// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5
// Source: merchant.proto

package merchantservice

import (
	"context"

	merchantv1 "mymall/api/gen/merchant/v1"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	ConsumeSeckillRequest    = merchantv1.ConsumeSeckillRequest
	ConsumeSeckillResponse   = merchantv1.ConsumeSeckillResponse
	EmptyResponse            = merchantv1.EmptyResponse
	LockCouponRequest        = merchantv1.LockCouponRequest
	MatchCouponView          = merchantv1.MatchCouponView
	MatchCouponsRequest      = merchantv1.MatchCouponsRequest
	MatchCouponsResponse     = merchantv1.MatchCouponsResponse
	MatchItem                = merchantv1.MatchItem
	OrderGiftCouponsRequest  = merchantv1.OrderGiftCouponsRequest
	OrderGiftCouponsResponse = merchantv1.OrderGiftCouponsResponse
	RedeemCouponRequest      = merchantv1.RedeemCouponRequest
	RestoreSeckillRequest    = merchantv1.RestoreSeckillRequest
	ReturnCouponRequest      = merchantv1.ReturnCouponRequest
	UnlockCouponRequest      = merchantv1.UnlockCouponRequest

	MerchantService interface {
		ConsumeSeckill(ctx context.Context, in *ConsumeSeckillRequest, opts ...grpc.CallOption) (*ConsumeSeckillResponse, error)
		RestoreSeckill(ctx context.Context, in *RestoreSeckillRequest, opts ...grpc.CallOption) (*EmptyResponse, error)
		MatchCoupons(ctx context.Context, in *MatchCouponsRequest, opts ...grpc.CallOption) (*MatchCouponsResponse, error)
		LockCoupon(ctx context.Context, in *LockCouponRequest, opts ...grpc.CallOption) (*EmptyResponse, error)
		UnlockCoupon(ctx context.Context, in *UnlockCouponRequest, opts ...grpc.CallOption) (*EmptyResponse, error)
		RedeemCoupon(ctx context.Context, in *RedeemCouponRequest, opts ...grpc.CallOption) (*EmptyResponse, error)
		ReturnCoupon(ctx context.Context, in *ReturnCouponRequest, opts ...grpc.CallOption) (*EmptyResponse, error)
		OrderGiftCoupons(ctx context.Context, in *OrderGiftCouponsRequest, opts ...grpc.CallOption) (*OrderGiftCouponsResponse, error)
	}

	defaultMerchantService struct {
		cli zrpc.Client
	}
)

func NewMerchantService(cli zrpc.Client) MerchantService {
	return &defaultMerchantService{
		cli: cli,
	}
}

func (m *defaultMerchantService) ConsumeSeckill(ctx context.Context, in *ConsumeSeckillRequest, opts ...grpc.CallOption) (*ConsumeSeckillResponse, error) {
	client := merchantv1.NewMerchantServiceClient(m.cli.Conn())
	return client.ConsumeSeckill(ctx, in, opts...)
}

func (m *defaultMerchantService) RestoreSeckill(ctx context.Context, in *RestoreSeckillRequest, opts ...grpc.CallOption) (*EmptyResponse, error) {
	client := merchantv1.NewMerchantServiceClient(m.cli.Conn())
	return client.RestoreSeckill(ctx, in, opts...)
}

func (m *defaultMerchantService) MatchCoupons(ctx context.Context, in *MatchCouponsRequest, opts ...grpc.CallOption) (*MatchCouponsResponse, error) {
	client := merchantv1.NewMerchantServiceClient(m.cli.Conn())
	return client.MatchCoupons(ctx, in, opts...)
}

func (m *defaultMerchantService) LockCoupon(ctx context.Context, in *LockCouponRequest, opts ...grpc.CallOption) (*EmptyResponse, error) {
	client := merchantv1.NewMerchantServiceClient(m.cli.Conn())
	return client.LockCoupon(ctx, in, opts...)
}

func (m *defaultMerchantService) UnlockCoupon(ctx context.Context, in *UnlockCouponRequest, opts ...grpc.CallOption) (*EmptyResponse, error) {
	client := merchantv1.NewMerchantServiceClient(m.cli.Conn())
	return client.UnlockCoupon(ctx, in, opts...)
}

func (m *defaultMerchantService) RedeemCoupon(ctx context.Context, in *RedeemCouponRequest, opts ...grpc.CallOption) (*EmptyResponse, error) {
	client := merchantv1.NewMerchantServiceClient(m.cli.Conn())
	return client.RedeemCoupon(ctx, in, opts...)
}

func (m *defaultMerchantService) ReturnCoupon(ctx context.Context, in *ReturnCouponRequest, opts ...grpc.CallOption) (*EmptyResponse, error) {
	client := merchantv1.NewMerchantServiceClient(m.cli.Conn())
	return client.ReturnCoupon(ctx, in, opts...)
}

func (m *defaultMerchantService) OrderGiftCoupons(ctx context.Context, in *OrderGiftCouponsRequest, opts ...grpc.CallOption) (*OrderGiftCouponsResponse, error) {
	client := merchantv1.NewMerchantServiceClient(m.cli.Conn())
	return client.OrderGiftCoupons(ctx, in, opts...)
}
