// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5
// Source: user.proto

package server

import (
	"context"

	rpclogic "mymall/services/user-service/internal/rpclogic"
	"mymall/services/user-service/internal/svc"
	userv1 "mymall/api/gen/user/v1"
)

type UserServiceServer struct {
	svcCtx *svc.ServiceContext
	userv1.UnimplementedUserServiceServer
}

func NewUserServiceServer(svcCtx *svc.ServiceContext) *UserServiceServer {
	return &UserServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *UserServiceServer) GetUser(ctx context.Context, in *userv1.GetUserRequest) (*userv1.GetUserResponse, error) {
	l := rpclogic.NewGetUserLogic(ctx, s.svcCtx)
	return l.GetUser(in)
}

func (s *UserServiceServer) GetAddress(ctx context.Context, in *userv1.GetAddressRequest) (*userv1.GetAddressResponse, error) {
	l := rpclogic.NewGetAddressLogic(ctx, s.svcCtx)
	return l.GetAddress(in)
}

func (s *UserServiceServer) FreezeWallet(ctx context.Context, in *userv1.WalletOpRequest) (*userv1.EmptyResponse, error) {
	l := rpclogic.NewFreezeWalletLogic(ctx, s.svcCtx)
	return l.FreezeWallet(in)
}

func (s *UserServiceServer) UnfreezeWallet(ctx context.Context, in *userv1.WalletOpRequest) (*userv1.EmptyResponse, error) {
	l := rpclogic.NewUnfreezeWalletLogic(ctx, s.svcCtx)
	return l.UnfreezeWallet(in)
}

func (s *UserServiceServer) SettleWallet(ctx context.Context, in *userv1.WalletOpRequest) (*userv1.EmptyResponse, error) {
	l := rpclogic.NewSettleWalletLogic(ctx, s.svcCtx)
	return l.SettleWallet(in)
}

func (s *UserServiceServer) Notify(ctx context.Context, in *userv1.NotifyRequest) (*userv1.EmptyResponse, error) {
	l := rpclogic.NewNotifyLogic(ctx, s.svcCtx)
	return l.Notify(in)
}

func (s *UserServiceServer) TaskEvent(ctx context.Context, in *userv1.TaskEventRequest) (*userv1.EmptyResponse, error) {
	l := rpclogic.NewTaskEventLogic(ctx, s.svcCtx)
	return l.TaskEvent(in)
}
