// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.8.5

package modelgen

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	couponScopesFieldNames          = builder.RawFieldNames(&CouponScope{})
	couponScopesRows                = strings.Join(couponScopesFieldNames, ",")
	couponScopesRowsExpectAutoSet   = strings.Join(stringx.Remove(couponScopesFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	couponScopesRowsWithPlaceHolder = strings.Join(stringx.Remove(couponScopesFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	couponScopesModel interface {
		Insert(ctx context.Context, data *CouponScope) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*CouponScope, error)
		FindOneByCouponIdRefTypeRefId(ctx context.Context, couponId uint64, refType string, refId uint64) (*CouponScope, error)
		Update(ctx context.Context, data *CouponScope) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultCouponScopesModel struct {
		conn  sqlx.SqlConn
		table string
	}

	CouponScope struct {
		ID       uint64 `db:"id"`
		CouponID uint64 `db:"coupon_id"`
		RefType  string `db:"ref_type"`
		RefID    uint64 `db:"ref_id"`
	}
)

func newCouponScopesModel(conn sqlx.SqlConn) *defaultCouponScopesModel {
	return &defaultCouponScopesModel{
		conn:  conn,
		table: "`coupon_scopes`",
	}
}

func (m *defaultCouponScopesModel) Delete(ctx context.Context, id uint64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultCouponScopesModel) FindOne(ctx context.Context, id uint64) (*CouponScope, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", couponScopesRows, m.table)
	var resp CouponScope
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultCouponScopesModel) FindOneByCouponIdRefTypeRefId(ctx context.Context, couponId uint64, refType string, refId uint64) (*CouponScope, error) {
	var resp CouponScope
	query := fmt.Sprintf("select %s from %s where `coupon_id` = ? and `ref_type` = ? and `ref_id` = ? limit 1", couponScopesRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, couponId, refType, refId)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultCouponScopesModel) Insert(ctx context.Context, data *CouponScope) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?)", m.table, couponScopesRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.CouponID, data.RefType, data.RefID)
	return ret, err
}

func (m *defaultCouponScopesModel) Update(ctx context.Context, newData *CouponScope) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, couponScopesRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.CouponID, newData.RefType, newData.RefID, newData.ID)
	return err
}

func (m *defaultCouponScopesModel) tableName() string {
	return m.table
}
