// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.8.5

package modelgen

import (
	"mymall/common"
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	couponGrantsFieldNames          = builder.RawFieldNames(&CouponGrant{})
	couponGrantsRows                = strings.Join(couponGrantsFieldNames, ",")
	couponGrantsRowsExpectAutoSet   = strings.Join(stringx.Remove(couponGrantsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	couponGrantsRowsWithPlaceHolder = strings.Join(stringx.Remove(couponGrantsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	couponGrantsModel interface {
		Insert(ctx context.Context, data *CouponGrant) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*CouponGrant, error)
		Update(ctx context.Context, data *CouponGrant) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultCouponGrantsModel struct {
		conn  sqlx.SqlConn
		table string
	}

	CouponGrant struct {
		ID           uint64    `db:"id"`
		CouponID     uint64    `db:"coupon_id"`
		OperatorID   uint64    `db:"operator_id"`
		IssuerType   string    `db:"issuer_type"`
		ShopID       uint64    `db:"shop_id"`
		UserCount    int     `db:"user_count"`
		SuccessCount int     `db:"success_count"`
		BatchNo      string    `db:"batch_no"`
		CreatedAt    common.LocalTime `db:"created_at"`
	}
)

func newCouponGrantsModel(conn sqlx.SqlConn) *defaultCouponGrantsModel {
	return &defaultCouponGrantsModel{
		conn:  conn,
		table: "`coupon_grants`",
	}
}

func (m *defaultCouponGrantsModel) Delete(ctx context.Context, id uint64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultCouponGrantsModel) FindOne(ctx context.Context, id uint64) (*CouponGrant, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", couponGrantsRows, m.table)
	var resp CouponGrant
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultCouponGrantsModel) Insert(ctx context.Context, data *CouponGrant) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?)", m.table, couponGrantsRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.CouponID, data.OperatorID, data.IssuerType, data.ShopID, data.UserCount, data.SuccessCount, data.BatchNo)
	return ret, err
}

func (m *defaultCouponGrantsModel) Update(ctx context.Context, data *CouponGrant) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, couponGrantsRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.CouponID, data.OperatorID, data.IssuerType, data.ShopID, data.UserCount, data.SuccessCount, data.BatchNo, data.ID)
	return err
}

func (m *defaultCouponGrantsModel) tableName() string {
	return m.table
}
