// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.8.5

package modelgen

import (
	"mymall/common"
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	couponsFieldNames          = builder.RawFieldNames(&Coupon{})
	couponsRows                = strings.Join(couponsFieldNames, ",")
	couponsRowsExpectAutoSet   = strings.Join(stringx.Remove(couponsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	couponsRowsWithPlaceHolder = strings.Join(stringx.Remove(couponsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	couponsModel interface {
		Insert(ctx context.Context, data *Coupon) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*Coupon, error)
		Update(ctx context.Context, data *Coupon) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultCouponsModel struct {
		conn  sqlx.SqlConn
		table string
	}

	Coupon struct {
		ID                uint64         `db:"id"`
		Name              string         `db:"name"`
		IssuerType        string         `db:"issuer_type"`
		ShopID            uint64         `db:"shop_id"`
		CouponType        string         `db:"coupon_type"`
		ThresholdAmount   float64        `db:"threshold_amount"`
		DiscountAmount    float64        `db:"discount_amount"`
		DiscountRate      float64        `db:"discount_rate"` // 0.80=八折
		MaxDiscountAmount float64        `db:"max_discount_amount"`
		ScopeType         string         `db:"scope_type"`
		TotalCount        int          `db:"total_count"` // 0=不限
		ClaimedCount      int          `db:"claimed_count"`
		PerUserLimit      int          `db:"per_user_limit"`
		ValidType         string         `db:"valid_type"`
		ValidStart        common.LocalTime   `db:"valid_start"`
		ValidEnd          common.LocalTime   `db:"valid_end"`
		ValidDays         int          `db:"valid_days"`
		Stackable         int          `db:"stackable"`
		UserIdentity      string         `db:"user_identity"`
		Channels          string `db:"channels"`
		Status            string         `db:"status"`
		Remark            string         `db:"remark"`
		CreatedBy         uint64         `db:"created_by"`
		CreatedAt         common.LocalTime      `db:"created_at"`
		UpdatedAt         common.LocalTime      `db:"updated_at"`
	}
)

func newCouponsModel(conn sqlx.SqlConn) *defaultCouponsModel {
	return &defaultCouponsModel{
		conn:  conn,
		table: "`coupons`",
	}
}

func (m *defaultCouponsModel) Delete(ctx context.Context, id uint64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultCouponsModel) FindOne(ctx context.Context, id uint64) (*Coupon, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", couponsRows, m.table)
	var resp Coupon
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultCouponsModel) Insert(ctx context.Context, data *Coupon) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, couponsRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Name, data.IssuerType, data.ShopID, data.CouponType, data.ThresholdAmount, data.DiscountAmount, data.DiscountRate, data.MaxDiscountAmount, data.ScopeType, data.TotalCount, data.ClaimedCount, data.PerUserLimit, data.ValidType, data.ValidStart, data.ValidEnd, data.ValidDays, data.Stackable, data.UserIdentity, data.Channels, data.Status, data.Remark, data.CreatedBy)
	return ret, err
}

func (m *defaultCouponsModel) Update(ctx context.Context, data *Coupon) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, couponsRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.Name, data.IssuerType, data.ShopID, data.CouponType, data.ThresholdAmount, data.DiscountAmount, data.DiscountRate, data.MaxDiscountAmount, data.ScopeType, data.TotalCount, data.ClaimedCount, data.PerUserLimit, data.ValidType, data.ValidStart, data.ValidEnd, data.ValidDays, data.Stackable, data.UserIdentity, data.Channels, data.Status, data.Remark, data.CreatedBy, data.ID)
	return err
}

func (m *defaultCouponsModel) tableName() string {
	return m.table
}
