// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.8.5

package modelgen

import (
	"mymall/common"
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	couponRedeemLogsFieldNames          = builder.RawFieldNames(&CouponRedeemLog{})
	couponRedeemLogsRows                = strings.Join(couponRedeemLogsFieldNames, ",")
	couponRedeemLogsRowsExpectAutoSet   = strings.Join(stringx.Remove(couponRedeemLogsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	couponRedeemLogsRowsWithPlaceHolder = strings.Join(stringx.Remove(couponRedeemLogsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	couponRedeemLogsModel interface {
		Insert(ctx context.Context, data *CouponRedeemLog) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*CouponRedeemLog, error)
		Update(ctx context.Context, data *CouponRedeemLog) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultCouponRedeemLogsModel struct {
		conn  sqlx.SqlConn
		table string
	}

	CouponRedeemLog struct {
		ID             uint64    `db:"id"`
		UserCouponID   uint64    `db:"user_coupon_id"`
		CouponID       uint64    `db:"coupon_id"`
		UserID         uint64    `db:"user_id"`
		OrderID        uint64    `db:"order_id"`
		ShopID         uint64    `db:"shop_id"`
		DiscountAmount float64   `db:"discount_amount"`
		Action         string    `db:"action"`
		CreatedAt      common.LocalTime `db:"created_at"`
	}
)

func newCouponRedeemLogsModel(conn sqlx.SqlConn) *defaultCouponRedeemLogsModel {
	return &defaultCouponRedeemLogsModel{
		conn:  conn,
		table: "`coupon_redeem_logs`",
	}
}

func (m *defaultCouponRedeemLogsModel) Delete(ctx context.Context, id uint64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultCouponRedeemLogsModel) FindOne(ctx context.Context, id uint64) (*CouponRedeemLog, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", couponRedeemLogsRows, m.table)
	var resp CouponRedeemLog
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultCouponRedeemLogsModel) Insert(ctx context.Context, data *CouponRedeemLog) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?)", m.table, couponRedeemLogsRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.UserCouponID, data.CouponID, data.UserID, data.OrderID, data.ShopID, data.DiscountAmount, data.Action)
	return ret, err
}

func (m *defaultCouponRedeemLogsModel) Update(ctx context.Context, data *CouponRedeemLog) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, couponRedeemLogsRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.UserCouponID, data.CouponID, data.UserID, data.OrderID, data.ShopID, data.DiscountAmount, data.Action, data.ID)
	return err
}

func (m *defaultCouponRedeemLogsModel) tableName() string {
	return m.table
}
