// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.8.5

package modelgen

import (
	"mymall/common"
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	homepageSlotSettingsFieldNames          = builder.RawFieldNames(&HomepageSlotSetting{})
	homepageSlotSettingsRows                = strings.Join(homepageSlotSettingsFieldNames, ",")
	homepageSlotSettingsRowsExpectAutoSet   = strings.Join(stringx.Remove(homepageSlotSettingsFieldNames, "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	homepageSlotSettingsRowsWithPlaceHolder = strings.Join(stringx.Remove(homepageSlotSettingsFieldNames, "`slot_type`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	homepageSlotSettingsModel interface {
		Insert(ctx context.Context, data *HomepageSlotSetting) (sql.Result, error)
		FindOne(ctx context.Context, slotType string) (*HomepageSlotSetting, error)
		Update(ctx context.Context, data *HomepageSlotSetting) error
		Delete(ctx context.Context, slotType string) error
	}

	defaultHomepageSlotSettingsModel struct {
		conn  sqlx.SqlConn
		table string
	}

	HomepageSlotSetting struct {
		SlotType  string    `db:"slot_type"`
		HomeLimit int     `db:"home_limit"` // 首页条带最多展示条数
		UpdatedAt common.LocalTime `db:"updated_at"`
	}
)

func newHomepageSlotSettingsModel(conn sqlx.SqlConn) *defaultHomepageSlotSettingsModel {
	return &defaultHomepageSlotSettingsModel{
		conn:  conn,
		table: "`homepage_slot_settings`",
	}
}

func (m *defaultHomepageSlotSettingsModel) Delete(ctx context.Context, slotType string) error {
	query := fmt.Sprintf("delete from %s where `slot_type` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, slotType)
	return err
}

func (m *defaultHomepageSlotSettingsModel) FindOne(ctx context.Context, slotType string) (*HomepageSlotSetting, error) {
	query := fmt.Sprintf("select %s from %s where `slot_type` = ? limit 1", homepageSlotSettingsRows, m.table)
	var resp HomepageSlotSetting
	err := m.conn.QueryRowCtx(ctx, &resp, query, slotType)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultHomepageSlotSettingsModel) Insert(ctx context.Context, data *HomepageSlotSetting) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?)", m.table, homepageSlotSettingsRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.SlotType, data.HomeLimit)
	return ret, err
}

func (m *defaultHomepageSlotSettingsModel) Update(ctx context.Context, data *HomepageSlotSetting) error {
	query := fmt.Sprintf("update %s set %s where `slot_type` = ?", m.table, homepageSlotSettingsRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.HomeLimit, data.SlotType)
	return err
}

func (m *defaultHomepageSlotSettingsModel) tableName() string {
	return m.table
}
