// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.8.5

package modelgen

import (
	"mymall/common"
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	homepageThemeOrdersFieldNames          = builder.RawFieldNames(&HomepageThemeOrder{})
	homepageThemeOrdersRows                = strings.Join(homepageThemeOrdersFieldNames, ",")
	homepageThemeOrdersRowsExpectAutoSet   = strings.Join(stringx.Remove(homepageThemeOrdersFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	homepageThemeOrdersRowsWithPlaceHolder = strings.Join(stringx.Remove(homepageThemeOrdersFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	homepageThemeOrdersModel interface {
		Insert(ctx context.Context, data *HomepageThemeOrder) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*HomepageThemeOrder, error)
		Update(ctx context.Context, data *HomepageThemeOrder) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultHomepageThemeOrdersModel struct {
		conn  sqlx.SqlConn
		table string
	}

	HomepageThemeOrder struct {
		ID           uint64    `db:"id"`
		ShopID       uint64    `db:"shop_id"`
		ThemeSlotID  uint64    `db:"theme_slot_id"`
		PackageID    uint64    `db:"package_id"`
		Title        string    `db:"title"`
		Subtitle     string    `db:"subtitle"`
		CoverURL     string    `db:"cover_url"`
		LinkType     string    `db:"link_type"`
		LinkID       uint64    `db:"link_id"`
		Amount       float64   `db:"amount"`
		DurationDays int     `db:"duration_days"`
		StartAt      common.LocalTime `db:"start_at"`
		EndAt        common.LocalTime `db:"end_at"`
		Status       string    `db:"status"`
		PaySource    string    `db:"pay_source"`
		WalletLogID  uint64    `db:"wallet_log_id"`
		OperatorID   uint64    `db:"operator_id"`
		CreatedAt    common.LocalTime `db:"created_at"`
		UpdatedAt    common.LocalTime `db:"updated_at"`
	}
)

func newHomepageThemeOrdersModel(conn sqlx.SqlConn) *defaultHomepageThemeOrdersModel {
	return &defaultHomepageThemeOrdersModel{
		conn:  conn,
		table: "`homepage_theme_orders`",
	}
}

func (m *defaultHomepageThemeOrdersModel) Delete(ctx context.Context, id uint64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultHomepageThemeOrdersModel) FindOne(ctx context.Context, id uint64) (*HomepageThemeOrder, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", homepageThemeOrdersRows, m.table)
	var resp HomepageThemeOrder
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultHomepageThemeOrdersModel) Insert(ctx context.Context, data *HomepageThemeOrder) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, homepageThemeOrdersRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.ShopID, data.ThemeSlotID, data.PackageID, data.Title, data.Subtitle, data.CoverURL, data.LinkType, data.LinkID, data.Amount, data.DurationDays, data.StartAt, data.EndAt, data.Status, data.PaySource, data.WalletLogID, data.OperatorID)
	return ret, err
}

func (m *defaultHomepageThemeOrdersModel) Update(ctx context.Context, data *HomepageThemeOrder) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, homepageThemeOrdersRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.ShopID, data.ThemeSlotID, data.PackageID, data.Title, data.Subtitle, data.CoverURL, data.LinkType, data.LinkID, data.Amount, data.DurationDays, data.StartAt, data.EndAt, data.Status, data.PaySource, data.WalletLogID, data.OperatorID, data.ID)
	return err
}

func (m *defaultHomepageThemeOrdersModel) tableName() string {
	return m.table
}
