// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.8.5

package modelgen

import (
	"mymall/common"
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	homepageThemePackagesFieldNames          = builder.RawFieldNames(&HomepageThemePackage{})
	homepageThemePackagesRows                = strings.Join(homepageThemePackagesFieldNames, ",")
	homepageThemePackagesRowsExpectAutoSet   = strings.Join(stringx.Remove(homepageThemePackagesFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	homepageThemePackagesRowsWithPlaceHolder = strings.Join(stringx.Remove(homepageThemePackagesFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	homepageThemePackagesModel interface {
		Insert(ctx context.Context, data *HomepageThemePackage) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*HomepageThemePackage, error)
		Update(ctx context.Context, data *HomepageThemePackage) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultHomepageThemePackagesModel struct {
		conn  sqlx.SqlConn
		table string
	}

	HomepageThemePackage struct {
		ID           uint64    `db:"id"`
		ThemeSlotID  uint64    `db:"theme_slot_id"` // 0=通用任意坑位
		Name         string    `db:"name"`
		Price        float64   `db:"price"`
		DurationDays int     `db:"duration_days"`
		Status       string    `db:"status"`
		Sort         int     `db:"sort"`
		Remark       string    `db:"remark"`
		CreatedAt    common.LocalTime `db:"created_at"`
		UpdatedAt    common.LocalTime `db:"updated_at"`
	}
)

func newHomepageThemePackagesModel(conn sqlx.SqlConn) *defaultHomepageThemePackagesModel {
	return &defaultHomepageThemePackagesModel{
		conn:  conn,
		table: "`homepage_theme_packages`",
	}
}

func (m *defaultHomepageThemePackagesModel) Delete(ctx context.Context, id uint64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultHomepageThemePackagesModel) FindOne(ctx context.Context, id uint64) (*HomepageThemePackage, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", homepageThemePackagesRows, m.table)
	var resp HomepageThemePackage
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultHomepageThemePackagesModel) Insert(ctx context.Context, data *HomepageThemePackage) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?)", m.table, homepageThemePackagesRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.ThemeSlotID, data.Name, data.Price, data.DurationDays, data.Status, data.Sort, data.Remark)
	return ret, err
}

func (m *defaultHomepageThemePackagesModel) Update(ctx context.Context, data *HomepageThemePackage) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, homepageThemePackagesRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.ThemeSlotID, data.Name, data.Price, data.DurationDays, data.Status, data.Sort, data.Remark, data.ID)
	return err
}

func (m *defaultHomepageThemePackagesModel) tableName() string {
	return m.table
}
