// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.8.5

package modelgen

import (
	"mymall/common"
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	homepageThemeSlotsFieldNames          = builder.RawFieldNames(&HomepageThemeSlot{})
	homepageThemeSlotsRows                = strings.Join(homepageThemeSlotsFieldNames, ",")
	homepageThemeSlotsRowsExpectAutoSet   = strings.Join(stringx.Remove(homepageThemeSlotsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	homepageThemeSlotsRowsWithPlaceHolder = strings.Join(stringx.Remove(homepageThemeSlotsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	homepageThemeSlotsModel interface {
		Insert(ctx context.Context, data *HomepageThemeSlot) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*HomepageThemeSlot, error)
		FindOneByPosition(ctx context.Context, position uint64) (*HomepageThemeSlot, error)
		FindOneBySlotKey(ctx context.Context, slotKey string) (*HomepageThemeSlot, error)
		Update(ctx context.Context, data *HomepageThemeSlot) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultHomepageThemeSlotsModel struct {
		conn  sqlx.SqlConn
		table string
	}

	HomepageThemeSlot struct {
		ID              uint64    `db:"id"`
		SlotKey         string    `db:"slot_key"`
		Position        uint64    `db:"position"`
		Name            string    `db:"name"`
		Desc            string    `db:"desc"`
		CoverURL        string    `db:"cover_url"`
		DefaultLinkType string    `db:"default_link_type"`
		DefaultLinkID   uint64    `db:"default_link_id"`
		Status          string    `db:"status"`
		Sort            int     `db:"sort"`
		CreatedAt       common.LocalTime `db:"created_at"`
		UpdatedAt       common.LocalTime `db:"updated_at"`
	}
)

func newHomepageThemeSlotsModel(conn sqlx.SqlConn) *defaultHomepageThemeSlotsModel {
	return &defaultHomepageThemeSlotsModel{
		conn:  conn,
		table: "`homepage_theme_slots`",
	}
}

func (m *defaultHomepageThemeSlotsModel) Delete(ctx context.Context, id uint64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultHomepageThemeSlotsModel) FindOne(ctx context.Context, id uint64) (*HomepageThemeSlot, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", homepageThemeSlotsRows, m.table)
	var resp HomepageThemeSlot
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultHomepageThemeSlotsModel) FindOneByPosition(ctx context.Context, position uint64) (*HomepageThemeSlot, error) {
	var resp HomepageThemeSlot
	query := fmt.Sprintf("select %s from %s where `position` = ? limit 1", homepageThemeSlotsRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, position)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultHomepageThemeSlotsModel) FindOneBySlotKey(ctx context.Context, slotKey string) (*HomepageThemeSlot, error) {
	var resp HomepageThemeSlot
	query := fmt.Sprintf("select %s from %s where `slot_key` = ? limit 1", homepageThemeSlotsRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, slotKey)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultHomepageThemeSlotsModel) Insert(ctx context.Context, data *HomepageThemeSlot) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, homepageThemeSlotsRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.SlotKey, data.Position, data.Name, data.Desc, data.CoverURL, data.DefaultLinkType, data.DefaultLinkID, data.Status, data.Sort)
	return ret, err
}

func (m *defaultHomepageThemeSlotsModel) Update(ctx context.Context, newData *HomepageThemeSlot) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, homepageThemeSlotsRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.SlotKey, newData.Position, newData.Name, newData.Desc, newData.CoverURL, newData.DefaultLinkType, newData.DefaultLinkID, newData.Status, newData.Sort, newData.ID)
	return err
}

func (m *defaultHomepageThemeSlotsModel) tableName() string {
	return m.table
}
