// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.8.5

package modelgen

import (
	"mymall/common"
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	homepageSlotPackagesFieldNames          = builder.RawFieldNames(&HomepageSlotPackage{})
	homepageSlotPackagesRows                = strings.Join(homepageSlotPackagesFieldNames, ",")
	homepageSlotPackagesRowsExpectAutoSet   = strings.Join(stringx.Remove(homepageSlotPackagesFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	homepageSlotPackagesRowsWithPlaceHolder = strings.Join(stringx.Remove(homepageSlotPackagesFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	homepageSlotPackagesModel interface {
		Insert(ctx context.Context, data *HomepageSlotPackage) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*HomepageSlotPackage, error)
		Update(ctx context.Context, data *HomepageSlotPackage) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultHomepageSlotPackagesModel struct {
		conn  sqlx.SqlConn
		table string
	}

	HomepageSlotPackage struct {
		ID           uint64    `db:"id"`
		SlotType     string    `db:"slot_type"` // brand_shop/quality_shop/article
		Name         string    `db:"name"`
		Price        float64   `db:"price"`
		DurationDays int     `db:"duration_days"`
		Status       string    `db:"status"` // on/off
		Sort         int     `db:"sort"`
		Remark       string    `db:"remark"`
		CreatedAt    common.LocalTime `db:"created_at"`
		UpdatedAt    common.LocalTime `db:"updated_at"`
	}
)

func newHomepageSlotPackagesModel(conn sqlx.SqlConn) *defaultHomepageSlotPackagesModel {
	return &defaultHomepageSlotPackagesModel{
		conn:  conn,
		table: "`homepage_slot_packages`",
	}
}

func (m *defaultHomepageSlotPackagesModel) Delete(ctx context.Context, id uint64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultHomepageSlotPackagesModel) FindOne(ctx context.Context, id uint64) (*HomepageSlotPackage, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", homepageSlotPackagesRows, m.table)
	var resp HomepageSlotPackage
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultHomepageSlotPackagesModel) Insert(ctx context.Context, data *HomepageSlotPackage) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?)", m.table, homepageSlotPackagesRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.SlotType, data.Name, data.Price, data.DurationDays, data.Status, data.Sort, data.Remark)
	return ret, err
}

func (m *defaultHomepageSlotPackagesModel) Update(ctx context.Context, data *HomepageSlotPackage) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, homepageSlotPackagesRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.SlotType, data.Name, data.Price, data.DurationDays, data.Status, data.Sort, data.Remark, data.ID)
	return err
}

func (m *defaultHomepageSlotPackagesModel) tableName() string {
	return m.table
}
