// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.8.5

package modelgen

import (
	"mymall/common"
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	homepageSlotOrdersFieldNames          = builder.RawFieldNames(&HomepageSlotOrder{})
	homepageSlotOrdersRows                = strings.Join(homepageSlotOrdersFieldNames, ",")
	homepageSlotOrdersRowsExpectAutoSet   = strings.Join(stringx.Remove(homepageSlotOrdersFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	homepageSlotOrdersRowsWithPlaceHolder = strings.Join(stringx.Remove(homepageSlotOrdersFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	homepageSlotOrdersModel interface {
		Insert(ctx context.Context, data *HomepageSlotOrder) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*HomepageSlotOrder, error)
		Update(ctx context.Context, data *HomepageSlotOrder) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultHomepageSlotOrdersModel struct {
		conn  sqlx.SqlConn
		table string
	}

	HomepageSlotOrder struct {
		ID           uint64    `db:"id"`
		ShopID       uint64    `db:"shop_id"`
		SlotType     string    `db:"slot_type"`
		PackageID    uint64    `db:"package_id"`
		TargetID     uint64    `db:"target_id"` // 店铺=shop_id；文章=article_id
		Amount       float64   `db:"amount"`
		DurationDays int     `db:"duration_days"`
		StartAt      common.LocalTime `db:"start_at"`
		EndAt        common.LocalTime `db:"end_at"`
		Status       string    `db:"status"`     // active/expired/cancelled
		PaySource    string    `db:"pay_source"` // wallet/admin
		WalletLogID  uint64    `db:"wallet_log_id"`
		OperatorID   uint64    `db:"operator_id"`
		CreatedAt    common.LocalTime `db:"created_at"`
		UpdatedAt    common.LocalTime `db:"updated_at"`
	}
)

func newHomepageSlotOrdersModel(conn sqlx.SqlConn) *defaultHomepageSlotOrdersModel {
	return &defaultHomepageSlotOrdersModel{
		conn:  conn,
		table: "`homepage_slot_orders`",
	}
}

func (m *defaultHomepageSlotOrdersModel) Delete(ctx context.Context, id uint64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultHomepageSlotOrdersModel) FindOne(ctx context.Context, id uint64) (*HomepageSlotOrder, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", homepageSlotOrdersRows, m.table)
	var resp HomepageSlotOrder
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultHomepageSlotOrdersModel) Insert(ctx context.Context, data *HomepageSlotOrder) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, homepageSlotOrdersRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.ShopID, data.SlotType, data.PackageID, data.TargetID, data.Amount, data.DurationDays, data.StartAt, data.EndAt, data.Status, data.PaySource, data.WalletLogID, data.OperatorID)
	return ret, err
}

func (m *defaultHomepageSlotOrdersModel) Update(ctx context.Context, data *HomepageSlotOrder) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, homepageSlotOrdersRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.ShopID, data.SlotType, data.PackageID, data.TargetID, data.Amount, data.DurationDays, data.StartAt, data.EndAt, data.Status, data.PaySource, data.WalletLogID, data.OperatorID, data.ID)
	return err
}

func (m *defaultHomepageSlotOrdersModel) tableName() string {
	return m.table
}
