// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.8.5

package modelgen

import (
	"mymall/common"
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	seckillSessionsFieldNames          = builder.RawFieldNames(&SeckillSession{})
	seckillSessionsRows                = strings.Join(seckillSessionsFieldNames, ",")
	seckillSessionsRowsExpectAutoSet   = strings.Join(stringx.Remove(seckillSessionsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	seckillSessionsRowsWithPlaceHolder = strings.Join(stringx.Remove(seckillSessionsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	seckillSessionsModel interface {
		Insert(ctx context.Context, data *SeckillSession) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*SeckillSession, error)
		Update(ctx context.Context, data *SeckillSession) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultSeckillSessionsModel struct {
		conn  sqlx.SqlConn
		table string
	}

	SeckillSession struct {
		ID        uint64    `db:"id"`
		RuleID    uint64    `db:"rule_id"`
		StartAt   common.LocalTime `db:"start_at"`
		EndAt     common.LocalTime `db:"end_at"`
		Status    string    `db:"status"` // active/ended
		CreatedAt common.LocalTime `db:"created_at"`
		UpdatedAt common.LocalTime `db:"updated_at"`
	}
)

func newSeckillSessionsModel(conn sqlx.SqlConn) *defaultSeckillSessionsModel {
	return &defaultSeckillSessionsModel{
		conn:  conn,
		table: "`seckill_sessions`",
	}
}

func (m *defaultSeckillSessionsModel) Delete(ctx context.Context, id uint64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultSeckillSessionsModel) FindOne(ctx context.Context, id uint64) (*SeckillSession, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", seckillSessionsRows, m.table)
	var resp SeckillSession
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultSeckillSessionsModel) Insert(ctx context.Context, data *SeckillSession) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?)", m.table, seckillSessionsRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.RuleID, data.StartAt, data.EndAt, data.Status)
	return ret, err
}

func (m *defaultSeckillSessionsModel) Update(ctx context.Context, data *SeckillSession) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, seckillSessionsRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.RuleID, data.StartAt, data.EndAt, data.Status, data.ID)
	return err
}

func (m *defaultSeckillSessionsModel) tableName() string {
	return m.table
}
