// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.8.5

package modelgen

import (
	"mymall/common"
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	seckillEntriesFieldNames          = builder.RawFieldNames(&SeckillEntry{})
	seckillEntriesRows                = strings.Join(seckillEntriesFieldNames, ",")
	seckillEntriesRowsExpectAutoSet   = strings.Join(stringx.Remove(seckillEntriesFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	seckillEntriesRowsWithPlaceHolder = strings.Join(stringx.Remove(seckillEntriesFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	seckillEntriesModel interface {
		Insert(ctx context.Context, data *SeckillEntry) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*SeckillEntry, error)
		FindOneBySessionIdShopIdProductId(ctx context.Context, sessionId uint64, shopId uint64, productId uint64) (*SeckillEntry, error)
		Update(ctx context.Context, data *SeckillEntry) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultSeckillEntriesModel struct {
		conn  sqlx.SqlConn
		table string
	}

	SeckillEntry struct {
		ID           uint64    `db:"id"`
		SessionID    uint64    `db:"session_id"`
		ShopID       uint64    `db:"shop_id"`
		ProductID    uint64    `db:"product_id"`
		ProductName  string    `db:"product_name"`
		ProductImage string    `db:"product_image"`
		OriginPrice  float64   `db:"origin_price"`
		SeckillPrice float64   `db:"seckill_price"`
		SeckillStock int     `db:"seckill_stock"`
		FeeAmount    float64   `db:"fee_amount"`
		Status       string    `db:"status"`
		CreatedAt    common.LocalTime `db:"created_at"`
		UpdatedAt    common.LocalTime `db:"updated_at"`
	}
)

func newSeckillEntriesModel(conn sqlx.SqlConn) *defaultSeckillEntriesModel {
	return &defaultSeckillEntriesModel{
		conn:  conn,
		table: "`seckill_entries`",
	}
}

func (m *defaultSeckillEntriesModel) Delete(ctx context.Context, id uint64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultSeckillEntriesModel) FindOne(ctx context.Context, id uint64) (*SeckillEntry, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", seckillEntriesRows, m.table)
	var resp SeckillEntry
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultSeckillEntriesModel) FindOneBySessionIdShopIdProductId(ctx context.Context, sessionId uint64, shopId uint64, productId uint64) (*SeckillEntry, error) {
	var resp SeckillEntry
	query := fmt.Sprintf("select %s from %s where `session_id` = ? and `shop_id` = ? and `product_id` = ? limit 1", seckillEntriesRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, sessionId, shopId, productId)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultSeckillEntriesModel) Insert(ctx context.Context, data *SeckillEntry) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, seckillEntriesRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.SessionID, data.ShopID, data.ProductID, data.ProductName, data.ProductImage, data.OriginPrice, data.SeckillPrice, data.SeckillStock, data.FeeAmount, data.Status)
	return ret, err
}

func (m *defaultSeckillEntriesModel) Update(ctx context.Context, newData *SeckillEntry) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, seckillEntriesRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.SessionID, newData.ShopID, newData.ProductID, newData.ProductName, newData.ProductImage, newData.OriginPrice, newData.SeckillPrice, newData.SeckillStock, newData.FeeAmount, newData.Status, newData.ID)
	return err
}

func (m *defaultSeckillEntriesModel) tableName() string {
	return m.table
}
