// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.8.5

package modelgen

import (
	"mymall/common"
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	seckillRulesFieldNames          = builder.RawFieldNames(&SeckillRule{})
	seckillRulesRows                = strings.Join(seckillRulesFieldNames, ",")
	seckillRulesRowsExpectAutoSet   = strings.Join(stringx.Remove(seckillRulesFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	seckillRulesRowsWithPlaceHolder = strings.Join(stringx.Remove(seckillRulesFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	seckillRulesModel interface {
		Insert(ctx context.Context, data *SeckillRule) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*SeckillRule, error)
		Update(ctx context.Context, data *SeckillRule) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultSeckillRulesModel struct {
		conn  sqlx.SqlConn
		table string
	}

	SeckillRule struct {
		ID                uint64    `db:"id"`
		DurationHours     int     `db:"duration_hours"`       // 场次时长(小时)
		ApplyFee          float64   `db:"apply_fee"`            // 报名费
		MaxEntriesPerShop int     `db:"max_entries_per_shop"` // 每店每场最多报名数
		Status            int     `db:"status"`               // 1启用 0停用
		CreatedAt         common.LocalTime `db:"created_at"`
		UpdatedAt         common.LocalTime `db:"updated_at"`
	}
)

func newSeckillRulesModel(conn sqlx.SqlConn) *defaultSeckillRulesModel {
	return &defaultSeckillRulesModel{
		conn:  conn,
		table: "`seckill_rules`",
	}
}

func (m *defaultSeckillRulesModel) Delete(ctx context.Context, id uint64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultSeckillRulesModel) FindOne(ctx context.Context, id uint64) (*SeckillRule, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", seckillRulesRows, m.table)
	var resp SeckillRule
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultSeckillRulesModel) Insert(ctx context.Context, data *SeckillRule) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?)", m.table, seckillRulesRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.DurationHours, data.ApplyFee, data.MaxEntriesPerShop, data.Status)
	return ret, err
}

func (m *defaultSeckillRulesModel) Update(ctx context.Context, data *SeckillRule) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, seckillRulesRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.DurationHours, data.ApplyFee, data.MaxEntriesPerShop, data.Status, data.ID)
	return err
}

func (m *defaultSeckillRulesModel) tableName() string {
	return m.table
}
