// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.8.5

package modelgen

import (
	"mymall/common"
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	shopsFieldNames          = builder.RawFieldNames(&Shop{})
	shopsRows                = strings.Join(shopsFieldNames, ",")
	shopsRowsExpectAutoSet   = strings.Join(stringx.Remove(shopsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	shopsRowsWithPlaceHolder = strings.Join(stringx.Remove(shopsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	shopsModel interface {
		Insert(ctx context.Context, data *Shop) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*Shop, error)
		Update(ctx context.Context, data *Shop) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultShopsModel struct {
		conn  sqlx.SqlConn
		table string
	}

	Shop struct {
		ID                uint64    `db:"id"`
		Name              string    `db:"name"`          // 店铺名称
		Logo              string    `db:"logo"`          // Logo
		ContactName       string    `db:"contact_name"`  // 联系人
		ContactPhone      string    `db:"contact_phone"` // 联系电话
		Description       string    `db:"description"`   // 简介
		Category          string    `db:"category"`      // 经营类目
		Province          string    `db:"province"`
		City              string    `db:"city"`
		District          string    `db:"district"`
		Address           string    `db:"address"`             // 详细地址
		BusinessLicenseNo string    `db:"business_license_no"` // 营业执照号
		LegalPerson       string    `db:"legal_person"`        // 法人
		LicenseImage      string    `db:"license_image"`       // 执照图
		StorefrontImage   string    `db:"storefront_image"`    // 门头图
		OwnerUserID       uint64    `db:"owner_user_id"`       // 店主用户ID
		Status            string    `db:"status"`              // 状态
		RejectReason      string    `db:"reject_reason"`       // 拒绝原因
		CreatedAt         common.LocalTime `db:"created_at"`
		UpdatedAt         common.LocalTime `db:"updated_at"`
	}
)

func newShopsModel(conn sqlx.SqlConn) *defaultShopsModel {
	return &defaultShopsModel{
		conn:  conn,
		table: "`shops`",
	}
}

func (m *defaultShopsModel) Delete(ctx context.Context, id uint64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultShopsModel) FindOne(ctx context.Context, id uint64) (*Shop, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", shopsRows, m.table)
	var resp Shop
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultShopsModel) Insert(ctx context.Context, data *Shop) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, shopsRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Name, data.Logo, data.ContactName, data.ContactPhone, data.Description, data.Category, data.Province, data.City, data.District, data.Address, data.BusinessLicenseNo, data.LegalPerson, data.LicenseImage, data.StorefrontImage, data.OwnerUserID, data.Status, data.RejectReason)
	return ret, err
}

func (m *defaultShopsModel) Update(ctx context.Context, data *Shop) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, shopsRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.Name, data.Logo, data.ContactName, data.ContactPhone, data.Description, data.Category, data.Province, data.City, data.District, data.Address, data.BusinessLicenseNo, data.LegalPerson, data.LicenseImage, data.StorefrontImage, data.OwnerUserID, data.Status, data.RejectReason, data.ID)
	return err
}

func (m *defaultShopsModel) tableName() string {
	return m.table
}
