// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.8.5

package modelgen

import (
	"mymall/common"
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	shopMembersFieldNames          = builder.RawFieldNames(&ShopMember{})
	shopMembersRows                = strings.Join(shopMembersFieldNames, ",")
	shopMembersRowsExpectAutoSet   = strings.Join(stringx.Remove(shopMembersFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	shopMembersRowsWithPlaceHolder = strings.Join(stringx.Remove(shopMembersFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	shopMembersModel interface {
		Insert(ctx context.Context, data *ShopMember) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*ShopMember, error)
		FindOneByShopIdUserId(ctx context.Context, shopId uint64, userId uint64) (*ShopMember, error)
		Update(ctx context.Context, data *ShopMember) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultShopMembersModel struct {
		conn  sqlx.SqlConn
		table string
	}

	ShopMember struct {
		ID         uint64    `db:"id"`
		ShopID     uint64    `db:"shop_id"`
		UserID     uint64    `db:"user_id"`
		MemberRole string    `db:"member_role"`
		CreatedAt  common.LocalTime `db:"created_at"`
		UpdatedAt  common.LocalTime `db:"updated_at"`
	}
)

func newShopMembersModel(conn sqlx.SqlConn) *defaultShopMembersModel {
	return &defaultShopMembersModel{
		conn:  conn,
		table: "`shop_members`",
	}
}

func (m *defaultShopMembersModel) Delete(ctx context.Context, id uint64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultShopMembersModel) FindOne(ctx context.Context, id uint64) (*ShopMember, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", shopMembersRows, m.table)
	var resp ShopMember
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultShopMembersModel) FindOneByShopIdUserId(ctx context.Context, shopId uint64, userId uint64) (*ShopMember, error) {
	var resp ShopMember
	query := fmt.Sprintf("select %s from %s where `shop_id` = ? and `user_id` = ? limit 1", shopMembersRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, shopId, userId)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultShopMembersModel) Insert(ctx context.Context, data *ShopMember) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?)", m.table, shopMembersRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.ShopID, data.UserID, data.MemberRole)
	return ret, err
}

func (m *defaultShopMembersModel) Update(ctx context.Context, newData *ShopMember) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, shopMembersRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.ShopID, newData.UserID, newData.MemberRole, newData.ID)
	return err
}

func (m *defaultShopMembersModel) tableName() string {
	return m.table
}
