// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.8.5

package modelgen

import (
	"mymall/common"
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	shopWalletLogsFieldNames          = builder.RawFieldNames(&ShopWalletLog{})
	shopWalletLogsRows                = strings.Join(shopWalletLogsFieldNames, ",")
	shopWalletLogsRowsExpectAutoSet   = strings.Join(stringx.Remove(shopWalletLogsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	shopWalletLogsRowsWithPlaceHolder = strings.Join(stringx.Remove(shopWalletLogsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	shopWalletLogsModel interface {
		Insert(ctx context.Context, data *ShopWalletLog) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*ShopWalletLog, error)
		Update(ctx context.Context, data *ShopWalletLog) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultShopWalletLogsModel struct {
		conn  sqlx.SqlConn
		table string
	}

	ShopWalletLog struct {
		ID             uint64        `db:"id"`
		ShopID         uint64        `db:"shop_id"`
		ChangeType     string        `db:"change_type"` // admin_adjust/seckill_apply
		Amount         float64       `db:"amount"`      // 变动金额，正加负减
		BalanceAfter   float64       `db:"balance_after"`
		FrozenAfter    float64       `db:"frozen_after"`
		DepositAfter   float64       `db:"deposit_after"`
		Remark         string        `db:"remark"`
		OperatorUserID sql.NullInt64 `db:"operator_user_id"`
		RefType        string        `db:"ref_type"`
		RefID          uint64        `db:"ref_id"`
		CreatedAt      common.LocalTime     `db:"created_at"`
	}
)

func newShopWalletLogsModel(conn sqlx.SqlConn) *defaultShopWalletLogsModel {
	return &defaultShopWalletLogsModel{
		conn:  conn,
		table: "`shop_wallet_logs`",
	}
}

func (m *defaultShopWalletLogsModel) Delete(ctx context.Context, id uint64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultShopWalletLogsModel) FindOne(ctx context.Context, id uint64) (*ShopWalletLog, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", shopWalletLogsRows, m.table)
	var resp ShopWalletLog
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultShopWalletLogsModel) Insert(ctx context.Context, data *ShopWalletLog) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, shopWalletLogsRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.ShopID, data.ChangeType, data.Amount, data.BalanceAfter, data.FrozenAfter, data.DepositAfter, data.Remark, data.OperatorUserID, data.RefType, data.RefID)
	return ret, err
}

func (m *defaultShopWalletLogsModel) Update(ctx context.Context, data *ShopWalletLog) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, shopWalletLogsRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.ShopID, data.ChangeType, data.Amount, data.BalanceAfter, data.FrozenAfter, data.DepositAfter, data.Remark, data.OperatorUserID, data.RefType, data.RefID, data.ID)
	return err
}

func (m *defaultShopWalletLogsModel) tableName() string {
	return m.table
}
