// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.8.5

package modelgen

import (
	"mymall/common"
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	shopApplicationsFieldNames          = builder.RawFieldNames(&ShopApplication{})
	shopApplicationsRows                = strings.Join(shopApplicationsFieldNames, ",")
	shopApplicationsRowsExpectAutoSet   = strings.Join(stringx.Remove(shopApplicationsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	shopApplicationsRowsWithPlaceHolder = strings.Join(stringx.Remove(shopApplicationsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	shopApplicationsModel interface {
		Insert(ctx context.Context, data *ShopApplication) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*ShopApplication, error)
		Update(ctx context.Context, data *ShopApplication) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultShopApplicationsModel struct {
		conn  sqlx.SqlConn
		table string
	}

	ShopApplication struct {
		ID                uint64        `db:"id"`
		UserID            uint64        `db:"user_id"` // 申请人
		ShopName          string        `db:"shop_name"`
		ContactName       string        `db:"contact_name"`
		ContactPhone      string        `db:"contact_phone"`
		Description       string        `db:"description"`
		Category          string        `db:"category"`
		Province          string        `db:"province"`
		City              string        `db:"city"`
		District          string        `db:"district"`
		Address           string        `db:"address"`
		BusinessLicenseNo string        `db:"business_license_no"`
		LegalPerson       string        `db:"legal_person"`
		LicenseImage      string        `db:"license_image"`
		StorefrontImage   string        `db:"storefront_image"`
		Status            string        `db:"status"`
		RejectReason      string        `db:"reject_reason"`
		ReviewedBy        sql.NullInt64 `db:"reviewed_by"`
		ReviewedAt        common.LocalTime  `db:"reviewed_at"`
		ShopID            sql.NullInt64 `db:"shop_id"` // 审核通过后关联店铺
		CreatedAt         common.LocalTime     `db:"created_at"`
		UpdatedAt         common.LocalTime     `db:"updated_at"`
	}
)

func newShopApplicationsModel(conn sqlx.SqlConn) *defaultShopApplicationsModel {
	return &defaultShopApplicationsModel{
		conn:  conn,
		table: "`shop_applications`",
	}
}

func (m *defaultShopApplicationsModel) Delete(ctx context.Context, id uint64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultShopApplicationsModel) FindOne(ctx context.Context, id uint64) (*ShopApplication, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", shopApplicationsRows, m.table)
	var resp ShopApplication
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultShopApplicationsModel) Insert(ctx context.Context, data *ShopApplication) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, shopApplicationsRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.UserID, data.ShopName, data.ContactName, data.ContactPhone, data.Description, data.Category, data.Province, data.City, data.District, data.Address, data.BusinessLicenseNo, data.LegalPerson, data.LicenseImage, data.StorefrontImage, data.Status, data.RejectReason, data.ReviewedBy, data.ReviewedAt, data.ShopID)
	return ret, err
}

func (m *defaultShopApplicationsModel) Update(ctx context.Context, data *ShopApplication) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, shopApplicationsRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.UserID, data.ShopName, data.ContactName, data.ContactPhone, data.Description, data.Category, data.Province, data.City, data.District, data.Address, data.BusinessLicenseNo, data.LegalPerson, data.LicenseImage, data.StorefrontImage, data.Status, data.RejectReason, data.ReviewedBy, data.ReviewedAt, data.ShopID, data.ID)
	return err
}

func (m *defaultShopApplicationsModel) tableName() string {
	return m.table
}
