// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.8.5

package modelgen

import (
	"mymall/common"
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	shopWalletsFieldNames          = builder.RawFieldNames(&ShopWallet{})
	shopWalletsRows                = strings.Join(shopWalletsFieldNames, ",")
	shopWalletsRowsExpectAutoSet   = strings.Join(stringx.Remove(shopWalletsFieldNames, "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	shopWalletsRowsWithPlaceHolder = strings.Join(stringx.Remove(shopWalletsFieldNames, "`shop_id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	shopWalletsModel interface {
		Insert(ctx context.Context, data *ShopWallet) (sql.Result, error)
		FindOne(ctx context.Context, shopId uint64) (*ShopWallet, error)
		Update(ctx context.Context, data *ShopWallet) error
		Delete(ctx context.Context, shopId uint64) error
	}

	defaultShopWalletsModel struct {
		conn  sqlx.SqlConn
		table string
	}

	ShopWallet struct {
		ShopID        uint64    `db:"shop_id"`        // 店铺ID
		Balance       float64   `db:"balance"`        // 可用余额
		FrozenBalance float64   `db:"frozen_balance"` // 冻结余额
		Deposit       float64   `db:"deposit"`        // 保证金
		CreatedAt     common.LocalTime `db:"created_at"`
		UpdatedAt     common.LocalTime `db:"updated_at"`
	}
)

func newShopWalletsModel(conn sqlx.SqlConn) *defaultShopWalletsModel {
	return &defaultShopWalletsModel{
		conn:  conn,
		table: "`shop_wallets`",
	}
}

func (m *defaultShopWalletsModel) Delete(ctx context.Context, shopId uint64) error {
	query := fmt.Sprintf("delete from %s where `shop_id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, shopId)
	return err
}

func (m *defaultShopWalletsModel) FindOne(ctx context.Context, shopId uint64) (*ShopWallet, error) {
	query := fmt.Sprintf("select %s from %s where `shop_id` = ? limit 1", shopWalletsRows, m.table)
	var resp ShopWallet
	err := m.conn.QueryRowCtx(ctx, &resp, query, shopId)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultShopWalletsModel) Insert(ctx context.Context, data *ShopWallet) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?)", m.table, shopWalletsRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.ShopID, data.Balance, data.FrozenBalance, data.Deposit)
	return ret, err
}

func (m *defaultShopWalletsModel) Update(ctx context.Context, data *ShopWallet) error {
	query := fmt.Sprintf("update %s set %s where `shop_id` = ?", m.table, shopWalletsRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.Balance, data.FrozenBalance, data.Deposit, data.ShopID)
	return err
}

func (m *defaultShopWalletsModel) tableName() string {
	return m.table
}
