// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.8.5

package modelgen

import (
	"mymall/common"
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	userCouponsFieldNames          = builder.RawFieldNames(&UserCoupon{})
	userCouponsRows                = strings.Join(userCouponsFieldNames, ",")
	userCouponsRowsExpectAutoSet   = strings.Join(stringx.Remove(userCouponsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	userCouponsRowsWithPlaceHolder = strings.Join(stringx.Remove(userCouponsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	userCouponsModel interface {
		Insert(ctx context.Context, data *UserCoupon) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*UserCoupon, error)
		Update(ctx context.Context, data *UserCoupon) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultUserCouponsModel struct {
		conn  sqlx.SqlConn
		table string
	}

	UserCoupon struct {
		ID             uint64       `db:"id"`
		CouponID       uint64       `db:"coupon_id"`
		UserID         uint64       `db:"user_id"`
		ShopID         uint64       `db:"shop_id"`
		Status         string       `db:"status"`
		Source         string       `db:"source"`
		ValidStart     common.LocalTime    `db:"valid_start"`
		ValidEnd       common.LocalTime    `db:"valid_end"`
		OrderID        uint64       `db:"order_id"`
		LockedAt       common.LocalTime `db:"locked_at"`
		UsedAt         common.LocalTime `db:"used_at"`
		ClaimBatchNo   string       `db:"claim_batch_no"`
		DiscountAmount float64      `db:"discount_amount"` // 核销时实际抵扣
		CreatedAt      common.LocalTime    `db:"created_at"`
		UpdatedAt      common.LocalTime    `db:"updated_at"`
	}
)

func newUserCouponsModel(conn sqlx.SqlConn) *defaultUserCouponsModel {
	return &defaultUserCouponsModel{
		conn:  conn,
		table: "`user_coupons`",
	}
}

func (m *defaultUserCouponsModel) Delete(ctx context.Context, id uint64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultUserCouponsModel) FindOne(ctx context.Context, id uint64) (*UserCoupon, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", userCouponsRows, m.table)
	var resp UserCoupon
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUserCouponsModel) Insert(ctx context.Context, data *UserCoupon) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, userCouponsRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.CouponID, data.UserID, data.ShopID, data.Status, data.Source, data.ValidStart, data.ValidEnd, data.OrderID, data.LockedAt, data.UsedAt, data.ClaimBatchNo, data.DiscountAmount)
	return ret, err
}

func (m *defaultUserCouponsModel) Update(ctx context.Context, data *UserCoupon) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, userCouponsRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.CouponID, data.UserID, data.ShopID, data.Status, data.Source, data.ValidStart, data.ValidEnd, data.OrderID, data.LockedAt, data.UsedAt, data.ClaimBatchNo, data.DiscountAmount, data.ID)
	return err
}

func (m *defaultUserCouponsModel) tableName() string {
	return m.table
}
