apiVersion: v1
kind: Secret
metadata:
  name: mymall-rabbitmq
  namespace: mymall
type: Opaque
stringData:
  host: host.docker.internal
  port: "5672"
  username: mymall
  password: mymall
  vhost: /
