apiVersion: v1
kind: ConfigMap
metadata:
  name: order-service-config
  namespace: mymall
data:
  order-service.yaml: |
    server:
      http_port: 8888
      mode: release
    mysql:
      port: 3306
      charset: utf8mb4
      dbname: mymall
      max_open_conns: 20
      max_idle_conns: 5
    grpc:
      user_service: user-service:9090
      catalog_service: catalog-service:9090
    rabbitmq:
      port: 5672
      vhost: /
      exchange: mymall.events
    telemetry:
      enabled: false
      service: order-service
