// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5

package types

type AddressReq struct {
	ReceiverName  string `json:"receiver_name"`
	ReceiverPhone string `json:"receiver_phone"`
	Province      string `json:"province"`
	City          string `json:"city"`
	District      string `json:"district"`
	Detail        string `json:"detail"`
	ProvinceCode  string `json:"province_code"`
	CityCode      string `json:"city_code"`
	DistrictCode  string `json:"district_code"`
	IsDefault     int    `json:"is_default,optional"`
}

type AddressUpdateReq struct {
	Id            uint64 `path:"id"`
	ReceiverName  string `json:"receiver_name,optional"`
	ReceiverPhone string `json:"receiver_phone,optional"`
	Province      string `json:"province,optional"`
	City          string `json:"city,optional"`
	District      string `json:"district,optional"`
	Detail        string `json:"detail,optional"`
	ProvinceCode  string `json:"province_code,optional"`
	CityCode      string `json:"city_code,optional"`
	DistrictCode  string `json:"district_code,optional"`
	IsDefault     int    `json:"is_default,optional"`
}

type AdminCreateReq struct {
	Mobile   string   `json:"mobile"`
	Password string   `json:"password"`
	Nickname string   `json:"nickname,optional"`
	RoleIDs  []uint64 `json:"role_ids,optional"`
}

type AdminResetPwdReq struct {
	Id       uint64 `path:"id"`
	Password string `json:"password"`
}

type AdminRolesReq struct {
	Id      uint64   `path:"id"`
	RoleIDs []uint64 `json:"role_ids"`
}

type AdminSendReq struct {
	Title   string   `json:"title"`
	Content string   `json:"content"`
	UserIDs []uint64 `json:"user_ids,optional"`
	SendAll bool     `json:"send_all,optional"`
}

type AdminWalletLogsReq struct {
	Id       uint64 `path:"id"`
	Page     int    `form:"page,default=1"`
	PageSize int    `form:"page_size,default=10"`
}

type AnyResp struct {
	Data interface{} `json:"data,optional"`
}

// DataResp is the preferred name for opaque entity JSON bodies.
type DataResp = AnyResp

type AuthMeResp struct {
	Roles    []string        `json:"roles"`
	Perms    []string        `json:"perms"`
	MenuTree []*MenuTreeNode `json:"menu_tree"`
}

type CodePathReq struct {
	Code string `path:"code"`
}

type ConfigBatchReq struct {
	Items []ConfigItemReq `json:"items"`
}

type ConfigItemReq struct {
	ConfigKey   string `json:"config_key"`
	ConfigValue string `json:"config_value"`
	Remark      string `json:"remark,optional"`
}

type CountResp struct {
	Count int64 `json:"count"`
}

type EmptyResp struct {
}

type ExchangeReq struct {
	ProductID uint64 `json:"product_id"`
	AddressID uint64 `json:"address_id,optional"`
	Remark    string `json:"remark,optional"`
}

type FilePathReq struct {
	File string `path:"file"`
}

type IdPathReq struct {
	Id uint64 `path:"id"`
}

type InternalAddressReq struct {
	Id     uint64 `form:"id"`
	UserID uint64 `form:"user_id"`
}

type ListAdminsReq struct {
	Page     int `form:"page,default=1"`
	PageSize int `form:"page_size,default=10"`
}

type ListPointsOrdersReq struct {
	Page     int    `form:"page,default=1"`
	PageSize int    `form:"page_size,default=10"`
	Status   string `form:"status,optional"`
	OrderNo  string `form:"order_no,optional"`
	Keyword  string `form:"keyword,optional"`
	UserID   uint64 `form:"user_id,optional"`
}

type ListPointsProductsReq struct {
	Page     int    `form:"page,default=1"`
	PageSize int    `form:"page_size,default=10"`
	Status   string `form:"status,optional"`
	Keyword  string `form:"keyword,optional"`
}

type ListUsersReq struct {
	Mobile   string `form:"mobile,optional"`
	Page     int    `form:"page,default=1"`
	PageSize int    `form:"page_size,default=10"`
}

type LoginReq struct {
	Mobile   string `json:"mobile"`
	Password string `json:"password"`
	ShopID   uint64 `json:"shop_id,optional"`
}

type LoginResp struct {
	Token string      `json:"token"`
	User  interface{} `json:"user"`
}

type MenuReq struct {
	ParentID  uint64 `json:"parent_id,optional"`
	Name      string `json:"name"`
	Type      string `json:"type"`
	Path      string `json:"path,optional"`
	Component string `json:"component,optional"`
	Icon      string `json:"icon,optional"`
	Perms     string `json:"perms,optional"`
	Sort      int    `json:"sort,optional"`
	Visible   int    `json:"visible,optional"`
	Status    int    `json:"status,optional"`
}

type MenuTreeNode struct {
	ID        uint64          `json:"id"`
	ParentID  uint64          `json:"parent_id"`
	Name      string          `json:"name"`
	Type      string          `json:"type"`
	Path      string          `json:"path"`
	Component string          `json:"component"`
	Icon      string          `json:"icon"`
	Perms     string          `json:"perms"`
	Sort      int             `json:"sort"`
	Visible   int             `json:"visible"`
	Status    int             `json:"status"`
	Children  []*MenuTreeNode `json:"children,optional"`
}

type MenuUpdateReq struct {
	Id        uint64 `path:"id"`
	ParentID  uint64 `json:"parent_id,optional"`
	Name      string `json:"name,optional"`
	Type      string `json:"type,optional"`
	Path      string `json:"path,optional"`
	Component string `json:"component,optional"`
	Icon      string `json:"icon,optional"`
	Perms     string `json:"perms,optional"`
	Sort      int    `json:"sort,optional"`
	Visible   int    `json:"visible,optional"`
	Status    int    `json:"status,optional"`
}

type NotificationRecipientsReq struct {
	Id       uint64 `path:"id"`
	Page     int    `form:"page,default=1"`
	PageSize int    `form:"page_size,default=10"`
}

type NotifyCreateReq struct {
	UserID  uint64 `json:"user_id"`
	Title   string `json:"title"`
	Content string `json:"content"`
	Type    string `json:"type,optional"`
}

type PageListResp struct {
	Total int64       `json:"total"`
	List  interface{} `json:"list"`
}

type PageReq struct {
	Page     int `form:"page,default=1"`
	PageSize int `form:"page_size,default=10"`
}

type PointsLedgerReq struct {
	UserID uint64 `json:"user_id"`
	Points int64  `json:"points"`
	Reason string `json:"reason,optional"`
	RefNo  string `json:"ref_no,optional"`
}

type PointsProductSaveReq struct {
	Name         string `json:"name"`
	CoverURL     string `json:"cover_url,optional"`
	Description  string `json:"description,optional"`
	PointsPrice  int    `json:"points_price,optional"`
	Stock        int    `json:"stock,optional"`
	PerUserLimit int    `json:"per_user_limit,optional"`
	Status       string `json:"status,optional"`
	Sort         int    `json:"sort,optional"`
}

type PointsProductStatusReq struct {
	Id     uint64 `path:"id"`
	Status string `json:"status"`
}

type PointsProductUpdateReq struct {
	Id           uint64 `path:"id"`
	Name         string `json:"name,optional"`
	CoverURL     string `json:"cover_url,optional"`
	Description  string `json:"description,optional"`
	PointsPrice  int    `json:"points_price,optional"`
	Stock        int    `json:"stock,optional"`
	PerUserLimit int    `json:"per_user_limit,optional"`
	Status       string `json:"status,optional"`
	Sort         int    `json:"sort,optional"`
}

type PointsResp struct {
	Points int64 `json:"points"`
}

type RegionListReq struct {
	ParentCode string `form:"parent_code,optional"`
}

type RegisterReq struct {
	Mobile   string `json:"mobile"`
	Password string `json:"password"`
}

type RemarkReq struct {
	Id     uint64 `path:"id"`
	Remark string `json:"remark"`
}

type RoleMenusReq struct {
	Id      uint64   `path:"id"`
	MenuIDs []uint64 `json:"menu_ids"`
}

type RoleReq struct {
	Code   string `json:"code"`
	Name   string `json:"name"`
	Status int    `json:"status,optional"`
	Remark string `json:"remark,optional"`
}

type RoleUpdateReq struct {
	Id     uint64 `path:"id"`
	Code   string `json:"code,optional"`
	Name   string `json:"name,optional"`
	Status int    `json:"status,optional"`
	Remark string `json:"remark,optional"`
}

type ShipReq struct {
	Id             uint64 `path:"id"`
	ExpressCompany string `json:"express_company"`
	ExpressNo      string `json:"express_no"`
}

type TaskEventReq struct {
	Event string `json:"event"`
	RefId string `json:"ref_id,optional"`
}

type TokenResp struct {
	Token string `json:"token"`
}

type IdListResp struct {
	Ids []uint64 `json:"ids"`
}

type TreeResp struct {
	Tree interface{} `json:"tree"`
}

type NotificationRecipientsResp struct {
	Batch interface{} `json:"batch"`
	List  interface{} `json:"list"`
	Total int64       `json:"total"`
}

type UserTokenResp struct {
	Token       string `json:"token"`
	UserId      uint64 `json:"user_id"`
	Mobile      string `json:"mobile"`
	Nickname    string `json:"nickname"`
	Role        string `json:"role,optional"`
	ShopId      uint64 `json:"shop_id,optional"`
	ExpireHours int    `json:"expire_hours,optional"`
}


type URLResp struct {
	Url string `json:"url"`
}

type UpdateTaskReq struct {
	Id          uint64 `path:"id"`
	Name        string `json:"name,optional"`
	Points      int64  `json:"points,optional"`
	Status      string `json:"status,optional"`
	Description string `json:"description,optional"`
}

type UserResetPwdReq struct {
	Id       uint64 `path:"id"`
	Password string `json:"password"`
}

type UserStatusReq struct {
	Id     uint64 `path:"id"`
	Status int    `json:"status"`
}

type UserUpdateReq struct {
	Id       uint64 `path:"id"`
	Nickname string `json:"nickname,optional"`
	Avatar   string `json:"avatar,optional"`
	Gender   int    `json:"gender,optional"`
	Mobile   string `json:"mobile,optional"`
}

type WalletAdjustReq struct {
	Id     uint64  `path:"id"`
	Field  string  `json:"field"`
	Amount float64 `json:"amount"`
	Remark string  `json:"remark,optional"`
}

type WalletOrderOpReq struct {
	UserID  uint64  `json:"user_id"`
	Amount  float64 `json:"amount"`
	OrderID uint64  `json:"order_id"`
	OrderNo string  `json:"order_no"`
}
