// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.8.5

package modelgen

import (
	"mymall/common"
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	pointsProductsFieldNames          = builder.RawFieldNames(&PointsProduct{})
	pointsProductsRows                = strings.Join(pointsProductsFieldNames, ",")
	pointsProductsRowsExpectAutoSet   = strings.Join(stringx.Remove(pointsProductsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	pointsProductsRowsWithPlaceHolder = strings.Join(stringx.Remove(pointsProductsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	pointsProductsModel interface {
		Insert(ctx context.Context, data *PointsProduct) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*PointsProduct, error)
		Update(ctx context.Context, data *PointsProduct) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultPointsProductsModel struct {
		conn  sqlx.SqlConn
		table string
	}

	PointsProduct struct {
		ID           uint64    `db:"id" json:"id"`
		Name         string    `db:"name" json:"name"`           // 商品名称
		CoverURL     string    `db:"cover_url" json:"cover_url"`      // 封面图
		Description  string    `db:"description" json:"description"`    // 说明
		PointsPrice  int     `db:"points_price" json:"points_price"`   // 兑换所需积分
		Stock        int     `db:"stock" json:"stock"`          // 库存
		PerUserLimit int     `db:"per_user_limit" json:"per_user_limit"` // 每人限兑次数,0=不限
		Status       string    `db:"status" json:"status"`         // on|off
		Sort         int     `db:"sort" json:"sort"`           // 排序,越大越靠前
		CreatedAt    common.LocalTime `db:"created_at" json:"created_at"`
		UpdatedAt    common.LocalTime `db:"updated_at" json:"updated_at"`
	}
)

func newPointsProductsModel(conn sqlx.SqlConn) *defaultPointsProductsModel {
	return &defaultPointsProductsModel{
		conn:  conn,
		table: "`points_products`",
	}
}

func (m *defaultPointsProductsModel) Delete(ctx context.Context, id uint64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultPointsProductsModel) FindOne(ctx context.Context, id uint64) (*PointsProduct, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", pointsProductsRows, m.table)
	var resp PointsProduct
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultPointsProductsModel) Insert(ctx context.Context, data *PointsProduct) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?)", m.table, pointsProductsRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Name, data.CoverURL, data.Description, data.PointsPrice, data.Stock, data.PerUserLimit, data.Status, data.Sort)
	return ret, err
}

func (m *defaultPointsProductsModel) Update(ctx context.Context, data *PointsProduct) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, pointsProductsRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.Name, data.CoverURL, data.Description, data.PointsPrice, data.Stock, data.PerUserLimit, data.Status, data.Sort, data.ID)
	return err
}

func (m *defaultPointsProductsModel) tableName() string {
	return m.table
}
