// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.8.5

package modelgen

import (
	"mymall/common"
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	pointsExchangeOrdersFieldNames          = builder.RawFieldNames(&PointsExchangeOrder{})
	pointsExchangeOrdersRows                = strings.Join(pointsExchangeOrdersFieldNames, ",")
	pointsExchangeOrdersRowsExpectAutoSet   = strings.Join(stringx.Remove(pointsExchangeOrdersFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	pointsExchangeOrdersRowsWithPlaceHolder = strings.Join(stringx.Remove(pointsExchangeOrdersFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	pointsExchangeOrdersModel interface {
		Insert(ctx context.Context, data *PointsExchangeOrder) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*PointsExchangeOrder, error)
		FindOneByOrderNo(ctx context.Context, orderNo string) (*PointsExchangeOrder, error)
		Update(ctx context.Context, data *PointsExchangeOrder) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultPointsExchangeOrdersModel struct {
		conn  sqlx.SqlConn
		table string
	}

	PointsExchangeOrder struct {
		ID              uint64       `db:"id" json:"id"`
		OrderNo         string       `db:"order_no" json:"order_no"` // 兑换单号
		UserID          uint64       `db:"user_id" json:"user_id"`
		ProductID       uint64       `db:"product_id" json:"product_id"`
		ProductName     string       `db:"product_name" json:"product_name"`
		ProductCover    string       `db:"product_cover" json:"product_cover"`
		Quantity        int        `db:"quantity" json:"quantity"`
		PointsCost      int        `db:"points_cost" json:"points_cost"` // 消耗积分
		Status          string       `db:"status" json:"status"`      // pending|shipped|completed|cancelled
		ReceiverName    string       `db:"receiver_name" json:"receiver_name"`
		ReceiverPhone   string       `db:"receiver_phone" json:"receiver_phone"`
		ReceiverAddress string       `db:"receiver_address" json:"receiver_address"`
		ShipCompany     string       `db:"ship_company" json:"ship_company"`
		ShipNo          string       `db:"ship_no" json:"ship_no"`
		AdminRemark     string       `db:"admin_remark" json:"admin_remark"`
		ShippedAt       common.LocalTime `db:"shipped_at" json:"shipped_at"`
		CompletedAt     common.LocalTime `db:"completed_at" json:"completed_at"`
		CancelledAt     common.LocalTime `db:"cancelled_at" json:"cancelled_at"`
		CreatedAt       common.LocalTime    `db:"created_at" json:"created_at"`
		UpdatedAt       common.LocalTime    `db:"updated_at" json:"updated_at"`
	}
)

func newPointsExchangeOrdersModel(conn sqlx.SqlConn) *defaultPointsExchangeOrdersModel {
	return &defaultPointsExchangeOrdersModel{
		conn:  conn,
		table: "`points_exchange_orders`",
	}
}

func (m *defaultPointsExchangeOrdersModel) Delete(ctx context.Context, id uint64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultPointsExchangeOrdersModel) FindOne(ctx context.Context, id uint64) (*PointsExchangeOrder, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", pointsExchangeOrdersRows, m.table)
	var resp PointsExchangeOrder
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultPointsExchangeOrdersModel) FindOneByOrderNo(ctx context.Context, orderNo string) (*PointsExchangeOrder, error) {
	var resp PointsExchangeOrder
	query := fmt.Sprintf("select %s from %s where `order_no` = ? limit 1", pointsExchangeOrdersRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, orderNo)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultPointsExchangeOrdersModel) Insert(ctx context.Context, data *PointsExchangeOrder) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, pointsExchangeOrdersRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.OrderNo, data.UserID, data.ProductID, data.ProductName, data.ProductCover, data.Quantity, data.PointsCost, data.Status, data.ReceiverName, data.ReceiverPhone, data.ReceiverAddress, data.ShipCompany, data.ShipNo, data.AdminRemark, data.ShippedAt, data.CompletedAt, data.CancelledAt)
	return ret, err
}

func (m *defaultPointsExchangeOrdersModel) Update(ctx context.Context, newData *PointsExchangeOrder) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, pointsExchangeOrdersRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.OrderNo, newData.UserID, newData.ProductID, newData.ProductName, newData.ProductCover, newData.Quantity, newData.PointsCost, newData.Status, newData.ReceiverName, newData.ReceiverPhone, newData.ReceiverAddress, newData.ShipCompany, newData.ShipNo, newData.AdminRemark, newData.ShippedAt, newData.CompletedAt, newData.CancelledAt, newData.ID)
	return err
}

func (m *defaultPointsExchangeOrdersModel) tableName() string {
	return m.table
}
