// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.8.5

package modelgen

import (
	"mymall/common"
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	regionsFieldNames          = builder.RawFieldNames(&Region{})
	regionsRows                = strings.Join(regionsFieldNames, ",")
	regionsRowsExpectAutoSet   = strings.Join(stringx.Remove(regionsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	regionsRowsWithPlaceHolder = strings.Join(stringx.Remove(regionsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	regionsModel interface {
		Insert(ctx context.Context, data *Region) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*Region, error)
		FindOneByCode(ctx context.Context, code string) (*Region, error)
		Update(ctx context.Context, data *Region) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultRegionsModel struct {
		conn  sqlx.SqlConn
		table string
	}

	Region struct {
		ID         uint64    `db:"id" json:"id"`
		Code       string    `db:"code" json:"code"`        // 行政区划代码
		Name       string    `db:"name" json:"name"`        // 名称
		ParentCode string    `db:"parent_code" json:"parent_code"` // 父级代码，省级为空
		Level      int     `db:"level" json:"level"`       // 1省 2市 3区县
		Sort       int     `db:"sort" json:"sort"`
		CreatedAt  common.LocalTime `db:"created_at" json:"created_at"`
	}
)

func newRegionsModel(conn sqlx.SqlConn) *defaultRegionsModel {
	return &defaultRegionsModel{
		conn:  conn,
		table: "`regions`",
	}
}

func (m *defaultRegionsModel) Delete(ctx context.Context, id uint64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultRegionsModel) FindOne(ctx context.Context, id uint64) (*Region, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", regionsRows, m.table)
	var resp Region
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultRegionsModel) FindOneByCode(ctx context.Context, code string) (*Region, error) {
	var resp Region
	query := fmt.Sprintf("select %s from %s where `code` = ? limit 1", regionsRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, code)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultRegionsModel) Insert(ctx context.Context, data *Region) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?)", m.table, regionsRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Code, data.Name, data.ParentCode, data.Level, data.Sort)
	return ret, err
}

func (m *defaultRegionsModel) Update(ctx context.Context, newData *Region) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, regionsRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.Code, newData.Name, newData.ParentCode, newData.Level, newData.Sort, newData.ID)
	return err
}

func (m *defaultRegionsModel) tableName() string {
	return m.table
}
