// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.8.5

package modelgen

import (
	"mymall/common"
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	sysConfigFieldNames          = builder.RawFieldNames(&SysConfig{})
	sysConfigRows                = strings.Join(sysConfigFieldNames, ",")
	sysConfigRowsExpectAutoSet   = strings.Join(stringx.Remove(sysConfigFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	sysConfigRowsWithPlaceHolder = strings.Join(stringx.Remove(sysConfigFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	sysConfigModel interface {
		Insert(ctx context.Context, data *SysConfig) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*SysConfig, error)
		FindOneByConfigKey(ctx context.Context, configKey string) (*SysConfig, error)
		Update(ctx context.Context, data *SysConfig) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultSysConfigModel struct {
		conn  sqlx.SqlConn
		table string
	}

	SysConfig struct {
		ID          uint64    `db:"id"`
		ConfigKey   string    `db:"config_key"`
		ConfigValue string    `db:"config_value"`
		Remark      string    `db:"remark"`
		CreatedAt   common.LocalTime `db:"created_at"`
		UpdatedAt   common.LocalTime `db:"updated_at"`
	}
)

func newSysConfigModel(conn sqlx.SqlConn) *defaultSysConfigModel {
	return &defaultSysConfigModel{
		conn:  conn,
		table: "`sys_config`",
	}
}

func (m *defaultSysConfigModel) Delete(ctx context.Context, id uint64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultSysConfigModel) FindOne(ctx context.Context, id uint64) (*SysConfig, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", sysConfigRows, m.table)
	var resp SysConfig
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultSysConfigModel) FindOneByConfigKey(ctx context.Context, configKey string) (*SysConfig, error) {
	var resp SysConfig
	query := fmt.Sprintf("select %s from %s where `config_key` = ? limit 1", sysConfigRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, configKey)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultSysConfigModel) Insert(ctx context.Context, data *SysConfig) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?)", m.table, sysConfigRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.ConfigKey, data.ConfigValue, data.Remark)
	return ret, err
}

func (m *defaultSysConfigModel) Update(ctx context.Context, newData *SysConfig) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, sysConfigRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.ConfigKey, newData.ConfigValue, newData.Remark, newData.ID)
	return err
}

func (m *defaultSysConfigModel) tableName() string {
	return m.table
}
