// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.8.5

package modelgen

import (
	"mymall/common"
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	taskDefinitionsFieldNames          = builder.RawFieldNames(&TaskDefinition{})
	taskDefinitionsRows                = strings.Join(taskDefinitionsFieldNames, ",")
	taskDefinitionsRowsExpectAutoSet   = strings.Join(stringx.Remove(taskDefinitionsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	taskDefinitionsRowsWithPlaceHolder = strings.Join(stringx.Remove(taskDefinitionsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	taskDefinitionsModel interface {
		Insert(ctx context.Context, data *TaskDefinition) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*TaskDefinition, error)
		FindOneByCode(ctx context.Context, code string) (*TaskDefinition, error)
		Update(ctx context.Context, data *TaskDefinition) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultTaskDefinitionsModel struct {
		conn  sqlx.SqlConn
		table string
	}

	TaskDefinition struct {
		ID           uint64    `db:"id"`
		Code         string    `db:"code"` // 任务编码
		Title        string    `db:"title"`
		Description  string    `db:"description"`
		Icon         string    `db:"icon"`
		Period       string    `db:"period"` // daily|once
		Enabled      int     `db:"enabled"`
		RewardPoints int     `db:"reward_points"` // 0=不奖励积分
		TargetCount  int     `db:"target_count"`  // 完成所需进度
		DailyLimit   int     `db:"daily_limit"`   // 每日最多领取次数,0=不限; once任务忽略
		Sort         int     `db:"sort"`
		RulesJSON    string    `db:"rules_json"`
		CreatedAt    common.LocalTime `db:"created_at"`
		UpdatedAt    common.LocalTime `db:"updated_at"`
	}
)

func newTaskDefinitionsModel(conn sqlx.SqlConn) *defaultTaskDefinitionsModel {
	return &defaultTaskDefinitionsModel{
		conn:  conn,
		table: "`task_definitions`",
	}
}

func (m *defaultTaskDefinitionsModel) Delete(ctx context.Context, id uint64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultTaskDefinitionsModel) FindOne(ctx context.Context, id uint64) (*TaskDefinition, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", taskDefinitionsRows, m.table)
	var resp TaskDefinition
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultTaskDefinitionsModel) FindOneByCode(ctx context.Context, code string) (*TaskDefinition, error) {
	var resp TaskDefinition
	query := fmt.Sprintf("select %s from %s where `code` = ? limit 1", taskDefinitionsRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, code)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultTaskDefinitionsModel) Insert(ctx context.Context, data *TaskDefinition) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, taskDefinitionsRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Code, data.Title, data.Description, data.Icon, data.Period, data.Enabled, data.RewardPoints, data.TargetCount, data.DailyLimit, data.Sort, data.RulesJSON)
	return ret, err
}

func (m *defaultTaskDefinitionsModel) Update(ctx context.Context, newData *TaskDefinition) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, taskDefinitionsRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.Code, newData.Title, newData.Description, newData.Icon, newData.Period, newData.Enabled, newData.RewardPoints, newData.TargetCount, newData.DailyLimit, newData.Sort, newData.RulesJSON, newData.ID)
	return err
}

func (m *defaultTaskDefinitionsModel) tableName() string {
	return m.table
}
