// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.8.5

package modelgen

import (
	"mymall/common"
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	userNotificationBatchesFieldNames          = builder.RawFieldNames(&UserNotificationBatch{})
	userNotificationBatchesRows                = strings.Join(userNotificationBatchesFieldNames, ",")
	userNotificationBatchesRowsExpectAutoSet   = strings.Join(stringx.Remove(userNotificationBatchesFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	userNotificationBatchesRowsWithPlaceHolder = strings.Join(stringx.Remove(userNotificationBatchesFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	userNotificationBatchesModel interface {
		Insert(ctx context.Context, data *UserNotificationBatch) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*UserNotificationBatch, error)
		Update(ctx context.Context, data *UserNotificationBatch) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultUserNotificationBatchesModel struct {
		conn  sqlx.SqlConn
		table string
	}

	UserNotificationBatch struct {
		ID           uint64    `db:"id"`
		Title        string    `db:"title"`
		Content      string    `db:"content"`
		Target       string    `db:"target"`
		UserCount    int     `db:"user_count"`
		SuccessCount int     `db:"success_count"`
		LinkType     string    `db:"link_type"`
		LinkID       uint64    `db:"link_id"`
		SenderID     uint64    `db:"sender_id"`
		CreatedAt    common.LocalTime `db:"created_at"`
	}
)

func newUserNotificationBatchesModel(conn sqlx.SqlConn) *defaultUserNotificationBatchesModel {
	return &defaultUserNotificationBatchesModel{
		conn:  conn,
		table: "`user_notification_batches`",
	}
}

func (m *defaultUserNotificationBatchesModel) Delete(ctx context.Context, id uint64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultUserNotificationBatchesModel) FindOne(ctx context.Context, id uint64) (*UserNotificationBatch, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", userNotificationBatchesRows, m.table)
	var resp UserNotificationBatch
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUserNotificationBatchesModel) Insert(ctx context.Context, data *UserNotificationBatch) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?)", m.table, userNotificationBatchesRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Title, data.Content, data.Target, data.UserCount, data.SuccessCount, data.LinkType, data.LinkID, data.SenderID)
	return ret, err
}

func (m *defaultUserNotificationBatchesModel) Update(ctx context.Context, data *UserNotificationBatch) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, userNotificationBatchesRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.Title, data.Content, data.Target, data.UserCount, data.SuccessCount, data.LinkType, data.LinkID, data.SenderID, data.ID)
	return err
}

func (m *defaultUserNotificationBatchesModel) tableName() string {
	return m.table
}
