// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.8.5

package modelgen

import (
	"mymall/common"
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	userPointsFieldNames          = builder.RawFieldNames(&UserPoints{})
	userPointsRows                = strings.Join(userPointsFieldNames, ",")
	userPointsRowsExpectAutoSet   = strings.Join(stringx.Remove(userPointsFieldNames, "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	userPointsRowsWithPlaceHolder = strings.Join(stringx.Remove(userPointsFieldNames, "`user_id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	userPointsModel interface {
		Insert(ctx context.Context, data *UserPoints) (sql.Result, error)
		FindOne(ctx context.Context, userId uint64) (*UserPoints, error)
		Update(ctx context.Context, data *UserPoints) error
		Delete(ctx context.Context, userId uint64) error
	}

	defaultUserPointsModel struct {
		conn  sqlx.SqlConn
		table string
	}

	UserPoints struct {
		UserID    uint64    `db:"user_id"` // 用户ID
		Points    int     `db:"points"`  // 当前积分
		CreatedAt common.LocalTime `db:"created_at"`
		UpdatedAt common.LocalTime `db:"updated_at"`
	}
)

func newUserPointsModel(conn sqlx.SqlConn) *defaultUserPointsModel {
	return &defaultUserPointsModel{
		conn:  conn,
		table: "`user_points`",
	}
}

func (m *defaultUserPointsModel) Delete(ctx context.Context, userId uint64) error {
	query := fmt.Sprintf("delete from %s where `user_id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, userId)
	return err
}

func (m *defaultUserPointsModel) FindOne(ctx context.Context, userId uint64) (*UserPoints, error) {
	query := fmt.Sprintf("select %s from %s where `user_id` = ? limit 1", userPointsRows, m.table)
	var resp UserPoints
	err := m.conn.QueryRowCtx(ctx, &resp, query, userId)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUserPointsModel) Insert(ctx context.Context, data *UserPoints) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?)", m.table, userPointsRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.UserID, data.Points)
	return ret, err
}

func (m *defaultUserPointsModel) Update(ctx context.Context, data *UserPoints) error {
	query := fmt.Sprintf("update %s set %s where `user_id` = ?", m.table, userPointsRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.Points, data.UserID)
	return err
}

func (m *defaultUserPointsModel) tableName() string {
	return m.table
}
