// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.8.5

package modelgen

import (
	"mymall/common"
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	userPointLogsFieldNames          = builder.RawFieldNames(&UserPointLog{})
	userPointLogsRows                = strings.Join(userPointLogsFieldNames, ",")
	userPointLogsRowsExpectAutoSet   = strings.Join(stringx.Remove(userPointLogsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	userPointLogsRowsWithPlaceHolder = strings.Join(stringx.Remove(userPointLogsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	userPointLogsModel interface {
		Insert(ctx context.Context, data *UserPointLog) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*UserPointLog, error)
		Update(ctx context.Context, data *UserPointLog) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultUserPointLogsModel struct {
		conn  sqlx.SqlConn
		table string
	}

	UserPointLog struct {
		ID          uint64    `db:"id" json:"id"`
		UserID      uint64    `db:"user_id" json:"user_id"`
		ChangeType  string    `db:"change_type" json:"change_type"` // task_claim/admin_adjust
		Delta       int     `db:"delta" json:"delta"`       // 变动积分(可负)
		PointsAfter int     `db:"points_after" json:"points_after"`
		Remark      string    `db:"remark" json:"remark"`
		RefType     string    `db:"ref_type" json:"ref_type"`
		RefID       uint64    `db:"ref_id" json:"ref_id"`
		CreatedAt   common.LocalTime `db:"created_at" json:"created_at"`
	}
)

func newUserPointLogsModel(conn sqlx.SqlConn) *defaultUserPointLogsModel {
	return &defaultUserPointLogsModel{
		conn:  conn,
		table: "`user_point_logs`",
	}
}

func (m *defaultUserPointLogsModel) Delete(ctx context.Context, id uint64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultUserPointLogsModel) FindOne(ctx context.Context, id uint64) (*UserPointLog, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", userPointLogsRows, m.table)
	var resp UserPointLog
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUserPointLogsModel) Insert(ctx context.Context, data *UserPointLog) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?)", m.table, userPointLogsRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.UserID, data.ChangeType, data.Delta, data.PointsAfter, data.Remark, data.RefType, data.RefID)
	return ret, err
}

func (m *defaultUserPointLogsModel) Update(ctx context.Context, data *UserPointLog) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, userPointLogsRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.UserID, data.ChangeType, data.Delta, data.PointsAfter, data.Remark, data.RefType, data.RefID, data.ID)
	return err
}

func (m *defaultUserPointLogsModel) tableName() string {
	return m.table
}
