// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.8.5

package modelgen

import (
	"mymall/common"
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	userTaskDedupeFieldNames          = builder.RawFieldNames(&UserTaskDedupe{})
	userTaskDedupeRows                = strings.Join(userTaskDedupeFieldNames, ",")
	userTaskDedupeRowsExpectAutoSet   = strings.Join(stringx.Remove(userTaskDedupeFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	userTaskDedupeRowsWithPlaceHolder = strings.Join(stringx.Remove(userTaskDedupeFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	userTaskDedupeModel interface {
		Insert(ctx context.Context, data *UserTaskDedupe) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*UserTaskDedupe, error)
		FindOneByUserIdTaskCodeBizDateRefKey(ctx context.Context, userId uint64, taskCode string, bizDate common.LocalTime, refKey string) (*UserTaskDedupe, error)
		Update(ctx context.Context, data *UserTaskDedupe) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultUserTaskDedupeModel struct {
		conn  sqlx.SqlConn
		table string
	}

	UserTaskDedupe struct {
		ID        uint64    `db:"id" json:"id"`
		UserID    uint64    `db:"user_id" json:"user_id"`
		TaskCode  string    `db:"task_code" json:"task_code"`
		BizDate   common.LocalTime `db:"biz_date" json:"biz_date"`
		RefKey    string    `db:"ref_key" json:"ref_key"`
		CreatedAt common.LocalTime `db:"created_at" json:"created_at"`
	}
)

func newUserTaskDedupeModel(conn sqlx.SqlConn) *defaultUserTaskDedupeModel {
	return &defaultUserTaskDedupeModel{
		conn:  conn,
		table: "`user_task_dedupe`",
	}
}

func (m *defaultUserTaskDedupeModel) Delete(ctx context.Context, id uint64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultUserTaskDedupeModel) FindOne(ctx context.Context, id uint64) (*UserTaskDedupe, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", userTaskDedupeRows, m.table)
	var resp UserTaskDedupe
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUserTaskDedupeModel) FindOneByUserIdTaskCodeBizDateRefKey(ctx context.Context, userId uint64, taskCode string, bizDate common.LocalTime, refKey string) (*UserTaskDedupe, error) {
	var resp UserTaskDedupe
	query := fmt.Sprintf("select %s from %s where `user_id` = ? and `task_code` = ? and `biz_date` = ? and `ref_key` = ? limit 1", userTaskDedupeRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, userId, taskCode, bizDate, refKey)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUserTaskDedupeModel) Insert(ctx context.Context, data *UserTaskDedupe) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?)", m.table, userTaskDedupeRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.UserID, data.TaskCode, data.BizDate, data.RefKey)
	return ret, err
}

func (m *defaultUserTaskDedupeModel) Update(ctx context.Context, newData *UserTaskDedupe) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, userTaskDedupeRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.UserID, newData.TaskCode, newData.BizDate, newData.RefKey, newData.ID)
	return err
}

func (m *defaultUserTaskDedupeModel) tableName() string {
	return m.table
}
