// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.8.5

package modelgen

import (
	"mymall/common"
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	userWalletsFieldNames          = builder.RawFieldNames(&UserWallet{})
	userWalletsRows                = strings.Join(userWalletsFieldNames, ",")
	userWalletsRowsExpectAutoSet   = strings.Join(stringx.Remove(userWalletsFieldNames, "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	userWalletsRowsWithPlaceHolder = strings.Join(stringx.Remove(userWalletsFieldNames, "`user_id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	userWalletsModel interface {
		Insert(ctx context.Context, data *UserWallet) (sql.Result, error)
		FindOne(ctx context.Context, userId uint64) (*UserWallet, error)
		Update(ctx context.Context, data *UserWallet) error
		Delete(ctx context.Context, userId uint64) error
	}

	defaultUserWalletsModel struct {
		conn  sqlx.SqlConn
		table string
	}

	UserWallet struct {
		UserID        uint64    `db:"user_id" json:"user_id"`        // 用户ID
		Balance       float64   `db:"balance" json:"balance"`        // 可用余额
		FrozenBalance float64   `db:"frozen_balance" json:"frozen_balance"` // 冻结余额
		CreatedAt     common.LocalTime `db:"created_at" json:"created_at"`
		UpdatedAt     common.LocalTime `db:"updated_at" json:"updated_at"`
	}
)

func newUserWalletsModel(conn sqlx.SqlConn) *defaultUserWalletsModel {
	return &defaultUserWalletsModel{
		conn:  conn,
		table: "`user_wallets`",
	}
}

func (m *defaultUserWalletsModel) Delete(ctx context.Context, userId uint64) error {
	query := fmt.Sprintf("delete from %s where `user_id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, userId)
	return err
}

func (m *defaultUserWalletsModel) FindOne(ctx context.Context, userId uint64) (*UserWallet, error) {
	query := fmt.Sprintf("select %s from %s where `user_id` = ? limit 1", userWalletsRows, m.table)
	var resp UserWallet
	err := m.conn.QueryRowCtx(ctx, &resp, query, userId)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUserWalletsModel) Insert(ctx context.Context, data *UserWallet) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?)", m.table, userWalletsRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.UserID, data.Balance, data.FrozenBalance)
	return ret, err
}

func (m *defaultUserWalletsModel) Update(ctx context.Context, data *UserWallet) error {
	query := fmt.Sprintf("update %s set %s where `user_id` = ?", m.table, userWalletsRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.Balance, data.FrozenBalance, data.UserID)
	return err
}

func (m *defaultUserWalletsModel) tableName() string {
	return m.table
}
