// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.8.5

package modelgen

import (
	"mymall/common"
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	usersFieldNames          = builder.RawFieldNames(&User{})
	usersRows                = strings.Join(usersFieldNames, ",")
	usersRowsExpectAutoSet   = strings.Join(stringx.Remove(usersFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	usersRowsWithPlaceHolder = strings.Join(stringx.Remove(usersFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	usersModel interface {
		Insert(ctx context.Context, data *User) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*User, error)
		FindOneByMobile(ctx context.Context, mobile string) (*User, error)
		Update(ctx context.Context, data *User) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultUsersModel struct {
		conn  sqlx.SqlConn
		table string
	}

	User struct {
		ID            uint64       `db:"id" json:"id"`
		Mobile        string       `db:"mobile" json:"mobile"`          // 登录手机号
		Password      string       `db:"password" json:"-"`        // 登录密码
		Nickname      string       `db:"nickname" json:"nickname"`        // 用户昵称
		Avatar        string       `db:"avatar" json:"avatar"`          // 用户头像URL
		Gender        int        `db:"gender" json:"gender"`          // 性别：0-未知 1-男 2-女
		Status        int        `db:"status" json:"status"`          // 账号状态：1-正常 0-禁用
		Role          string       `db:"role" json:"role"`            // 角色
		LastLoginTime common.LocalTime `db:"last_login_time" json:"last_login_time"` // 最后登录时间
		CreatedAt     common.LocalTime    `db:"created_at" json:"created_at"`
		UpdatedAt     common.LocalTime    `db:"updated_at" json:"updated_at"`
		DeletedAt     common.LocalTime `db:"deleted_at" json:"deleted_at"`
	}
)

func newUsersModel(conn sqlx.SqlConn) *defaultUsersModel {
	return &defaultUsersModel{
		conn:  conn,
		table: "`users`",
	}
}

func (m *defaultUsersModel) Delete(ctx context.Context, id uint64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultUsersModel) FindOne(ctx context.Context, id uint64) (*User, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", usersRows, m.table)
	var resp User
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUsersModel) FindOneByMobile(ctx context.Context, mobile string) (*User, error) {
	var resp User
	query := fmt.Sprintf("select %s from %s where `mobile` = ? limit 1", usersRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, mobile)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUsersModel) Insert(ctx context.Context, data *User) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, usersRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Mobile, data.Password, data.Nickname, data.Avatar, data.Gender, data.Status, data.Role, data.LastLoginTime, data.DeletedAt)
	return ret, err
}

func (m *defaultUsersModel) Update(ctx context.Context, newData *User) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, usersRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.Mobile, newData.Password, newData.Nickname, newData.Avatar, newData.Gender, newData.Status, newData.Role, newData.LastLoginTime, newData.DeletedAt, newData.ID)
	return err
}

func (m *defaultUsersModel) tableName() string {
	return m.table
}
