// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.8.5

package modelgen

import (
	"mymall/common"
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	userTaskProgressFieldNames          = builder.RawFieldNames(&UserTaskProgress{})
	userTaskProgressRows                = strings.Join(userTaskProgressFieldNames, ",")
	userTaskProgressRowsExpectAutoSet   = strings.Join(stringx.Remove(userTaskProgressFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	userTaskProgressRowsWithPlaceHolder = strings.Join(stringx.Remove(userTaskProgressFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	userTaskProgressModel interface {
		Insert(ctx context.Context, data *UserTaskProgress) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*UserTaskProgress, error)
		FindOneByUserIdTaskCodeBizDate(ctx context.Context, userId uint64, taskCode string, bizDate common.LocalTime) (*UserTaskProgress, error)
		Update(ctx context.Context, data *UserTaskProgress) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultUserTaskProgressModel struct {
		conn  sqlx.SqlConn
		table string
	}

	UserTaskProgress struct {
		ID         uint64       `db:"id" json:"id"`
		UserID     uint64       `db:"user_id" json:"user_id"`
		TaskCode   string       `db:"task_code" json:"task_code"`
		BizDate    common.LocalTime    `db:"biz_date" json:"biz_date"` // 日任务按自然日; once=1970-01-01
		Progress   int        `db:"progress" json:"progress"`
		ClaimCount int        `db:"claim_count" json:"claim_count"` // 当日已领取次数
		Status     string       `db:"status" json:"status"`      // ongoing|claimable|claimed
		ClaimedAt  common.LocalTime `db:"claimed_at" json:"claimed_at"`
		CreatedAt  common.LocalTime    `db:"created_at" json:"created_at"`
		UpdatedAt  common.LocalTime    `db:"updated_at" json:"updated_at"`
	}
)

func newUserTaskProgressModel(conn sqlx.SqlConn) *defaultUserTaskProgressModel {
	return &defaultUserTaskProgressModel{
		conn:  conn,
		table: "`user_task_progress`",
	}
}

func (m *defaultUserTaskProgressModel) Delete(ctx context.Context, id uint64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultUserTaskProgressModel) FindOne(ctx context.Context, id uint64) (*UserTaskProgress, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", userTaskProgressRows, m.table)
	var resp UserTaskProgress
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUserTaskProgressModel) FindOneByUserIdTaskCodeBizDate(ctx context.Context, userId uint64, taskCode string, bizDate common.LocalTime) (*UserTaskProgress, error) {
	var resp UserTaskProgress
	query := fmt.Sprintf("select %s from %s where `user_id` = ? and `task_code` = ? and `biz_date` = ? limit 1", userTaskProgressRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, userId, taskCode, bizDate)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUserTaskProgressModel) Insert(ctx context.Context, data *UserTaskProgress) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?)", m.table, userTaskProgressRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.UserID, data.TaskCode, data.BizDate, data.Progress, data.ClaimCount, data.Status, data.ClaimedAt)
	return ret, err
}

func (m *defaultUserTaskProgressModel) Update(ctx context.Context, newData *UserTaskProgress) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, userTaskProgressRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.UserID, newData.TaskCode, newData.BizDate, newData.Progress, newData.ClaimCount, newData.Status, newData.ClaimedAt, newData.ID)
	return err
}

func (m *defaultUserTaskProgressModel) tableName() string {
	return m.table
}
