// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.8.5

package modelgen

import (
	"mymall/common"
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	userWalletLogsFieldNames          = builder.RawFieldNames(&UserWalletLog{})
	userWalletLogsRows                = strings.Join(userWalletLogsFieldNames, ",")
	userWalletLogsRowsExpectAutoSet   = strings.Join(stringx.Remove(userWalletLogsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	userWalletLogsRowsWithPlaceHolder = strings.Join(stringx.Remove(userWalletLogsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	userWalletLogsModel interface {
		Insert(ctx context.Context, data *UserWalletLog) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*UserWalletLog, error)
		Update(ctx context.Context, data *UserWalletLog) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultUserWalletLogsModel struct {
		conn  sqlx.SqlConn
		table string
	}

	UserWalletLog struct {
		ID             uint64        `db:"id" json:"id"`
		UserID         uint64        `db:"user_id" json:"user_id"`
		ChangeType     string        `db:"change_type" json:"change_type"` // admin_adjust/order_freeze/order_unfreeze/order_settle
		Amount         float64       `db:"amount" json:"amount"`      // 变动金额
		BalanceAfter   float64       `db:"balance_after" json:"balance_after"`
		FrozenAfter    float64       `db:"frozen_after" json:"frozen_after"`
		Remark         string        `db:"remark" json:"remark"`
		OperatorUserID uint64 `db:"operator_user_id" json:"operator_user_id"`
		RefType        string        `db:"ref_type" json:"ref_type"`
		RefID          uint64        `db:"ref_id" json:"ref_id"`
		CreatedAt      common.LocalTime     `db:"created_at" json:"created_at"`
	}
)

func newUserWalletLogsModel(conn sqlx.SqlConn) *defaultUserWalletLogsModel {
	return &defaultUserWalletLogsModel{
		conn:  conn,
		table: "`user_wallet_logs`",
	}
}

func (m *defaultUserWalletLogsModel) Delete(ctx context.Context, id uint64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultUserWalletLogsModel) FindOne(ctx context.Context, id uint64) (*UserWalletLog, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", userWalletLogsRows, m.table)
	var resp UserWalletLog
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUserWalletLogsModel) Insert(ctx context.Context, data *UserWalletLog) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, userWalletLogsRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.UserID, data.ChangeType, data.Amount, data.BalanceAfter, data.FrozenAfter, data.Remark, data.OperatorUserID, data.RefType, data.RefID)
	return ret, err
}

func (m *defaultUserWalletLogsModel) Update(ctx context.Context, data *UserWalletLog) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, userWalletLogsRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.UserID, data.ChangeType, data.Amount, data.BalanceAfter, data.FrozenAfter, data.Remark, data.OperatorUserID, data.RefType, data.RefID, data.ID)
	return err
}

func (m *defaultUserWalletLogsModel) tableName() string {
	return m.table
}
