// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.8.5

package modelgen

import (
	"mymall/common"
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	userNotificationsFieldNames          = builder.RawFieldNames(&UserNotification{})
	userNotificationsRows                = strings.Join(userNotificationsFieldNames, ",")
	userNotificationsRowsExpectAutoSet   = strings.Join(stringx.Remove(userNotificationsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	userNotificationsRowsWithPlaceHolder = strings.Join(stringx.Remove(userNotificationsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	userNotificationsModel interface {
		Insert(ctx context.Context, data *UserNotification) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*UserNotification, error)
		Update(ctx context.Context, data *UserNotification) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultUserNotificationsModel struct {
		conn  sqlx.SqlConn
		table string
	}

	UserNotification struct {
		ID         uint64         `db:"id"`
		UserID     uint64         `db:"user_id"`
		Title      string         `db:"title"`
		Content    string         `db:"content"`
		MsgType    string         `db:"msg_type"`
		LinkType   string         `db:"link_type"`
		LinkID     uint64         `db:"link_id"`
		Extra      string `db:"extra"`
		IsRead     int          `db:"is_read"`
		SenderType string         `db:"sender_type"`
		SenderID   uint64         `db:"sender_id"`
		BatchID    uint64         `db:"batch_id"`
		CreatedAt  common.LocalTime      `db:"created_at"`
	}
)

func newUserNotificationsModel(conn sqlx.SqlConn) *defaultUserNotificationsModel {
	return &defaultUserNotificationsModel{
		conn:  conn,
		table: "`user_notifications`",
	}
}

func (m *defaultUserNotificationsModel) Delete(ctx context.Context, id uint64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultUserNotificationsModel) FindOne(ctx context.Context, id uint64) (*UserNotification, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", userNotificationsRows, m.table)
	var resp UserNotification
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUserNotificationsModel) Insert(ctx context.Context, data *UserNotification) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, userNotificationsRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.UserID, data.Title, data.Content, data.MsgType, data.LinkType, data.LinkID, data.Extra, data.IsRead, data.SenderType, data.SenderID, data.BatchID)
	return ret, err
}

func (m *defaultUserNotificationsModel) Update(ctx context.Context, data *UserNotification) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, userNotificationsRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.UserID, data.Title, data.Content, data.MsgType, data.LinkType, data.LinkID, data.Extra, data.IsRead, data.SenderType, data.SenderID, data.BatchID, data.ID)
	return err
}

func (m *defaultUserNotificationsModel) tableName() string {
	return m.table
}
