// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.8.5

package modelgen

import (
	"mymall/common"
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	userAddressesFieldNames          = builder.RawFieldNames(&UserAddress{})
	userAddressesRows                = strings.Join(userAddressesFieldNames, ",")
	userAddressesRowsExpectAutoSet   = strings.Join(stringx.Remove(userAddressesFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	userAddressesRowsWithPlaceHolder = strings.Join(stringx.Remove(userAddressesFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	userAddressesModel interface {
		Insert(ctx context.Context, data *UserAddress) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*UserAddress, error)
		Update(ctx context.Context, data *UserAddress) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultUserAddressesModel struct {
		conn  sqlx.SqlConn
		table string
	}

	UserAddress struct {
		ID            uint64           `db:"id"`
		UserID        uint64           `db:"user_id"`
		ReceiverName  string           `db:"receiver_name"`  // 收货人
		ReceiverPhone string           `db:"receiver_phone"` // 手机号
		Province      string           `db:"province"`
		City          string           `db:"city"`
		District      string           `db:"district"`
		Detail        string           `db:"detail"` // 详细地址
		ProvinceCode  string           `db:"province_code"`
		CityCode      string           `db:"city_code"`
		DistrictCode  string           `db:"district_code"`
		IsDefault     int              `db:"is_default"` // 1默认
		CreatedAt     common.LocalTime `db:"created_at"`
		UpdatedAt     common.LocalTime `db:"updated_at"`
	}
)

func newUserAddressesModel(conn sqlx.SqlConn) *defaultUserAddressesModel {
	return &defaultUserAddressesModel{
		conn:  conn,
		table: "`user_addresses`",
	}
}

func (m *defaultUserAddressesModel) Delete(ctx context.Context, id uint64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultUserAddressesModel) FindOne(ctx context.Context, id uint64) (*UserAddress, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", userAddressesRows, m.table)
	var resp UserAddress
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUserAddressesModel) Insert(ctx context.Context, data *UserAddress) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?)", m.table, userAddressesRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.UserID, data.ReceiverName, data.ReceiverPhone, data.Province, data.City, data.District, data.Detail, data.IsDefault)
	return ret, err
}

func (m *defaultUserAddressesModel) Update(ctx context.Context, data *UserAddress) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, userAddressesRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.UserID, data.ReceiverName, data.ReceiverPhone, data.Province, data.City, data.District, data.Detail, data.IsDefault, data.ID)
	return err
}

func (m *defaultUserAddressesModel) tableName() string {
	return m.table
}
