// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5
// Source: catalog.proto

package catalogservice

import (
	"context"

	catalogv1 "mymall/api/gen/catalog/v1"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	BatchGetProductsRequest  = catalogv1.BatchGetProductsRequest
	BatchGetProductsResponse = catalogv1.BatchGetProductsResponse
	Product                  = catalogv1.Product
	ReleaseStockRequest      = catalogv1.ReleaseStockRequest
	ReleaseStockResponse     = catalogv1.ReleaseStockResponse
	ReserveStockRequest      = catalogv1.ReserveStockRequest
	ReserveStockResponse     = catalogv1.ReserveStockResponse
	StockItem                = catalogv1.StockItem

	CatalogService interface {
		BatchGetProducts(ctx context.Context, in *BatchGetProductsRequest, opts ...grpc.CallOption) (*BatchGetProductsResponse, error)
		ReserveStock(ctx context.Context, in *ReserveStockRequest, opts ...grpc.CallOption) (*ReserveStockResponse, error)
		ReleaseStock(ctx context.Context, in *ReleaseStockRequest, opts ...grpc.CallOption) (*ReleaseStockResponse, error)
	}

	defaultCatalogService struct {
		cli zrpc.Client
	}
)

func NewCatalogService(cli zrpc.Client) CatalogService {
	return &defaultCatalogService{
		cli: cli,
	}
}

func (m *defaultCatalogService) BatchGetProducts(ctx context.Context, in *BatchGetProductsRequest, opts ...grpc.CallOption) (*BatchGetProductsResponse, error) {
	client := catalogv1.NewCatalogServiceClient(m.cli.Conn())
	return client.BatchGetProducts(ctx, in, opts...)
}

func (m *defaultCatalogService) ReserveStock(ctx context.Context, in *ReserveStockRequest, opts ...grpc.CallOption) (*ReserveStockResponse, error) {
	client := catalogv1.NewCatalogServiceClient(m.cli.Conn())
	return client.ReserveStock(ctx, in, opts...)
}

func (m *defaultCatalogService) ReleaseStock(ctx context.Context, in *ReleaseStockRequest, opts ...grpc.CallOption) (*ReleaseStockResponse, error) {
	client := catalogv1.NewCatalogServiceClient(m.cli.Conn())
	return client.ReleaseStock(ctx, in, opts...)
}
