// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.8.5

package modelgen

import (
	"mymall/common"
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	logisticsCompaniesFieldNames          = builder.RawFieldNames(&LogisticsCompany{})
	logisticsCompaniesRows                = strings.Join(logisticsCompaniesFieldNames, ",")
	logisticsCompaniesRowsExpectAutoSet   = strings.Join(stringx.Remove(logisticsCompaniesFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	logisticsCompaniesRowsWithPlaceHolder = strings.Join(stringx.Remove(logisticsCompaniesFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	logisticsCompaniesModel interface {
		Insert(ctx context.Context, data *LogisticsCompany) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*LogisticsCompany, error)
		FindOneByCode(ctx context.Context, code string) (*LogisticsCompany, error)
		Update(ctx context.Context, data *LogisticsCompany) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultLogisticsCompaniesModel struct {
		conn  sqlx.SqlConn
		table string
	}

	LogisticsCompany struct {
		ID        uint64    `db:"id"`
		Name      string    `db:"name"`   // 公司名称
		Code      string    `db:"code"`   // 编码
		Sort      int     `db:"sort"`   // 排序，越小越靠前
		Status    int     `db:"status"` // 1启用 0停用
		CreatedAt common.LocalTime `db:"created_at"`
		UpdatedAt common.LocalTime `db:"updated_at"`
	}
)

func newLogisticsCompaniesModel(conn sqlx.SqlConn) *defaultLogisticsCompaniesModel {
	return &defaultLogisticsCompaniesModel{
		conn:  conn,
		table: "`logistics_companies`",
	}
}

func (m *defaultLogisticsCompaniesModel) Delete(ctx context.Context, id uint64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultLogisticsCompaniesModel) FindOne(ctx context.Context, id uint64) (*LogisticsCompany, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", logisticsCompaniesRows, m.table)
	var resp LogisticsCompany
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultLogisticsCompaniesModel) FindOneByCode(ctx context.Context, code string) (*LogisticsCompany, error) {
	var resp LogisticsCompany
	query := fmt.Sprintf("select %s from %s where `code` = ? limit 1", logisticsCompaniesRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, code)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultLogisticsCompaniesModel) Insert(ctx context.Context, data *LogisticsCompany) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?)", m.table, logisticsCompaniesRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Name, data.Code, data.Sort, data.Status)
	return ret, err
}

func (m *defaultLogisticsCompaniesModel) Update(ctx context.Context, newData *LogisticsCompany) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, logisticsCompaniesRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.Name, newData.Code, newData.Sort, newData.Status, newData.ID)
	return err
}

func (m *defaultLogisticsCompaniesModel) tableName() string {
	return m.table
}
