// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.8.5

package modelgen

import (
	"mymall/common"
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	orderAfterSalesFieldNames          = builder.RawFieldNames(&OrderAfterSale{})
	orderAfterSalesRows                = strings.Join(orderAfterSalesFieldNames, ",")
	orderAfterSalesRowsExpectAutoSet   = strings.Join(stringx.Remove(orderAfterSalesFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	orderAfterSalesRowsWithPlaceHolder = strings.Join(stringx.Remove(orderAfterSalesFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	orderAfterSalesModel interface {
		Insert(ctx context.Context, data *OrderAfterSale) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*OrderAfterSale, error)
		Update(ctx context.Context, data *OrderAfterSale) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultOrderAfterSalesModel struct {
		conn  sqlx.SqlConn
		table string
	}

	OrderAfterSale struct {
		ID          uint64    `db:"id"`
		OrderID     uint64    `db:"order_id"`
		OrderNo     string    `db:"order_no"`
		UserID      uint64    `db:"user_id"`
		ShopID      uint64    `db:"shop_id"`
		Type        string    `db:"type"`
		Reason      string    `db:"reason"`
		Amount      float64   `db:"amount"`
		Status      string    `db:"status"`
		AdminRemark string    `db:"admin_remark"`
		HandledBy   uint64    `db:"handled_by"`
		CreatedAt   common.LocalTime `db:"created_at"`
		UpdatedAt   common.LocalTime `db:"updated_at"`
	}
)

func newOrderAfterSalesModel(conn sqlx.SqlConn) *defaultOrderAfterSalesModel {
	return &defaultOrderAfterSalesModel{
		conn:  conn,
		table: "`order_after_sales`",
	}
}

func (m *defaultOrderAfterSalesModel) Delete(ctx context.Context, id uint64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultOrderAfterSalesModel) FindOne(ctx context.Context, id uint64) (*OrderAfterSale, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", orderAfterSalesRows, m.table)
	var resp OrderAfterSale
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultOrderAfterSalesModel) Insert(ctx context.Context, data *OrderAfterSale) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, orderAfterSalesRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.OrderID, data.OrderNo, data.UserID, data.ShopID, data.Type, data.Reason, data.Amount, data.Status, data.AdminRemark, data.HandledBy)
	return ret, err
}

func (m *defaultOrderAfterSalesModel) Update(ctx context.Context, data *OrderAfterSale) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, orderAfterSalesRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.OrderID, data.OrderNo, data.UserID, data.ShopID, data.Type, data.Reason, data.Amount, data.Status, data.AdminRemark, data.HandledBy, data.ID)
	return err
}

func (m *defaultOrderAfterSalesModel) tableName() string {
	return m.table
}
