// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.8.5

package modelgen

import (
	"mymall/common"
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	orderItemsFieldNames          = builder.RawFieldNames(&OrderItem{})
	orderItemsRows                = strings.Join(orderItemsFieldNames, ",")
	orderItemsRowsExpectAutoSet   = strings.Join(stringx.Remove(orderItemsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	orderItemsRowsWithPlaceHolder = strings.Join(stringx.Remove(orderItemsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	orderItemsModel interface {
		Insert(ctx context.Context, data *OrderItem) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*OrderItem, error)
		Update(ctx context.Context, data *OrderItem) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultOrderItemsModel struct {
		conn  sqlx.SqlConn
		table string
	}

	OrderItem struct {
		ID          uint64         `db:"id"`
		OrderID     uint64         `db:"order_id"`
		ProductID   uint64         `db:"product_id"`
		SKUID       uint64         `db:"sku_id"` // SKU ID
		ProductName string         `db:"product_name"`
		SKUSnapshot string `db:"sku_snapshot"` // SKU规格快照
		Price       float64        `db:"price"`
		Quantity    int          `db:"quantity"`
		CreatedAt   common.LocalTime      `db:"created_at"`
	}
)

func newOrderItemsModel(conn sqlx.SqlConn) *defaultOrderItemsModel {
	return &defaultOrderItemsModel{
		conn:  conn,
		table: "`order_items`",
	}
}

func (m *defaultOrderItemsModel) Delete(ctx context.Context, id uint64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultOrderItemsModel) FindOne(ctx context.Context, id uint64) (*OrderItem, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", orderItemsRows, m.table)
	var resp OrderItem
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultOrderItemsModel) Insert(ctx context.Context, data *OrderItem) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?)", m.table, orderItemsRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.OrderID, data.ProductID, data.SKUID, data.ProductName, data.SKUSnapshot, data.Price, data.Quantity)
	return ret, err
}

func (m *defaultOrderItemsModel) Update(ctx context.Context, data *OrderItem) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, orderItemsRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.OrderID, data.ProductID, data.SKUID, data.ProductName, data.SKUSnapshot, data.Price, data.Quantity, data.ID)
	return err
}

func (m *defaultOrderItemsModel) tableName() string {
	return m.table
}
