// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.8.5

package modelgen

import (
	"mymall/common"
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	ordersFieldNames          = builder.RawFieldNames(&Order{})
	ordersRows                = strings.Join(ordersFieldNames, ",")
	ordersRowsExpectAutoSet   = strings.Join(stringx.Remove(ordersFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	ordersRowsWithPlaceHolder = strings.Join(stringx.Remove(ordersFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	ordersModel interface {
		Insert(ctx context.Context, data *Order) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*Order, error)
		FindOneByOrderNo(ctx context.Context, orderNo string) (*Order, error)
		Update(ctx context.Context, data *Order) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultOrdersModel struct {
		conn  sqlx.SqlConn
		table string
	}

	Order struct {
		ID          uint64    `db:"id"`
		OrderNo     string    `db:"order_no"`
		UserID      uint64    `db:"user_id"`
		ShopID      uint64    `db:"shop_id"`
		TotalAmount float64   `db:"total_amount"`
		Status      string    `db:"status"`
		CreatedAt   common.LocalTime `db:"created_at"`
		UpdatedAt   common.LocalTime `db:"updated_at"`
	}
)

func newOrdersModel(conn sqlx.SqlConn) *defaultOrdersModel {
	return &defaultOrdersModel{
		conn:  conn,
		table: "`orders`",
	}
}

func (m *defaultOrdersModel) Delete(ctx context.Context, id uint64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultOrdersModel) FindOne(ctx context.Context, id uint64) (*Order, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", ordersRows, m.table)
	var resp Order
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultOrdersModel) FindOneByOrderNo(ctx context.Context, orderNo string) (*Order, error) {
	var resp Order
	query := fmt.Sprintf("select %s from %s where `order_no` = ? limit 1", ordersRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, orderNo)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultOrdersModel) Insert(ctx context.Context, data *Order) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?)", m.table, ordersRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.OrderNo, data.UserID, data.ShopID, data.TotalAmount, data.Status)
	return ret, err
}

func (m *defaultOrdersModel) Update(ctx context.Context, newData *Order) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, ordersRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.OrderNo, newData.UserID, newData.ShopID, newData.TotalAmount, newData.Status, newData.ID)
	return err
}

func (m *defaultOrdersModel) tableName() string {
	return m.table
}
