// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.8.5

package modelgen

import (
	"mymall/common"
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	productReviewsFieldNames          = builder.RawFieldNames(&ProductReview{})
	productReviewsRows                = strings.Join(productReviewsFieldNames, ",")
	productReviewsRowsExpectAutoSet   = strings.Join(stringx.Remove(productReviewsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	productReviewsRowsWithPlaceHolder = strings.Join(stringx.Remove(productReviewsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	productReviewsModel interface {
		Insert(ctx context.Context, data *ProductReview) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*ProductReview, error)
		FindOneByOrderId(ctx context.Context, orderId uint64) (*ProductReview, error)
		Update(ctx context.Context, data *ProductReview) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultProductReviewsModel struct {
		conn  sqlx.SqlConn
		table string
	}

	ProductReview struct {
		ID            uint64       `db:"id"`
		OrderID       uint64       `db:"order_id"`
		OrderNo       string       `db:"order_no"`
		UserID        uint64       `db:"user_id"`
		ShopID        uint64       `db:"shop_id"`
		ProductID     uint64       `db:"product_id"`
		OrderItemID   uint64       `db:"order_item_id"`
		SKUID         uint64       `db:"sku_id"`
		SKUSnapshot   string       `db:"sku_snapshot"`
		Rating        int        `db:"rating"`
		Content       string       `db:"content"`
		IsAnonymous   int        `db:"is_anonymous"`
		Status        string       `db:"status"` // visible/deleted
		MerchantReply string       `db:"merchant_reply"`
		RepliedAt     common.LocalTime `db:"replied_at"`
		CreatedAt     common.LocalTime    `db:"created_at"`
		UpdatedAt     common.LocalTime    `db:"updated_at"`
	}
)

func newProductReviewsModel(conn sqlx.SqlConn) *defaultProductReviewsModel {
	return &defaultProductReviewsModel{
		conn:  conn,
		table: "`product_reviews`",
	}
}

func (m *defaultProductReviewsModel) Delete(ctx context.Context, id uint64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultProductReviewsModel) FindOne(ctx context.Context, id uint64) (*ProductReview, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", productReviewsRows, m.table)
	var resp ProductReview
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultProductReviewsModel) FindOneByOrderId(ctx context.Context, orderId uint64) (*ProductReview, error) {
	var resp ProductReview
	query := fmt.Sprintf("select %s from %s where `order_id` = ? limit 1", productReviewsRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, orderId)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultProductReviewsModel) Insert(ctx context.Context, data *ProductReview) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, productReviewsRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.OrderID, data.OrderNo, data.UserID, data.ShopID, data.ProductID, data.OrderItemID, data.SKUID, data.SKUSnapshot, data.Rating, data.Content, data.IsAnonymous, data.Status, data.MerchantReply, data.RepliedAt)
	return ret, err
}

func (m *defaultProductReviewsModel) Update(ctx context.Context, newData *ProductReview) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, productReviewsRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.OrderID, newData.OrderNo, newData.UserID, newData.ShopID, newData.ProductID, newData.OrderItemID, newData.SKUID, newData.SKUSnapshot, newData.Rating, newData.Content, newData.IsAnonymous, newData.Status, newData.MerchantReply, newData.RepliedAt, newData.ID)
	return err
}

func (m *defaultProductReviewsModel) tableName() string {
	return m.table
}
