// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.8.5

package modelgen

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	productReviewImagesFieldNames          = builder.RawFieldNames(&ProductReviewImage{})
	productReviewImagesRows                = strings.Join(productReviewImagesFieldNames, ",")
	productReviewImagesRowsExpectAutoSet   = strings.Join(stringx.Remove(productReviewImagesFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	productReviewImagesRowsWithPlaceHolder = strings.Join(stringx.Remove(productReviewImagesFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	productReviewImagesModel interface {
		Insert(ctx context.Context, data *ProductReviewImage) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*ProductReviewImage, error)
		Update(ctx context.Context, data *ProductReviewImage) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultProductReviewImagesModel struct {
		conn  sqlx.SqlConn
		table string
	}

	ProductReviewImage struct {
		ID       uint64 `db:"id"`
		ReviewID uint64 `db:"review_id"`
		URL      string `db:"url"`
		Sort     int  `db:"sort"`
	}
)

func newProductReviewImagesModel(conn sqlx.SqlConn) *defaultProductReviewImagesModel {
	return &defaultProductReviewImagesModel{
		conn:  conn,
		table: "`product_review_images`",
	}
}

func (m *defaultProductReviewImagesModel) Delete(ctx context.Context, id uint64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultProductReviewImagesModel) FindOne(ctx context.Context, id uint64) (*ProductReviewImage, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", productReviewImagesRows, m.table)
	var resp ProductReviewImage
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultProductReviewImagesModel) Insert(ctx context.Context, data *ProductReviewImage) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?)", m.table, productReviewImagesRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.ReviewID, data.URL, data.Sort)
	return ret, err
}

func (m *defaultProductReviewImagesModel) Update(ctx context.Context, data *ProductReviewImage) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, productReviewImagesRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.ReviewID, data.URL, data.Sort, data.ID)
	return err
}

func (m *defaultProductReviewImagesModel) tableName() string {
	return m.table
}
