server:
  http_port: 8882
  grpc_port: 9091
  mode: debug
mysql:
  host: 127.0.0.1
  port: 3306
  username: homestead
  password: secret
  charset: utf8mb4
  dbname: catalog_db
  max_open_conns: 50
  max_idle_conns: 10
  conn_max_lifetime: 3600
  conn_max_idle_time: 3600
redis:
  host: 127.0.0.1
  port: 6379
  password: ""
  db: 0
rabbitmq:
  host: 127.0.0.1
  port: 5672
  username: mymall
  password: mymall
  vhost: /
  exchange: mymall.events
telemetry:
  enabled: false
  endpoint: jaeger-collector.mymall:4318
  service: catalog-service
