// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5
// Source: catalog.proto

package server

import (
	"context"

	rpclogic "mymall/services/catalog-service/internal/rpclogic"
	"mymall/services/catalog-service/internal/svc"
	catalogv1 "mymall/api/gen/catalog/v1"
)

type CatalogServiceServer struct {
	svcCtx *svc.ServiceContext
	catalogv1.UnimplementedCatalogServiceServer
}

func NewCatalogServiceServer(svcCtx *svc.ServiceContext) *CatalogServiceServer {
	return &CatalogServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *CatalogServiceServer) BatchGetProducts(ctx context.Context, in *catalogv1.BatchGetProductsRequest) (*catalogv1.BatchGetProductsResponse, error) {
	l := rpclogic.NewBatchGetProductsLogic(ctx, s.svcCtx)
	return l.BatchGetProducts(in)
}

func (s *CatalogServiceServer) ReserveStock(ctx context.Context, in *catalogv1.ReserveStockRequest) (*catalogv1.ReserveStockResponse, error) {
	l := rpclogic.NewReserveStockLogic(ctx, s.svcCtx)
	return l.ReserveStock(in)
}

func (s *CatalogServiceServer) ReleaseStock(ctx context.Context, in *catalogv1.ReleaseStockRequest) (*catalogv1.ReleaseStockResponse, error) {
	l := rpclogic.NewReleaseStockLogic(ctx, s.svcCtx)
	return l.ReleaseStock(in)
}
