#################################################
# canal instance for mymall (mounted into canal-server)
#################################################
canal.instance.mysql.slaveId=1234
canal.instance.master.address=host.docker.internal:3306
canal.instance.dbUsername=canal
canal.instance.dbPassword=canal
canal.instance.connectionCharset=UTF-8
canal.instance.defaultDatabaseName=mymall
canal.instance.filter.regex=mymall\\.product_skus,mymall\\.products
canal.instance.filter.black.regex=
canal.instance.tsdb.enable=false
canal.instance.gtidon=false
