logging:
  file:
    enable: true
    level: INFO
    path: logs
    rotation: "10 MB"
    retention: "7 days"
  console:
    enable: true
    level: INFO

db_meta:
  host: localhost
  port: 3306
  user: homestead
  password: secret
  database: mymall

db_dw:
  host: localhost
  port: 3306
  user: homestead
  password: secret
  database: mymall

qdrant:  
  host: localhost
  port: 6333
  embedding_size: 1024

embedding:
  host: 127.0.0.1
  port: 8082
  model: BAAI/bge-large-zh-v1.5

es:
  host: localhost
  port: 9200
  index_name: data_agent

llm:
  model_name: qwen2.5:7b
  model_provider: ollama
  api_key: <api_key>
  base_url: http://127.0.0.1:11434
