// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5

package handler

import (
	"net/http"

	admin "mymall/services/order-service/internal/handler/admin"
	merchant "mymall/services/order-service/internal/handler/merchant"
	public "mymall/services/order-service/internal/handler/public"
	shared "mymall/services/order-service/internal/handler/shared"
	user "mymall/services/order-service/internal/handler/user"
	"mymall/services/order-service/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.RequestID, serverCtx.GatewayIdentity, serverCtx.RequirePlatformAdmin},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/admin/after-sales",
					Handler: admin.AdminAfterSalesHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/api/v1/admin/after-sales/:id/handle",
					Handler: admin.AdminHandleAfterSaleHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/admin/logistics",
					Handler: admin.AdminListLogisticsHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/v1/admin/logistics",
					Handler: admin.AdminCreateLogisticsHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/api/v1/admin/logistics/:id",
					Handler: admin.AdminUpdateLogisticsHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/api/v1/admin/logistics/:id",
					Handler: admin.AdminDeleteLogisticsHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/api/v1/admin/logistics/:id/status",
					Handler: admin.UpdateStatusHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/admin/orders",
					Handler: admin.AdminListOrdersHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/admin/orders/:id",
					Handler: admin.AdminDetailHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/api/v1/admin/orders/:id/complete",
					Handler: admin.AdminCompleteHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/api/v1/admin/orders/:id/remark",
					Handler: admin.AdminRemarkHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/api/v1/admin/orders/:id/ship",
					Handler: admin.AdminShipHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/admin/reviews",
					Handler: admin.AdminListReviewsHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/api/v1/admin/reviews/:id",
					Handler: admin.AdminDeleteHandler(serverCtx),
				},
			}...,
		),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.RequestID, serverCtx.GatewayIdentityShop, serverCtx.RequireMerchantOwner},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/merchant/after-sales",
					Handler: merchant.MerchantAfterSalesHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/api/v1/merchant/after-sales/:id/handle",
					Handler: merchant.MerchantHandleAfterSaleHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/merchant/orders",
					Handler: merchant.MerchantListOrdersHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/merchant/orders/:id",
					Handler: merchant.MerchantDetailHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/api/v1/merchant/orders/:id/complete",
					Handler: merchant.MerchantCompleteHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/api/v1/merchant/orders/:id/remark",
					Handler: merchant.MerchantRemarkHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/api/v1/merchant/orders/:id/ship",
					Handler: merchant.MerchantShipHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/merchant/reviews",
					Handler: merchant.MerchantListReviewsHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/api/v1/merchant/reviews/:id",
					Handler: merchant.MerchantDeleteHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/api/v1/merchant/reviews/:id/reply",
					Handler: merchant.MerchantReplyHandler(serverCtx),
				},
			}...,
		),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.RequestID},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/products/:id/reviews",
					Handler: public.PublicListProductReviewsHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/healthz",
					Handler: public.HealthzHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/metrics",
					Handler: public.MetricsHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/readyz",
					Handler: public.ReadyzHandler(serverCtx),
				},
			}...,
		),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.RequestID, serverCtx.GatewayIdentity, serverCtx.RequirePlatformOrMerchant},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/logistics/options",
					Handler: shared.LogisticsOptionsHandler(serverCtx),
				},
			}...,
		),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.RequestID, serverCtx.GatewayIdentity},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/api/v1/orders",
					Handler: user.UserCreateOrderHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/orders",
					Handler: user.UserListOrdersHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/orders/:id",
					Handler: user.UserGetOrderHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/v1/orders/:id/after-sales",
					Handler: user.CreateAfterSaleHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/api/v1/orders/:id/cancel",
					Handler: user.CancelHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/api/v1/orders/:id/confirm-receive",
					Handler: user.ConfirmReceiveHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/orders/:id/review",
					Handler: user.GetByOrderHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/orders/:id/review-eligible",
					Handler: user.EligibleHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/v1/orders/:id/reviews",
					Handler: user.UserCreateReviewHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/orders/after-sales",
					Handler: user.UserAfterSalesHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/v1/orders/coupon-preview",
					Handler: user.CouponPreviewHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/orders/status-counts",
					Handler: user.StatusCountsHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/v1/user/review-uploads",
					Handler: user.UserUploadReviewHandler(serverCtx),
				},
			}...,
		),
	)
}
