// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5

package handler

import (
	"net/http"

	"mymall/services/order-service/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.RequestID},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/products/:id/reviews",
					Handler: ProductListHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/healthz",
					Handler: HealthzHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/metrics",
					Handler: MetricsHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/readyz",
					Handler: ReadyzHandler(serverCtx),
				},
			}...,
		),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.RequestID, serverCtx.GatewayIdentity},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/api/v1/orders",
					Handler: CreateHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/orders",
					Handler: ListHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/orders/:id",
					Handler: DetailHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/v1/orders/:id/after-sales",
					Handler: CreateAfterSaleHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/api/v1/orders/:id/cancel",
					Handler: CancelHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/api/v1/orders/:id/confirm-receive",
					Handler: ConfirmReceiveHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/orders/:id/review",
					Handler: GetByOrderHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/orders/:id/review-eligible",
					Handler: EligibleHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/v1/orders/:id/reviews",
					Handler: Create2Handler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/orders/after-sales",
					Handler: UserAfterSalesHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/v1/orders/coupon-preview",
					Handler: CouponPreviewHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/orders/status-counts",
					Handler: StatusCountsHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/v1/user/review-uploads",
					Handler: UploadHandler(serverCtx),
				},
			}...,
		),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.RequestID, serverCtx.GatewayIdentityShop, serverCtx.RequireMerchantOwner},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/merchant/after-sales",
					Handler: MerchantAfterSalesHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/api/v1/merchant/after-sales/:id/handle",
					Handler: MerchantHandleAfterSaleHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/merchant/orders",
					Handler: MerchantList2Handler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/merchant/orders/:id",
					Handler: MerchantDetailHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/api/v1/merchant/orders/:id/complete",
					Handler: MerchantCompleteHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/api/v1/merchant/orders/:id/remark",
					Handler: MerchantRemarkHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/api/v1/merchant/orders/:id/ship",
					Handler: MerchantShipHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/merchant/reviews",
					Handler: MerchantListHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/api/v1/merchant/reviews/:id",
					Handler: MerchantDeleteHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/api/v1/merchant/reviews/:id/reply",
					Handler: MerchantReplyHandler(serverCtx),
				},
			}...,
		),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.RequestID, serverCtx.GatewayIdentity, serverCtx.RequirePlatformOrMerchant},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/logistics/options",
					Handler: OptionsHandler(serverCtx),
				},
			}...,
		),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.RequestID, serverCtx.GatewayIdentity, serverCtx.RequirePlatformAdmin},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/admin/after-sales",
					Handler: AdminAfterSalesHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/api/v1/admin/after-sales/:id/handle",
					Handler: AdminHandleAfterSaleHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/admin/logistics",
					Handler: AdminList3Handler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/v1/admin/logistics",
					Handler: Create3Handler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/api/v1/admin/logistics/:id",
					Handler: UpdateHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/api/v1/admin/logistics/:id",
					Handler: DeleteHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/api/v1/admin/logistics/:id/status",
					Handler: UpdateStatusHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/admin/orders",
					Handler: AdminList2Handler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/admin/orders/:id",
					Handler: AdminDetailHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/api/v1/admin/orders/:id/complete",
					Handler: AdminCompleteHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/api/v1/admin/orders/:id/remark",
					Handler: AdminRemarkHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/api/v1/admin/orders/:id/ship",
					Handler: AdminShipHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/admin/reviews",
					Handler: AdminListHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/api/v1/admin/reviews/:id",
					Handler: AdminDeleteHandler(serverCtx),
				},
			}...,
		),
	)
}
