// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package handler

import (
	"net/http"

	adminlogistics "mymall/services/order-service/internal/handler/admin/logistics"
	adminorder "mymall/services/order-service/internal/handler/admin/order"
	adminreview "mymall/services/order-service/internal/handler/admin/review"
	merchantorder "mymall/services/order-service/internal/handler/merchant/order"
	merchantreview "mymall/services/order-service/internal/handler/merchant/review"
	publichealth "mymall/services/order-service/internal/handler/public/health"
	publicreview "mymall/services/order-service/internal/handler/public/review"
	sharedlogistics "mymall/services/order-service/internal/handler/shared/logistics"
	userorder "mymall/services/order-service/internal/handler/user/order"
	userreview "mymall/services/order-service/internal/handler/user/review"
	"mymall/services/order-service/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.RequestID, serverCtx.GatewayIdentity, serverCtx.RequirePlatformAdmin},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/admin/logistics",
					Handler: adminlogistics.AdminListLogisticsHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/v1/admin/logistics",
					Handler: adminlogistics.AdminCreateLogisticsHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/api/v1/admin/logistics/:id",
					Handler: adminlogistics.AdminUpdateLogisticsHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/api/v1/admin/logistics/:id",
					Handler: adminlogistics.AdminDeleteLogisticsHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/api/v1/admin/logistics/:id/status",
					Handler: adminlogistics.UpdateStatusHandler(serverCtx),
				},
			}...,
		),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.RequestID, serverCtx.GatewayIdentity, serverCtx.RequirePlatformAdmin},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/admin/after-sales",
					Handler: adminorder.AdminAfterSalesHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/api/v1/admin/after-sales/:id/handle",
					Handler: adminorder.AdminHandleAfterSaleHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/admin/orders",
					Handler: adminorder.AdminListOrdersHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/admin/orders/:id",
					Handler: adminorder.AdminDetailHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/api/v1/admin/orders/:id/complete",
					Handler: adminorder.AdminCompleteHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/api/v1/admin/orders/:id/remark",
					Handler: adminorder.AdminRemarkHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/api/v1/admin/orders/:id/ship",
					Handler: adminorder.AdminShipHandler(serverCtx),
				},
			}...,
		),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.RequestID, serverCtx.GatewayIdentity, serverCtx.RequirePlatformAdmin},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/admin/reviews",
					Handler: adminreview.AdminListReviewsHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/api/v1/admin/reviews/:id",
					Handler: adminreview.AdminDeleteHandler(serverCtx),
				},
			}...,
		),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.RequestID, serverCtx.GatewayIdentityShop, serverCtx.RequireMerchantOwner},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/merchant/after-sales",
					Handler: merchantorder.MerchantAfterSalesHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/api/v1/merchant/after-sales/:id/handle",
					Handler: merchantorder.MerchantHandleAfterSaleHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/merchant/orders",
					Handler: merchantorder.MerchantListOrdersHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/merchant/orders/:id",
					Handler: merchantorder.MerchantDetailHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/api/v1/merchant/orders/:id/complete",
					Handler: merchantorder.MerchantCompleteHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/api/v1/merchant/orders/:id/remark",
					Handler: merchantorder.MerchantRemarkHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/api/v1/merchant/orders/:id/ship",
					Handler: merchantorder.MerchantShipHandler(serverCtx),
				},
			}...,
		),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.RequestID, serverCtx.GatewayIdentityShop, serverCtx.RequireMerchantOwner},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/merchant/reviews",
					Handler: merchantreview.MerchantListReviewsHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/api/v1/merchant/reviews/:id",
					Handler: merchantreview.MerchantDeleteHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/api/v1/merchant/reviews/:id/reply",
					Handler: merchantreview.MerchantReplyHandler(serverCtx),
				},
			}...,
		),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.RequestID},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/healthz",
					Handler: publichealth.HealthzHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/metrics",
					Handler: publichealth.MetricsHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/readyz",
					Handler: publichealth.ReadyzHandler(serverCtx),
				},
			}...,
		),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.RequestID},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/products/:id/reviews",
					Handler: publicreview.PublicListProductReviewsHandler(serverCtx),
				},
			}...,
		),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.RequestID, serverCtx.GatewayIdentity, serverCtx.RequirePlatformOrMerchant},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/logistics/options",
					Handler: sharedlogistics.LogisticsOptionsHandler(serverCtx),
				},
			}...,
		),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.RequestID, serverCtx.GatewayIdentity},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/api/v1/orders",
					Handler: userorder.UserCreateOrderHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/orders",
					Handler: userorder.UserListOrdersHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/orders/:id",
					Handler: userorder.UserGetOrderHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/v1/orders/:id/after-sales",
					Handler: userorder.CreateAfterSaleHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/api/v1/orders/:id/cancel",
					Handler: userorder.CancelHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/api/v1/orders/:id/confirm-receive",
					Handler: userorder.ConfirmReceiveHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/orders/after-sales",
					Handler: userorder.UserAfterSalesHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/v1/orders/coupon-preview",
					Handler: userorder.CouponPreviewHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/orders/status-counts",
					Handler: userorder.StatusCountsHandler(serverCtx),
				},
			}...,
		),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.RequestID, serverCtx.GatewayIdentity},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/orders/:id/review",
					Handler: userreview.GetByOrderHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/orders/:id/review-eligible",
					Handler: userreview.EligibleHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/v1/orders/:id/reviews",
					Handler: userreview.UserCreateReviewHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/v1/user/review-uploads",
					Handler: userreview.UserUploadReviewHandler(serverCtx),
				},
			}...,
		),
	)
}
