// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5

package types

type AnyResp struct {
	Data interface{} `json:"data,optional"`
}

// DataResp is the preferred name for opaque entity JSON bodies.
type DataResp = AnyResp

type CodePathReq struct {
	Code string `path:"code"`
}

type EmptyResp struct {
}

type ListResp struct {
	List interface{} `json:"list"`
}

type FilePathReq struct {
	File string `path:"file"`
}

type IdPathReq struct {
	Id uint64 `path:"id"`
}


type PageListResp struct {
	Total int64       `json:"total"`
	List  interface{} `json:"list"`
}

type PageReq struct {
	Page     int    `form:"page,default=1"`
	PageSize int    `form:"page_size,default=10"`
	City     string `form:"city,optional"`
	SlotType string `form:"slot_type,optional"`
}
