#!/usr/bin/env bash
# Verify goctl-generated routes match api/*.api and carry goctl header.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
SERVICE="${1:-}"

usage() {
  echo "usage: $0 <service-name|all>" >&2
  exit 2
}

[[ -n "$SERVICE" ]] || usage

check_one() {
  local name="$1"
  local dir="$ROOT/services/$name"
  local api routes main
  api="$(find "$dir/api" -name '*.api' 2>/dev/null | head -1 || true)"
  routes="$dir/internal/handler/routes.go"
  main="$dir/cmd/main.go"

  if [[ -z "$api" || ! -f "$api" ]]; then
    echo "[$name] FAIL: missing api/*.api" >&2
    return 1
  fi
  if [[ ! -f "$routes" ]]; then
    echo "[$name] FAIL: missing internal/handler/routes.go" >&2
    return 1
  fi
  if ! grep -q 'Code generated by goctl' "$routes"; then
    echo "[$name] FAIL: routes.go is not goctl-generated (missing goctl header)" >&2
    return 1
  fi
  if [[ -f "$main" ]] && grep -E 'Path:\s*"/api/' "$main" >/dev/null 2>&1; then
    echo "[$name] FAIL: cmd/main.go still contains Path: \"/api/..." >&2
    return 1
  fi

  local tmp
  tmp="$(mktemp -d)"
  trap 'rm -rf "$tmp"' RETURN

  python3 - "$api" "$tmp/api.txt" <<'PY'
import re, sys
api, out = sys.argv[1], sys.argv[2]
text = open(api).read()
text = re.sub(r'//.*?$', '', text, flags=re.M)
pat = re.compile(r'(?im)^\s*(get|post|put|delete|patch)\s+(\S+)')
rows = {f"{m.group(1).upper()} {m.group(2)}" for m in pat.finditer(text)}
open(out, 'w').write('\n'.join(sorted(rows)) + ('\n' if rows else ''))
print(len(rows))
PY

  python3 - "$routes" "$tmp/routes.txt" <<'PY'
import re, sys
path, out = sys.argv[1], sys.argv[2]
text = open(path).read()
pat = re.compile(
    r'Method:\s*http\.Method(Get|Post|Put|Delete|Patch)\s*,\s*Path:\s*"([^"]+)"',
    re.I,
)
rows = {f"{m.group(1).upper()} {m.group(2)}" for m in pat.finditer(text)}
open(out, 'w').write('\n'.join(sorted(rows)) + ('\n' if rows else ''))
print(len(rows))
PY

  api_count=$(wc -l < "$tmp/api.txt" | tr -d ' ')
  routes_count=$(wc -l < "$tmp/routes.txt" | tr -d ' ')
  if ! diff -u "$tmp/api.txt" "$tmp/routes.txt" > "$tmp/diff.txt"; then
    echo "[$name] FAIL: .api ($api_count) vs goctl routes.go ($routes_count) mismatch:" >&2
    cat "$tmp/diff.txt" >&2
    return 1
  fi
  echo "[$name] OK: $api_count goctl routes match .api"
}

if [[ "$SERVICE" == "all" ]]; then
  ec=0
  for s in merchant-service order-service user-service catalog-service inventory-sync-service; do
    [[ -d "$ROOT/services/$s" ]] || continue
    check_one "$s" || ec=1
  done
  exit $ec
fi

check_one "$SERVICE"
