-- mymall 业务表（users / products / product_categories）
-- 执行：mysql -u homestead -p mymall < scripts/init-schema.sql

USE mymall;

CREATE TABLE IF NOT EXISTS users (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    mobile CHAR(11) NOT NULL COMMENT '登录手机号',
    password VARCHAR(255) NOT NULL COMMENT '登录密码',
    nickname VARCHAR(50) NOT NULL COMMENT '用户昵称',
    avatar VARCHAR(255) NOT NULL DEFAULT '' COMMENT '用户头像URL',
	gender TINYINT NOT NULL DEFAULT 0 COMMENT '性别：0-未知 1-男 2-女',
    status TINYINT NOT NULL DEFAULT 1 COMMENT '账号状态：1-正常 0-禁用',
    role VARCHAR(32) NOT NULL DEFAULT 'user' COMMENT '角色',
    last_login_time TIMESTAMP NULL DEFAULT NULL COMMENT '最后登录时间',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP NULL DEFAULT NULL,
    UNIQUE KEY uk_mobile (mobile),
    INDEX idx_deleted_at (deleted_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS product_categories (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    parent_id INT NOT NULL DEFAULT 0 COMMENT '父分类ID',
    name VARCHAR(100) NOT NULL COMMENT '分类名称',
    icon VARCHAR(200) DEFAULT NULL COMMENT '分类图标',
    image VARCHAR(500) DEFAULT NULL COMMENT '分类图片',
    description VARCHAR(500) DEFAULT NULL COMMENT '分类描述',
    sort_order INT NOT NULL DEFAULT 0 COMMENT '排序',
    level INT NOT NULL DEFAULT 1 COMMENT '分类层级',
    is_show TINYINT(1) NOT NULL DEFAULT 1 COMMENT '是否显示',
    product_count INT NOT NULL DEFAULT 0 COMMENT '商品数量',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS products (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    shop_id BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '所属店铺ID',
    product_no VARCHAR(50) NOT NULL COMMENT '商品编号',
    name VARCHAR(200) NOT NULL COMMENT '商品名称',
    subtitle VARCHAR(500) DEFAULT NULL COMMENT '商品副标题',
    description TEXT DEFAULT NULL COMMENT '商品描述',
    main_image VARCHAR(500) DEFAULT NULL COMMENT '主图',
    image_list JSON DEFAULT NULL COMMENT '商品图片列表',
    video_url VARCHAR(500) DEFAULT NULL COMMENT '商品视频',
    market_price DECIMAL(10,2) DEFAULT NULL COMMENT '市场价',
    sale_price DECIMAL(10,2) NOT NULL COMMENT '销售价',
    cost_price DECIMAL(10,2) DEFAULT NULL COMMENT '成本价',
    discount DECIMAL(5,2) NOT NULL DEFAULT 100.00 COMMENT '折扣(百分比)',
    discount_price DECIMAL(10,2) DEFAULT NULL COMMENT '折后价',
    stock INT NOT NULL DEFAULT 0 COMMENT '库存数量',
    stock_warn INT NOT NULL DEFAULT 10 COMMENT '库存预警值',
    sold_count INT NOT NULL DEFAULT 0 COMMENT '已售数量',
    view_count INT NOT NULL DEFAULT 0 COMMENT '浏览数量',
    collect_count INT NOT NULL DEFAULT 0 COMMENT '收藏数量',
    pet_type ENUM('dog','cat','both','other') NOT NULL DEFAULT 'both' COMMENT '宠物类型',
    pet_age JSON DEFAULT NULL COMMENT '适用年龄',
    pet_size JSON DEFAULT NULL COMMENT '适用体型',
    weight DECIMAL(8,2) DEFAULT NULL COMMENT '重量(kg)',
    unit VARCHAR(20) DEFAULT NULL COMMENT '单位',
    brand_id INT DEFAULT NULL COMMENT '品牌ID',
    category_id INT NOT NULL COMMENT '分类ID',
    tags JSON DEFAULT NULL COMMENT '标签数组',
    nutrition_info JSON DEFAULT NULL COMMENT '营养成分表',
    ingredients TEXT DEFAULT NULL COMMENT '主要成分',
    feeding_guide TEXT DEFAULT NULL COMMENT '喂养指南',
    shelf_life INT DEFAULT NULL COMMENT '保质期(天)',
    storage_condition VARCHAR(200) DEFAULT NULL COMMENT '存储条件',
    status ENUM('draft','pending','approved','rejected','on_sale','off_sale','deleted') NOT NULL DEFAULT 'draft' COMMENT '状态',
    is_hot TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否热销',
    is_new TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否新品',
    is_recommend TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否推荐',
    is_prescription TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否处方粮',
    is_imported TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否进口',
    is_organic TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否有机',
    is_grain_free TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否无谷',
    publish_time DATETIME DEFAULT NULL COMMENT '上架时间',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP NULL DEFAULT NULL,
    UNIQUE KEY uk_product_no (product_no),
    INDEX idx_category_id (category_id),
    INDEX idx_brand_id (brand_id),
    INDEX idx_pet_type (pet_type),
    INDEX idx_status (status),
    INDEX idx_is_hot (is_hot),
    INDEX idx_is_new (is_new),
    INDEX idx_is_recommend (is_recommend),
    INDEX idx_deleted_at (deleted_at),
    INDEX idx_shop_id (shop_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
