// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5

package handler

import (
	"net/http"

	"mymall/services/merchant-service/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.RequestID},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/coupons/center",
					Handler: PublicCouponCenterHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/coupons/popup",
					Handler: PublicCouponPopupHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/home/theme-tiles",
					Handler: PublicThemeTilesHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/v1/internal/coupons/lock",
					Handler: InternalLockCouponHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/v1/internal/coupons/match",
					Handler: InternalMatchCouponsHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/v1/internal/coupons/order-gift",
					Handler: InternalOrderGiftHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/v1/internal/coupons/redeem",
					Handler: InternalRedeemCouponHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/v1/internal/coupons/return",
					Handler: InternalReturnCouponHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/v1/internal/coupons/unlock",
					Handler: InternalUnlockCouponHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/v1/seckill/consume",
					Handler: SeckillConsumeHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/seckill/current",
					Handler: PublicSeckillCurrentHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/seckill/entries/:id",
					Handler: PublicSeckillEntryHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/seckill/list",
					Handler: PublicSeckillListHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/v1/seckill/restore",
					Handler: SeckillRestoreHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/shops/:id",
					Handler: PublicGetShopHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/shops/home-slots",
					Handler: PublicHomeSlotsHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/shops/list",
					Handler: PublicListShopsHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/healthz",
					Handler: HealthzHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/readyz",
					Handler: ReadyzHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/uploads/points-mall/:file",
					Handler: ServePointsMallUploadHandler(serverCtx),
				},
			}...,
		),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.RequestID, serverCtx.GatewayIdentity},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/api/v1/coupons/:id/claim",
					Handler: ClaimCouponHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/v1/merchant/apply",
					Handler: ApplyHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/merchant/shops",
					Handler: MyShopsHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/user/coupons",
					Handler: ListMyCouponsHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/v1/user/points-mall/exchange",
					Handler: ExchangeHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/user/points-mall/orders",
					Handler: ListUserPointsOrdersHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/user/points-mall/orders/:id",
					Handler: DetailUserPointsOrderHandler(serverCtx),
				},
			}...,
		),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.RequestID, serverCtx.GatewayIdentity, serverCtx.RequireMerchantOwner},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/merchant/coupons",
					Handler: MerchantListCouponsHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/v1/merchant/coupons",
					Handler: MerchantCreateCouponHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/api/v1/merchant/coupons/:id",
					Handler: MerchantUpdateCouponHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/merchant/coupons/:id/claims",
					Handler: MerchantCouponClaimsHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/v1/merchant/coupons/:id/copy",
					Handler: MerchantCopyCouponHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/api/v1/merchant/coupons/:id/off",
					Handler: MerchantOffCouponHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/merchant/coupons/:id/redeems",
					Handler: MerchantCouponRedeemsHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/merchant/coupons/:id/stats",
					Handler: MerchantCouponStatsHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/v1/merchant/coupons/grant",
					Handler: MerchantGrantCouponHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/v1/merchant/homepage-orders",
					Handler: MerchantBuySlotHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/merchant/homepage-orders",
					Handler: MerchantListSlotOrdersHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/merchant/homepage-packages",
					Handler: MerchantListSlotPackagesHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/v1/merchant/seckill/entries",
					Handler: MerchantApplySeckillHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/merchant/seckill/entries",
					Handler: MerchantListSeckillEntriesHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/api/v1/merchant/seckill/entries/:id/auto-renew",
					Handler: MerchantSetSeckillAutoRenewHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/merchant/seckill/sessions",
					Handler: MerchantSeckillSessionsHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/api/v1/merchant/shops/:id",
					Handler: UpdateMyShopHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/v1/merchant/theme-orders",
					Handler: MerchantBuyThemeHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/merchant/theme-orders",
					Handler: MerchantListThemeOrdersHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/merchant/theme-packages",
					Handler: MerchantListThemePackagesHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/merchant/theme-slots",
					Handler: MerchantListThemeSlotsHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/merchant/wallet",
					Handler: MerchantGetWalletHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/merchant/wallet/logs",
					Handler: MerchantWalletLogsHandler(serverCtx),
				},
			}...,
		),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.RequestID, serverCtx.GatewayIdentity, serverCtx.RequirePlatformAdmin},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/admin/applications",
					Handler: AdminListApplicationsHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/v1/admin/applications/:id/approve",
					Handler: AdminApproveHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/v1/admin/applications/:id/reject",
					Handler: AdminRejectHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/admin/coupons",
					Handler: AdminListCouponsHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/v1/admin/coupons",
					Handler: AdminCreateCouponHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/api/v1/admin/coupons/:id",
					Handler: AdminUpdateCouponHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/admin/coupons/:id/claims",
					Handler: AdminCouponClaimsHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/v1/admin/coupons/:id/copy",
					Handler: AdminCopyCouponHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/api/v1/admin/coupons/:id/off",
					Handler: AdminOffCouponHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/admin/coupons/:id/redeems",
					Handler: AdminCouponRedeemsHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/admin/coupons/:id/stats",
					Handler: AdminCouponStatsHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/v1/admin/coupons/grant",
					Handler: AdminGrantCouponHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/admin/homepage-orders",
					Handler: AdminListSlotOrdersHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/v1/admin/homepage-orders/grant",
					Handler: AdminGrantSlotHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/admin/homepage-packages",
					Handler: AdminListSlotPackagesHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/v1/admin/homepage-packages",
					Handler: AdminCreateSlotPackageHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/api/v1/admin/homepage-packages/:id",
					Handler: AdminUpdateSlotPackageHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/admin/homepage-settings",
					Handler: AdminListSlotSettingsHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/api/v1/admin/homepage-settings",
					Handler: AdminUpdateSlotSettingsHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/admin/points-orders",
					Handler: ListPointsOrdersHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/admin/points-orders/:id",
					Handler: DetailPointsOrderHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/v1/admin/points-orders/:id/cancel",
					Handler: CancelPointsOrderHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/v1/admin/points-orders/:id/complete",
					Handler: CompletePointsOrderHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/api/v1/admin/points-orders/:id/remark",
					Handler: RemarkPointsOrderHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/v1/admin/points-orders/:id/ship",
					Handler: ShipPointsOrderHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/admin/points-products",
					Handler: ListPointsProductsHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/v1/admin/points-products",
					Handler: CreatePointsProductHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/admin/points-products/:id",
					Handler: DetailPointsProductHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/api/v1/admin/points-products/:id",
					Handler: UpdatePointsProductHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/api/v1/admin/points-products/:id",
					Handler: DeletePointsProductHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/api/v1/admin/points-products/:id/status",
					Handler: SetPointsProductStatusHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/v1/admin/points-products/upload",
					Handler: UploadPointsProductHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/admin/seckill/entries",
					Handler: AdminListSeckillEntriesHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/admin/seckill/rule",
					Handler: AdminGetSeckillRuleHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/api/v1/admin/seckill/rule",
					Handler: AdminUpdateSeckillRuleHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/admin/seckill/sessions",
					Handler: AdminListSeckillSessionsHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/admin/shops",
					Handler: AdminListShopsHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/v1/admin/shops",
					Handler: AdminCreateShopHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/admin/shops/:id",
					Handler: AdminGetShopHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/api/v1/admin/shops/:id",
					Handler: AdminUpdateShopHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/api/v1/admin/shops/:id/disable",
					Handler: AdminDisableShopHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/api/v1/admin/shops/:id/enable",
					Handler: AdminEnableShopHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/api/v1/admin/shops/:id/owner-password",
					Handler: AdminResetOwnerPasswordHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/admin/shops/:id/wallet",
					Handler: AdminGetWalletHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/v1/admin/shops/:id/wallet/adjust",
					Handler: AdminAdjustWalletHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/admin/shops/:id/wallet/logs",
					Handler: AdminWalletLogsHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/admin/theme-orders",
					Handler: AdminListThemeOrdersHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/v1/admin/theme-orders/grant",
					Handler: AdminGrantThemeHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/admin/theme-packages",
					Handler: AdminListThemePackagesHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/v1/admin/theme-packages",
					Handler: AdminCreateThemePackageHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/api/v1/admin/theme-packages/:id",
					Handler: AdminUpdateThemePackageHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/admin/theme-slots",
					Handler: AdminListThemeSlotsHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/api/v1/admin/theme-slots/:id",
					Handler: AdminUpdateThemeSlotHandler(serverCtx),
				},
			}...,
		),
	)
}
