// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5

package handler

import (
	"net/http"

	adminapplication "mymall/services/merchant-service/internal/handler/admin/application"
	admincoupon "mymall/services/merchant-service/internal/handler/admin/coupon"
	adminhomepage "mymall/services/merchant-service/internal/handler/admin/homepage"
	adminseckill "mymall/services/merchant-service/internal/handler/admin/seckill"
	adminshop "mymall/services/merchant-service/internal/handler/admin/shop"
	admintheme "mymall/services/merchant-service/internal/handler/admin/theme"
	adminwallet "mymall/services/merchant-service/internal/handler/admin/wallet"
	internalapicoupon "mymall/services/merchant-service/internal/handler/internalapi/coupon"
	internalapiseckill "mymall/services/merchant-service/internal/handler/internalapi/seckill"
	merchantcoupon "mymall/services/merchant-service/internal/handler/merchant/coupon"
	merchanthomepage "mymall/services/merchant-service/internal/handler/merchant/homepage"
	merchantseckill "mymall/services/merchant-service/internal/handler/merchant/seckill"
	merchantshop "mymall/services/merchant-service/internal/handler/merchant/shop"
	merchanttheme "mymall/services/merchant-service/internal/handler/merchant/theme"
	merchantwallet "mymall/services/merchant-service/internal/handler/merchant/wallet"
	publiccoupon "mymall/services/merchant-service/internal/handler/public/coupon"
	publichealth "mymall/services/merchant-service/internal/handler/public/health"
	publicseckill "mymall/services/merchant-service/internal/handler/public/seckill"
	publicshop "mymall/services/merchant-service/internal/handler/public/shop"
	usercoupon "mymall/services/merchant-service/internal/handler/user/coupon"
	"mymall/services/merchant-service/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.RequestID, serverCtx.GatewayIdentity, serverCtx.RequirePlatformAdmin},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/admin/applications",
					Handler: adminapplication.AdminListApplicationsHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/v1/admin/applications/:id/approve",
					Handler: adminapplication.AdminApproveHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/v1/admin/applications/:id/reject",
					Handler: adminapplication.AdminRejectHandler(serverCtx),
				},
			}...,
		),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.RequestID, serverCtx.GatewayIdentity, serverCtx.RequirePlatformAdmin},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/admin/coupons",
					Handler: admincoupon.AdminListCouponsHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/v1/admin/coupons",
					Handler: admincoupon.AdminCreateCouponHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/api/v1/admin/coupons/:id",
					Handler: admincoupon.AdminUpdateCouponHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/admin/coupons/:id/claims",
					Handler: admincoupon.AdminCouponClaimsHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/v1/admin/coupons/:id/copy",
					Handler: admincoupon.AdminCopyCouponHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/api/v1/admin/coupons/:id/off",
					Handler: admincoupon.AdminOffCouponHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/admin/coupons/:id/redeems",
					Handler: admincoupon.AdminCouponRedeemsHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/admin/coupons/:id/stats",
					Handler: admincoupon.AdminCouponStatsHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/v1/admin/coupons/grant",
					Handler: admincoupon.AdminGrantCouponHandler(serverCtx),
				},
			}...,
		),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.RequestID, serverCtx.GatewayIdentity, serverCtx.RequirePlatformAdmin},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/admin/homepage-orders",
					Handler: adminhomepage.AdminListSlotOrdersHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/v1/admin/homepage-orders/grant",
					Handler: adminhomepage.AdminGrantSlotHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/admin/homepage-packages",
					Handler: adminhomepage.AdminListSlotPackagesHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/v1/admin/homepage-packages",
					Handler: adminhomepage.AdminCreateSlotPackageHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/api/v1/admin/homepage-packages/:id",
					Handler: adminhomepage.AdminUpdateSlotPackageHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/admin/homepage-settings",
					Handler: adminhomepage.AdminListSlotSettingsHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/api/v1/admin/homepage-settings",
					Handler: adminhomepage.AdminUpdateSlotSettingsHandler(serverCtx),
				},
			}...,
		),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.RequestID, serverCtx.GatewayIdentity, serverCtx.RequirePlatformAdmin},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/admin/seckill/entries",
					Handler: adminseckill.AdminListSeckillEntriesHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/admin/seckill/rule",
					Handler: adminseckill.AdminGetSeckillRuleHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/api/v1/admin/seckill/rule",
					Handler: adminseckill.AdminUpdateSeckillRuleHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/admin/seckill/sessions",
					Handler: adminseckill.AdminListSeckillSessionsHandler(serverCtx),
				},
			}...,
		),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.RequestID, serverCtx.GatewayIdentity, serverCtx.RequirePlatformAdmin},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/admin/shops",
					Handler: adminshop.AdminListShopsHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/v1/admin/shops",
					Handler: adminshop.AdminCreateShopHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/admin/shops/:id",
					Handler: adminshop.AdminGetShopHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/api/v1/admin/shops/:id",
					Handler: adminshop.AdminUpdateShopHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/api/v1/admin/shops/:id/disable",
					Handler: adminshop.AdminDisableShopHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/api/v1/admin/shops/:id/enable",
					Handler: adminshop.AdminEnableShopHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/api/v1/admin/shops/:id/owner-password",
					Handler: adminshop.AdminResetOwnerPasswordHandler(serverCtx),
				},
			}...,
		),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.RequestID, serverCtx.GatewayIdentity, serverCtx.RequirePlatformAdmin},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/admin/theme-orders",
					Handler: admintheme.AdminListThemeOrdersHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/v1/admin/theme-orders/grant",
					Handler: admintheme.AdminGrantThemeHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/admin/theme-packages",
					Handler: admintheme.AdminListThemePackagesHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/v1/admin/theme-packages",
					Handler: admintheme.AdminCreateThemePackageHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/api/v1/admin/theme-packages/:id",
					Handler: admintheme.AdminUpdateThemePackageHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/admin/theme-slots",
					Handler: admintheme.AdminListThemeSlotsHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/api/v1/admin/theme-slots/:id",
					Handler: admintheme.AdminUpdateThemeSlotHandler(serverCtx),
				},
			}...,
		),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.RequestID, serverCtx.GatewayIdentity, serverCtx.RequirePlatformAdmin},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/admin/shops/:id/wallet",
					Handler: adminwallet.AdminGetWalletHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/v1/admin/shops/:id/wallet/adjust",
					Handler: adminwallet.AdminAdjustWalletHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/admin/shops/:id/wallet/logs",
					Handler: adminwallet.AdminWalletLogsHandler(serverCtx),
				},
			}...,
		),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.RequestID},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/api/v1/internal/coupons/lock",
					Handler: internalapicoupon.InternalLockCouponHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/v1/internal/coupons/match",
					Handler: internalapicoupon.InternalMatchCouponsHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/v1/internal/coupons/order-gift",
					Handler: internalapicoupon.InternalOrderGiftHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/v1/internal/coupons/redeem",
					Handler: internalapicoupon.InternalRedeemCouponHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/v1/internal/coupons/return",
					Handler: internalapicoupon.InternalReturnCouponHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/v1/internal/coupons/unlock",
					Handler: internalapicoupon.InternalUnlockCouponHandler(serverCtx),
				},
			}...,
		),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.RequestID},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/api/v1/seckill/consume",
					Handler: internalapiseckill.SeckillConsumeHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/v1/seckill/restore",
					Handler: internalapiseckill.SeckillRestoreHandler(serverCtx),
				},
			}...,
		),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.RequestID, serverCtx.GatewayIdentity, serverCtx.RequireMerchantOwner},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/merchant/coupons",
					Handler: merchantcoupon.MerchantListCouponsHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/v1/merchant/coupons",
					Handler: merchantcoupon.MerchantCreateCouponHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/api/v1/merchant/coupons/:id",
					Handler: merchantcoupon.MerchantUpdateCouponHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/merchant/coupons/:id/claims",
					Handler: merchantcoupon.MerchantCouponClaimsHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/v1/merchant/coupons/:id/copy",
					Handler: merchantcoupon.MerchantCopyCouponHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/api/v1/merchant/coupons/:id/off",
					Handler: merchantcoupon.MerchantOffCouponHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/merchant/coupons/:id/redeems",
					Handler: merchantcoupon.MerchantCouponRedeemsHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/merchant/coupons/:id/stats",
					Handler: merchantcoupon.MerchantCouponStatsHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/v1/merchant/coupons/grant",
					Handler: merchantcoupon.MerchantGrantCouponHandler(serverCtx),
				},
			}...,
		),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.RequestID, serverCtx.GatewayIdentity, serverCtx.RequireMerchantOwner},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/api/v1/merchant/homepage-orders",
					Handler: merchanthomepage.MerchantBuySlotHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/merchant/homepage-orders",
					Handler: merchanthomepage.MerchantListSlotOrdersHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/merchant/homepage-packages",
					Handler: merchanthomepage.MerchantListSlotPackagesHandler(serverCtx),
				},
			}...,
		),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.RequestID, serverCtx.GatewayIdentity, serverCtx.RequireMerchantOwner},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/api/v1/merchant/seckill/entries",
					Handler: merchantseckill.MerchantApplySeckillHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/merchant/seckill/entries",
					Handler: merchantseckill.MerchantListSeckillEntriesHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/api/v1/merchant/seckill/entries/:id/auto-renew",
					Handler: merchantseckill.MerchantSetSeckillAutoRenewHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/merchant/seckill/sessions",
					Handler: merchantseckill.MerchantSeckillSessionsHandler(serverCtx),
				},
			}...,
		),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.RequestID, serverCtx.GatewayIdentity},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/api/v1/merchant/apply",
					Handler: merchantshop.ApplyHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/merchant/shops",
					Handler: merchantshop.MyShopsHandler(serverCtx),
				},
			}...,
		),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.RequestID, serverCtx.GatewayIdentity, serverCtx.RequireMerchantOwner},
			[]rest.Route{
				{
					Method:  http.MethodPut,
					Path:    "/api/v1/merchant/shops/:id",
					Handler: merchantshop.UpdateMyShopHandler(serverCtx),
				},
			}...,
		),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.RequestID, serverCtx.GatewayIdentity, serverCtx.RequireMerchantOwner},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/api/v1/merchant/theme-orders",
					Handler: merchanttheme.MerchantBuyThemeHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/merchant/theme-orders",
					Handler: merchanttheme.MerchantListThemeOrdersHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/merchant/theme-packages",
					Handler: merchanttheme.MerchantListThemePackagesHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/merchant/theme-slots",
					Handler: merchanttheme.MerchantListThemeSlotsHandler(serverCtx),
				},
			}...,
		),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.RequestID, serverCtx.GatewayIdentity, serverCtx.RequireMerchantOwner},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/merchant/wallet",
					Handler: merchantwallet.MerchantGetWalletHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/merchant/wallet/logs",
					Handler: merchantwallet.MerchantWalletLogsHandler(serverCtx),
				},
			}...,
		),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.RequestID},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/coupons/center",
					Handler: publiccoupon.PublicCouponCenterHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/coupons/popup",
					Handler: publiccoupon.PublicCouponPopupHandler(serverCtx),
				},
			}...,
		),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.RequestID},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/healthz",
					Handler: publichealth.HealthzHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/readyz",
					Handler: publichealth.ReadyzHandler(serverCtx),
				},
			}...,
		),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.RequestID},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/seckill/current",
					Handler: publicseckill.PublicSeckillCurrentHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/seckill/entries/:id",
					Handler: publicseckill.PublicSeckillEntryHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/seckill/list",
					Handler: publicseckill.PublicSeckillListHandler(serverCtx),
				},
			}...,
		),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.RequestID},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/home/theme-tiles",
					Handler: publicshop.PublicThemeTilesHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/shops/:id",
					Handler: publicshop.PublicGetShopHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/shops/home-slots",
					Handler: publicshop.PublicHomeSlotsHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/shops/list",
					Handler: publicshop.PublicListShopsHandler(serverCtx),
				},
			}...,
		),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.RequestID, serverCtx.GatewayIdentity},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/api/v1/coupons/:id/claim",
					Handler: usercoupon.ClaimCouponHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/user/coupons",
					Handler: usercoupon.ListMyCouponsHandler(serverCtx),
				},
			}...,
		),
	)
}
