// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5

package handler

import (
	"net/http"

	"mymall/services/catalog-service/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.RequestID},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/articles/:id",
					Handler: DetailHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/articles/:id/comments",
					Handler: ListCommentsHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/articles/list",
					Handler: ListHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/banners",
					Handler: ListBannersHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/comment-emojis",
					Handler: ListEmojisHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/product_category/detail",
					Handler: GetCategoryDetailHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/product_category/list",
					Handler: GetCategoryListHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/products/:id/favorite-count",
					Handler: CountHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/products/detail",
					Handler: GetProductDetailHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/products/list",
					Handler: GetProductListHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/products/sales-rank",
					Handler: GetSalesRankHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/healthz",
					Handler: HealthzHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/metrics",
					Handler: MetricsHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/readyz",
					Handler: ReadyzHandler(serverCtx),
				},
			}...,
		),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.RequestID, serverCtx.GatewayIdentity},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/api/v1/articles/:id/comments",
					Handler: CreateCommentHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/articles/:id/engagement",
					Handler: StatusHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/v1/articles/:id/favorite",
					Handler: FavoriteHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/api/v1/articles/:id/favorite",
					Handler: UnfavoriteHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/v1/articles/:id/like",
					Handler: LikeHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/api/v1/articles/:id/like",
					Handler: UnlikeHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/products/:id/favorite",
					Handler: Status2Handler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/user/article-favorites",
					Handler: ListMyFavoritesHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/user/article-likes",
					Handler: ListMyLikesHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/v1/user/article-uploads",
					Handler: UploadMineHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/user/articles",
					Handler: ListMineHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/v1/user/articles",
					Handler: CreateMineHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/user/articles/:id",
					Handler: DetailMineHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/api/v1/user/articles/:id",
					Handler: UpdateMineHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/api/v1/user/articles/:id",
					Handler: DeleteMineHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/v1/user/favorites",
					Handler: AddHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/user/favorites",
					Handler: List2Handler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/api/v1/user/favorites/:product_id",
					Handler: RemoveHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/v1/user/favorites/batch-remove",
					Handler: RemoveBatchHandler(serverCtx),
				},
			}...,
		),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.RequestID, serverCtx.GatewayIdentityShop, serverCtx.RequireMerchantOwner},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/merchant/article-categories",
					Handler: CategoryListHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/merchant/article-comments",
					Handler: CommentListHandler(serverCtx),
				},
				{
					Method:  http.MethodPatch,
					Path:    "/api/v1/merchant/article-comments/:id",
					Handler: CommentPatchHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/api/v1/merchant/article-comments/:id",
					Handler: CommentDeleteHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/v1/merchant/article-uploads",
					Handler: Upload2Handler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/merchant/articles",
					Handler: List4Handler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/v1/merchant/articles",
					Handler: Create2Handler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/merchant/articles/:id",
					Handler: Detail3Handler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/api/v1/merchant/articles/:id",
					Handler: Update2Handler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/api/v1/merchant/articles/:id",
					Handler: DeleteHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/merchant/attr-templates",
					Handler: ListAttrTemplatesHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/v1/merchant/attr-templates",
					Handler: SaveAttrTemplateHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/api/v1/merchant/attr-templates/:id",
					Handler: SaveAttrTemplate2Handler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/api/v1/merchant/attr-templates/:id",
					Handler: DeleteAttrTemplateHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/merchant/auth/me",
					Handler: AuthMeHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/merchant/notifications",
					Handler: List5Handler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/v1/merchant/notifications/:id/read",
					Handler: MarkReadHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/v1/merchant/notifications/read-all",
					Handler: MarkAllReadHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/merchant/notifications/unread-count",
					Handler: UnreadCountHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/merchant/products",
					Handler: List3Handler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/v1/merchant/products",
					Handler: CreateHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/merchant/products/:id",
					Handler: Detail2Handler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/api/v1/merchant/products/:id",
					Handler: UpdateHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/v1/merchant/products/:id/copy",
					Handler: CopyHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/v1/merchant/products/:id/schedules",
					Handler: ScheduleHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/api/v1/merchant/products/:id/status",
					Handler: SetStatusHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/v1/merchant/products/batch",
					Handler: BatchHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/merchant/products/export",
					Handler: ExportHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/v1/merchant/products/import",
					Handler: ImportHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/merchant/products/jobs/:id",
					Handler: JobStatusHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/merchant/products/op-logs",
					Handler: OpLogsHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/api/v1/merchant/products/recycle",
					Handler: RecycleDeleteHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/v1/merchant/products/recycle/restore",
					Handler: RecycleRestoreHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/api/v1/merchant/schedules/:id",
					Handler: CancelScheduleHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/merchant/shop/menus",
					Handler: ListMenusHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/merchant/shop/roles",
					Handler: ListRolesHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/v1/merchant/shop/roles",
					Handler: SaveRoleHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/api/v1/merchant/shop/roles/:id",
					Handler: SaveRole2Handler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/merchant/shop/roles/:id/menus",
					Handler: RoleMenusHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/merchant/shop/staff",
					Handler: ListStaffHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/v1/merchant/shop/staff",
					Handler: BindStaffHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/api/v1/merchant/skus/:id/stock",
					Handler: AdjustStockHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/v1/merchant/skus/batch-stock",
					Handler: BatchStockHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/merchant/stocks/warnings",
					Handler: StockWarningsHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/merchant/tags",
					Handler: ListTagsHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/v1/merchant/tags",
					Handler: SaveTagHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/api/v1/merchant/tags/:id",
					Handler: SaveTag2Handler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/api/v1/merchant/tags/:id",
					Handler: DeleteTagHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/v1/merchant/uploads/images",
					Handler: UploadHandler(serverCtx),
				},
			}...,
		),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.RequestID, serverCtx.GatewayIdentity, serverCtx.RequirePlatformAdmin},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/admin/article-categories",
					Handler: CategoryList2Handler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/v1/admin/article-categories",
					Handler: CategoryCreateHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/api/v1/admin/article-categories/:id",
					Handler: CategoryUpdateHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/api/v1/admin/article-categories/:id",
					Handler: CategoryDeleteHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/admin/article-comments",
					Handler: CommentList2Handler(serverCtx),
				},
				{
					Method:  http.MethodPatch,
					Path:    "/api/v1/admin/article-comments/:id",
					Handler: CommentPatch2Handler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/api/v1/admin/article-comments/:id",
					Handler: CommentDelete2Handler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/v1/admin/article-uploads",
					Handler: Upload3Handler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/admin/articles",
					Handler: List8Handler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/v1/admin/articles",
					Handler: Create3Handler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/admin/articles/:id",
					Handler: Detail4Handler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/api/v1/admin/articles/:id",
					Handler: Update3Handler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/api/v1/admin/articles/:id",
					Handler: SoftDeleteHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/v1/admin/articles/:id/audit",
					Handler: AuditHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/v1/admin/articles/:id/offline",
					Handler: OfflineHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/v1/admin/articles/:id/top",
					Handler: TopHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/v1/admin/articles/batch-audit",
					Handler: BatchAuditHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/admin/articles/recycle",
					Handler: List7Handler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/api/v1/admin/articles/recycle",
					Handler: RecycleDelete2Handler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/v1/admin/articles/recycle/restore",
					Handler: RecycleRestore2Handler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/admin/articles/stats",
					Handler: StatsHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/admin/banners",
					Handler: ListBanners2Handler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/v1/admin/banners",
					Handler: CreateBannerHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/admin/banners/:id",
					Handler: GetBannerHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/api/v1/admin/banners/:id",
					Handler: UpdateBannerHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/api/v1/admin/banners/:id",
					Handler: DeleteBannerHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/v1/admin/banners/upload",
					Handler: UploadBannerHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/admin/categories",
					Handler: AdminListCategoriesHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/v1/admin/categories",
					Handler: AdminCreateCategoryHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/api/v1/admin/categories/:id",
					Handler: AdminUpdateCategoryHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/api/v1/admin/categories/:id",
					Handler: AdminDeleteCategoryHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/admin/comment-emojis",
					Handler: EmojiListHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/v1/admin/comment-emojis",
					Handler: EmojiCreateHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/api/v1/admin/comment-emojis/:id",
					Handler: EmojiUpdateHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/api/v1/admin/comment-emojis/:id",
					Handler: EmojiDeleteHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/admin/products",
					Handler: List6Handler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/api/v1/admin/products/:id",
					Handler: Delete2Handler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/api/v1/admin/products/:id/off_sale",
					Handler: OffSaleHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/v1/admin/shop-uploads",
					Handler: Upload4Handler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/admin/users/:id/favorites",
					Handler: AdminUserListHandler(serverCtx),
				},
			}...,
		),
	)
}
