// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5

package handler

import (
	"net/http"

	adminarticle "mymall/services/catalog-service/internal/handler/admin/article"
	adminbanner "mymall/services/catalog-service/internal/handler/admin/banner"
	admincategory "mymall/services/catalog-service/internal/handler/admin/category"
	admincomment "mymall/services/catalog-service/internal/handler/admin/comment"
	adminproduct "mymall/services/catalog-service/internal/handler/admin/product"
	adminshop "mymall/services/catalog-service/internal/handler/admin/shop"
	adminuser_favorite "mymall/services/catalog-service/internal/handler/admin/user_favorite"
	merchantarticle "mymall/services/catalog-service/internal/handler/merchant/article"
	merchantnotification "mymall/services/catalog-service/internal/handler/merchant/notification"
	merchantproduct "mymall/services/catalog-service/internal/handler/merchant/product"
	merchantshopops "mymall/services/catalog-service/internal/handler/merchant/shopops"
	publicarticle "mymall/services/catalog-service/internal/handler/public/article"
	publicbanner "mymall/services/catalog-service/internal/handler/public/banner"
	publiccategory "mymall/services/catalog-service/internal/handler/public/category"
	publichealth "mymall/services/catalog-service/internal/handler/public/health"
	publicproduct "mymall/services/catalog-service/internal/handler/public/product"
	userarticle "mymall/services/catalog-service/internal/handler/user/article"
	userfavorite "mymall/services/catalog-service/internal/handler/user/favorite"
	"mymall/services/catalog-service/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.RequestID, serverCtx.GatewayIdentity, serverCtx.RequirePlatformAdmin},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/admin/article-categories",
					Handler: adminarticle.AdminListArticleCategoriesHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/v1/admin/article-categories",
					Handler: adminarticle.AdminCreateArticleCategoryHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/api/v1/admin/article-categories/:id",
					Handler: adminarticle.AdminUpdateArticleCategoryHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/api/v1/admin/article-categories/:id",
					Handler: adminarticle.AdminDeleteArticleCategoryHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/v1/admin/article-uploads",
					Handler: adminarticle.AdminUploadArticleHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/admin/articles",
					Handler: adminarticle.AdminListArticlesHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/v1/admin/articles",
					Handler: adminarticle.AdminCreateArticleHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/admin/articles/:id",
					Handler: adminarticle.AdminGetArticleHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/api/v1/admin/articles/:id",
					Handler: adminarticle.AdminUpdateArticleHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/api/v1/admin/articles/:id",
					Handler: adminarticle.AdminSoftDeleteArticleHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/v1/admin/articles/:id/audit",
					Handler: adminarticle.AdminAuditArticleHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/v1/admin/articles/:id/offline",
					Handler: adminarticle.AdminOfflineArticleHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/v1/admin/articles/:id/top",
					Handler: adminarticle.AdminTopArticleHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/v1/admin/articles/batch-audit",
					Handler: adminarticle.AdminBatchAuditArticlesHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/admin/articles/recycle",
					Handler: adminarticle.AdminListArticleRecycleHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/api/v1/admin/articles/recycle",
					Handler: adminarticle.AdminPurgeArticleRecycleHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/v1/admin/articles/recycle/restore",
					Handler: adminarticle.AdminRestoreArticleRecycleHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/admin/articles/stats",
					Handler: adminarticle.AdminArticleStatsHandler(serverCtx),
				},
			}...,
		),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.RequestID, serverCtx.GatewayIdentity, serverCtx.RequirePlatformAdmin},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/admin/banners",
					Handler: adminbanner.AdminListBannersHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/v1/admin/banners",
					Handler: adminbanner.CreateBannerHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/admin/banners/:id",
					Handler: adminbanner.GetBannerHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/api/v1/admin/banners/:id",
					Handler: adminbanner.UpdateBannerHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/api/v1/admin/banners/:id",
					Handler: adminbanner.DeleteBannerHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/v1/admin/banners/upload",
					Handler: adminbanner.UploadBannerHandler(serverCtx),
				},
			}...,
		),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.RequestID, serverCtx.GatewayIdentity, serverCtx.RequirePlatformAdmin},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/admin/categories",
					Handler: admincategory.AdminListCategoriesHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/v1/admin/categories",
					Handler: admincategory.AdminCreateCategoryHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/api/v1/admin/categories/:id",
					Handler: admincategory.AdminUpdateCategoryHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/api/v1/admin/categories/:id",
					Handler: admincategory.AdminDeleteCategoryHandler(serverCtx),
				},
			}...,
		),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.RequestID, serverCtx.GatewayIdentity, serverCtx.RequirePlatformAdmin},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/admin/article-comments",
					Handler: admincomment.AdminListArticleCommentsHandler(serverCtx),
				},
				{
					Method:  http.MethodPatch,
					Path:    "/api/v1/admin/article-comments/:id",
					Handler: admincomment.AdminPatchArticleCommentHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/api/v1/admin/article-comments/:id",
					Handler: admincomment.AdminDeleteArticleCommentHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/admin/comment-emojis",
					Handler: admincomment.EmojiListHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/v1/admin/comment-emojis",
					Handler: admincomment.EmojiCreateHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/api/v1/admin/comment-emojis/:id",
					Handler: admincomment.EmojiUpdateHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/api/v1/admin/comment-emojis/:id",
					Handler: admincomment.EmojiDeleteHandler(serverCtx),
				},
			}...,
		),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.RequestID, serverCtx.GatewayIdentity, serverCtx.RequirePlatformAdmin},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/admin/products",
					Handler: adminproduct.AdminListProductsHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/api/v1/admin/products/:id",
					Handler: adminproduct.AdminDeleteProductHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/api/v1/admin/products/:id/off_sale",
					Handler: adminproduct.AdminOffSaleProductHandler(serverCtx),
				},
			}...,
		),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.RequestID, serverCtx.GatewayIdentity, serverCtx.RequirePlatformAdmin},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/api/v1/admin/shop-uploads",
					Handler: adminshop.AdminUploadShopHandler(serverCtx),
				},
			}...,
		),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.RequestID, serverCtx.GatewayIdentity, serverCtx.RequirePlatformAdmin},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/admin/users/:id/favorites",
					Handler: adminuser_favorite.AdminListUserFavoritesHandler(serverCtx),
				},
			}...,
		),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.RequestID, serverCtx.GatewayIdentityShop, serverCtx.RequireMerchantOwner},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/merchant/article-categories",
					Handler: merchantarticle.MerchantListArticleCategoriesHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/merchant/article-comments",
					Handler: merchantarticle.MerchantListArticleCommentsHandler(serverCtx),
				},
				{
					Method:  http.MethodPatch,
					Path:    "/api/v1/merchant/article-comments/:id",
					Handler: merchantarticle.MerchantPatchArticleCommentHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/api/v1/merchant/article-comments/:id",
					Handler: merchantarticle.MerchantDeleteArticleCommentHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/v1/merchant/article-uploads",
					Handler: merchantarticle.MerchantUploadArticleHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/merchant/articles",
					Handler: merchantarticle.MerchantListArticlesHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/v1/merchant/articles",
					Handler: merchantarticle.MerchantCreateArticleHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/merchant/articles/:id",
					Handler: merchantarticle.MerchantGetArticleHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/api/v1/merchant/articles/:id",
					Handler: merchantarticle.MerchantUpdateArticleHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/api/v1/merchant/articles/:id",
					Handler: merchantarticle.MerchantDeleteArticleHandler(serverCtx),
				},
			}...,
		),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.RequestID, serverCtx.GatewayIdentityShop, serverCtx.RequireMerchantOwner},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/merchant/notifications",
					Handler: merchantnotification.MerchantListNotificationsHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/v1/merchant/notifications/:id/read",
					Handler: merchantnotification.MerchantMarkNotificationReadHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/v1/merchant/notifications/read-all",
					Handler: merchantnotification.MerchantMarkAllNotificationsReadHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/merchant/notifications/unread-count",
					Handler: merchantnotification.MerchantUnreadNotificationCountHandler(serverCtx),
				},
			}...,
		),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.RequestID, serverCtx.GatewayIdentityShop, serverCtx.RequireMerchantOwner},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/merchant/attr-templates",
					Handler: merchantproduct.ListAttrTemplatesHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/v1/merchant/attr-templates",
					Handler: merchantproduct.MerchantCreateAttrTemplateHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/api/v1/merchant/attr-templates/:id",
					Handler: merchantproduct.MerchantUpdateAttrTemplateHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/api/v1/merchant/attr-templates/:id",
					Handler: merchantproduct.DeleteAttrTemplateHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/merchant/products",
					Handler: merchantproduct.MerchantListProductsHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/v1/merchant/products",
					Handler: merchantproduct.MerchantCreateProductHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/merchant/products/:id",
					Handler: merchantproduct.MerchantGetProductHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/api/v1/merchant/products/:id",
					Handler: merchantproduct.MerchantUpdateProductHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/v1/merchant/products/:id/copy",
					Handler: merchantproduct.MerchantCopyProductHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/v1/merchant/products/:id/schedules",
					Handler: merchantproduct.MerchantScheduleProductHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/api/v1/merchant/products/:id/status",
					Handler: merchantproduct.MerchantSetProductStatusHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/v1/merchant/products/batch",
					Handler: merchantproduct.MerchantBatchProductsHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/merchant/products/export",
					Handler: merchantproduct.MerchantExportProductsHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/v1/merchant/products/import",
					Handler: merchantproduct.MerchantImportProductsHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/merchant/products/jobs/:id",
					Handler: merchantproduct.JobStatusHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/merchant/products/op-logs",
					Handler: merchantproduct.OpLogsHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/api/v1/merchant/products/recycle",
					Handler: merchantproduct.MerchantPurgeProductsHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/v1/merchant/products/recycle/restore",
					Handler: merchantproduct.MerchantRestoreProductsHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/api/v1/merchant/schedules/:id",
					Handler: merchantproduct.CancelScheduleHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/api/v1/merchant/skus/:id/stock",
					Handler: merchantproduct.AdjustStockHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/v1/merchant/skus/batch-stock",
					Handler: merchantproduct.BatchStockHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/merchant/stocks/warnings",
					Handler: merchantproduct.StockWarningsHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/merchant/tags",
					Handler: merchantproduct.ListTagsHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/v1/merchant/tags",
					Handler: merchantproduct.MerchantCreateTagHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/api/v1/merchant/tags/:id",
					Handler: merchantproduct.MerchantUpdateTagHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/api/v1/merchant/tags/:id",
					Handler: merchantproduct.DeleteTagHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/v1/merchant/uploads/images",
					Handler: merchantproduct.MerchantUploadImageHandler(serverCtx),
				},
			}...,
		),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.RequestID, serverCtx.GatewayIdentityShop, serverCtx.RequireMerchantOwner},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/merchant/auth/me",
					Handler: merchantshopops.MerchantAuthMeHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/merchant/shop/menus",
					Handler: merchantshopops.ListMenusHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/merchant/shop/roles",
					Handler: merchantshopops.ListRolesHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/v1/merchant/shop/roles",
					Handler: merchantshopops.MerchantCreateRoleHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/api/v1/merchant/shop/roles/:id",
					Handler: merchantshopops.MerchantUpdateRoleHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/merchant/shop/roles/:id/menus",
					Handler: merchantshopops.RoleMenusHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/merchant/shop/staff",
					Handler: merchantshopops.ListStaffHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/v1/merchant/shop/staff",
					Handler: merchantshopops.BindStaffHandler(serverCtx),
				},
			}...,
		),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.RequestID},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/articles/:id",
					Handler: publicarticle.PublicGetArticleHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/articles/:id/comments",
					Handler: publicarticle.ListCommentsHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/articles/list",
					Handler: publicarticle.PublicListArticlesHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/comment-emojis",
					Handler: publicarticle.ListEmojisHandler(serverCtx),
				},
			}...,
		),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.RequestID},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/banners",
					Handler: publicbanner.ListBannersHandler(serverCtx),
				},
			}...,
		),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.RequestID},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/product_category/detail",
					Handler: publiccategory.GetCategoryDetailHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/product_category/list",
					Handler: publiccategory.GetCategoryListHandler(serverCtx),
				},
			}...,
		),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.RequestID},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/healthz",
					Handler: publichealth.HealthzHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/metrics",
					Handler: publichealth.MetricsHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/readyz",
					Handler: publichealth.ReadyzHandler(serverCtx),
				},
			}...,
		),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.RequestID},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/products/:id/favorite-count",
					Handler: publicproduct.CountHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/products/detail",
					Handler: publicproduct.GetProductDetailHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/products/list",
					Handler: publicproduct.GetProductListHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/products/sales-rank",
					Handler: publicproduct.GetSalesRankHandler(serverCtx),
				},
			}...,
		),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.RequestID, serverCtx.GatewayIdentity},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/api/v1/articles/:id/comments",
					Handler: userarticle.CreateCommentHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/articles/:id/engagement",
					Handler: userarticle.UserArticleEngagementHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/v1/articles/:id/favorite",
					Handler: userarticle.FavoriteHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/api/v1/articles/:id/favorite",
					Handler: userarticle.UnfavoriteHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/v1/articles/:id/like",
					Handler: userarticle.LikeHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/api/v1/articles/:id/like",
					Handler: userarticle.UnlikeHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/user/article-favorites",
					Handler: userarticle.ListMyFavoritesHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/user/article-likes",
					Handler: userarticle.ListMyLikesHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/v1/user/article-uploads",
					Handler: userarticle.UploadMineHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/user/articles",
					Handler: userarticle.ListMineHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/v1/user/articles",
					Handler: userarticle.CreateMineHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/user/articles/:id",
					Handler: userarticle.DetailMineHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/api/v1/user/articles/:id",
					Handler: userarticle.UpdateMineHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/api/v1/user/articles/:id",
					Handler: userarticle.DeleteMineHandler(serverCtx),
				},
			}...,
		),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.RequestID, serverCtx.GatewayIdentity},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/products/:id/favorite",
					Handler: userfavorite.UserFavoriteStatusHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/v1/user/favorites",
					Handler: userfavorite.UserAddFavoriteHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/user/favorites",
					Handler: userfavorite.UserListFavoritesHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/api/v1/user/favorites/:product_id",
					Handler: userfavorite.UserRemoveFavoriteHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/v1/user/favorites/batch-remove",
					Handler: userfavorite.RemoveBatchHandler(serverCtx),
				},
			}...,
		),
	)
}
