// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package types

type AnyResp struct {
	Data interface{} `json:"data,optional"`
}

// DataResp is the preferred name for opaque entity JSON bodies.
type DataResp = AnyResp

type CodePathReq struct {
	Code string `path:"code"`
}

type CouponPreviewReq struct {
	Items        []CreateOrderItem `json:"items"`
	UserCouponID uint64            `json:"user_coupon_id,optional"`
}

type CouponPreviewResp struct {
	GoodsAmount      float64     `json:"goods_amount"`
	DiscountAmount   float64     `json:"discount_amount"`
	PayAmount        float64     `json:"pay_amount"`
	BestUserCouponID uint64      `json:"best_user_coupon_id"`
	Available        interface{} `json:"available"`
	Unavailable      interface{} `json:"unavailable"`
}

type CreateAfterSaleBodyReq struct {
	Id     uint64  `path:"id"`
	Type   string  `json:"type"`
	Reason string  `json:"reason"`
	Amount float64 `json:"amount"`
}

type CreateOrderItem struct {
	ProductID      uint64 `json:"product_id"`
	SkuID          uint64 `json:"sku_id"`
	SkuSnapshot    string `json:"sku_snapshot,optional"`
	Quantity       int    `json:"quantity"`
	SeckillEntryID uint64 `json:"seckill_entry_id,optional"`
}

type CreateOrderReq struct {
	AddressID    uint64            `json:"address_id"`
	Items        []CreateOrderItem `json:"items"`
	UserCouponID uint64            `json:"user_coupon_id,optional"`
}

type CreateReviewBodyReq struct {
	Id          uint64   `path:"id"`
	Rating      int8     `json:"rating"`
	Content     string   `json:"content,optional"`
	IsAnonymous bool     `json:"is_anonymous,optional"`
	OrderItemID uint64   `json:"order_item_id,optional"`
	Images      []string `json:"images,optional"`
}

type EmptyResp struct {
}

type FilePathReq struct {
	File string `path:"file"`
}

type HandleAfterSaleBodyReq struct {
	Id          uint64 `path:"id"`
	Action      string `json:"action"`
	AdminRemark string `json:"admin_remark,optional"`
}

type IdPathReq struct {
	Id uint64 `path:"id"`
}

type ListResp struct {
	List interface{} `json:"list"`
}

type LogisticsSaveBodyReq struct {
	Name   string `json:"name"`
	Code   string `json:"code"`
	Sort   int    `json:"sort,optional"`
	Status int    `json:"status,optional"`
}

type LogisticsStatusBodyReq struct {
	Id     uint64 `path:"id"`
	Status int8   `json:"status"`
}

type LogisticsUpdateBodyReq struct {
	Id     uint64 `path:"id"`
	Name   string `json:"name"`
	Code   string `json:"code"`
	Sort   int    `json:"sort,optional"`
	Status int    `json:"status,optional"`
}

type OrderDetailResp struct {
	Order      interface{} `json:"order"`
	AfterSales interface{} `json:"after_sales"`
}

type OrderStatusCountsResp struct {
	Counts map[string]int64 `json:"counts"`
}

type PageListResp struct {
	Total int64       `json:"total"`
	List  interface{} `json:"list"`
}

type PageReq struct {
	Page     int    `form:"page,default=1"`
	PageSize int    `form:"page_size,default=10"`
	Status   string `form:"status,optional"`
}

type RemarkBodyReq struct {
	Id     uint64 `path:"id"`
	Remark string `json:"remark"`
}

type ReviewEligibleResp struct {
	Eligible bool   `json:"eligible"`
	Reviewed bool   `json:"reviewed"`
	Status   string `json:"status"`
	OrderId  uint64 `json:"order_id"`
}

type ReviewReplyBodyReq struct {
	Id    uint64 `path:"id"`
	Reply string `json:"reply"`
}

type ShipBodyReq struct {
	Id          uint64 `path:"id"`
	ShipCompany string `json:"ship_company"`
	ShipNo      string `json:"ship_no"`
}

type URLResp struct {
	Url string `json:"url"`
}
