// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5
// Source: merchant.proto

package server

import (
	"context"

	rpclogic "mymall/services/merchant-service/internal/rpclogic"
	"mymall/services/merchant-service/internal/svc"
	merchantv1 "mymall/api/gen/merchant/v1"
)

type MerchantServiceServer struct {
	svcCtx *svc.ServiceContext
	merchantv1.UnimplementedMerchantServiceServer
}

func NewMerchantServiceServer(svcCtx *svc.ServiceContext) *MerchantServiceServer {
	return &MerchantServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *MerchantServiceServer) ConsumeSeckill(ctx context.Context, in *merchantv1.ConsumeSeckillRequest) (*merchantv1.ConsumeSeckillResponse, error) {
	l := rpclogic.NewConsumeSeckillLogic(ctx, s.svcCtx)
	return l.ConsumeSeckill(in)
}

func (s *MerchantServiceServer) RestoreSeckill(ctx context.Context, in *merchantv1.RestoreSeckillRequest) (*merchantv1.EmptyResponse, error) {
	l := rpclogic.NewRestoreSeckillLogic(ctx, s.svcCtx)
	return l.RestoreSeckill(in)
}

func (s *MerchantServiceServer) MatchCoupons(ctx context.Context, in *merchantv1.MatchCouponsRequest) (*merchantv1.MatchCouponsResponse, error) {
	l := rpclogic.NewMatchCouponsLogic(ctx, s.svcCtx)
	return l.MatchCoupons(in)
}

func (s *MerchantServiceServer) LockCoupon(ctx context.Context, in *merchantv1.LockCouponRequest) (*merchantv1.EmptyResponse, error) {
	l := rpclogic.NewLockCouponLogic(ctx, s.svcCtx)
	return l.LockCoupon(in)
}

func (s *MerchantServiceServer) UnlockCoupon(ctx context.Context, in *merchantv1.UnlockCouponRequest) (*merchantv1.EmptyResponse, error) {
	l := rpclogic.NewUnlockCouponLogic(ctx, s.svcCtx)
	return l.UnlockCoupon(in)
}

func (s *MerchantServiceServer) RedeemCoupon(ctx context.Context, in *merchantv1.RedeemCouponRequest) (*merchantv1.EmptyResponse, error) {
	l := rpclogic.NewRedeemCouponLogic(ctx, s.svcCtx)
	return l.RedeemCoupon(in)
}

func (s *MerchantServiceServer) ReturnCoupon(ctx context.Context, in *merchantv1.ReturnCouponRequest) (*merchantv1.EmptyResponse, error) {
	l := rpclogic.NewReturnCouponLogic(ctx, s.svcCtx)
	return l.ReturnCoupon(in)
}

func (s *MerchantServiceServer) OrderGiftCoupons(ctx context.Context, in *merchantv1.OrderGiftCouponsRequest) (*merchantv1.OrderGiftCouponsResponse, error) {
	l := rpclogic.NewOrderGiftCouponsLogic(ctx, s.svcCtx)
	return l.OrderGiftCoupons(in)
}
