// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.8.5

package modelgen

import (
	"mymall/common"
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	articleFavoritesFieldNames          = builder.RawFieldNames(&ArticleFavorite{})
	articleFavoritesRows                = strings.Join(articleFavoritesFieldNames, ",")
	articleFavoritesRowsExpectAutoSet   = strings.Join(stringx.Remove(articleFavoritesFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	articleFavoritesRowsWithPlaceHolder = strings.Join(stringx.Remove(articleFavoritesFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	articleFavoritesModel interface {
		Insert(ctx context.Context, data *ArticleFavorite) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*ArticleFavorite, error)
		FindOneByUserIdArticleId(ctx context.Context, userId uint64, articleId uint64) (*ArticleFavorite, error)
		Update(ctx context.Context, data *ArticleFavorite) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultArticleFavoritesModel struct {
		conn  sqlx.SqlConn
		table string
	}

	ArticleFavorite struct {
		ID        uint64    `db:"id"`
		UserID    uint64    `db:"user_id"`
		ArticleID uint64    `db:"article_id"`
		CreatedAt common.LocalTime `db:"created_at"`
	}
)

func newArticleFavoritesModel(conn sqlx.SqlConn) *defaultArticleFavoritesModel {
	return &defaultArticleFavoritesModel{
		conn:  conn,
		table: "`article_favorites`",
	}
}

func (m *defaultArticleFavoritesModel) Delete(ctx context.Context, id uint64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultArticleFavoritesModel) FindOne(ctx context.Context, id uint64) (*ArticleFavorite, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", articleFavoritesRows, m.table)
	var resp ArticleFavorite
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultArticleFavoritesModel) FindOneByUserIdArticleId(ctx context.Context, userId uint64, articleId uint64) (*ArticleFavorite, error) {
	var resp ArticleFavorite
	query := fmt.Sprintf("select %s from %s where `user_id` = ? and `article_id` = ? limit 1", articleFavoritesRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, userId, articleId)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultArticleFavoritesModel) Insert(ctx context.Context, data *ArticleFavorite) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?)", m.table, articleFavoritesRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.UserID, data.ArticleID)
	return ret, err
}

func (m *defaultArticleFavoritesModel) Update(ctx context.Context, newData *ArticleFavorite) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, articleFavoritesRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.UserID, newData.ArticleID, newData.ID)
	return err
}

func (m *defaultArticleFavoritesModel) tableName() string {
	return m.table
}
