// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.8.5

package modelgen

import (
	"mymall/common"
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	articleLikesFieldNames          = builder.RawFieldNames(&ArticleLike{})
	articleLikesRows                = strings.Join(articleLikesFieldNames, ",")
	articleLikesRowsExpectAutoSet   = strings.Join(stringx.Remove(articleLikesFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	articleLikesRowsWithPlaceHolder = strings.Join(stringx.Remove(articleLikesFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	articleLikesModel interface {
		Insert(ctx context.Context, data *ArticleLike) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*ArticleLike, error)
		FindOneByUserIdArticleId(ctx context.Context, userId uint64, articleId uint64) (*ArticleLike, error)
		Update(ctx context.Context, data *ArticleLike) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultArticleLikesModel struct {
		conn  sqlx.SqlConn
		table string
	}

	ArticleLike struct {
		ID        uint64    `db:"id"`
		UserID    uint64    `db:"user_id"`
		ArticleID uint64    `db:"article_id"`
		CreatedAt common.LocalTime `db:"created_at"`
	}
)

func newArticleLikesModel(conn sqlx.SqlConn) *defaultArticleLikesModel {
	return &defaultArticleLikesModel{
		conn:  conn,
		table: "`article_likes`",
	}
}

func (m *defaultArticleLikesModel) Delete(ctx context.Context, id uint64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultArticleLikesModel) FindOne(ctx context.Context, id uint64) (*ArticleLike, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", articleLikesRows, m.table)
	var resp ArticleLike
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultArticleLikesModel) FindOneByUserIdArticleId(ctx context.Context, userId uint64, articleId uint64) (*ArticleLike, error) {
	var resp ArticleLike
	query := fmt.Sprintf("select %s from %s where `user_id` = ? and `article_id` = ? limit 1", articleLikesRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, userId, articleId)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultArticleLikesModel) Insert(ctx context.Context, data *ArticleLike) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?)", m.table, articleLikesRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.UserID, data.ArticleID)
	return ret, err
}

func (m *defaultArticleLikesModel) Update(ctx context.Context, newData *ArticleLike) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, articleLikesRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.UserID, newData.ArticleID, newData.ID)
	return err
}

func (m *defaultArticleLikesModel) tableName() string {
	return m.table
}
