// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.8.5

package modelgen

import (
	"mymall/common"
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	articleAudiencesFieldNames          = builder.RawFieldNames(&ArticleAudience{})
	articleAudiencesRows                = strings.Join(articleAudiencesFieldNames, ",")
	articleAudiencesRowsExpectAutoSet   = strings.Join(stringx.Remove(articleAudiencesFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	articleAudiencesRowsWithPlaceHolder = strings.Join(stringx.Remove(articleAudiencesFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	articleAudiencesModel interface {
		Insert(ctx context.Context, data *ArticleAudience) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*ArticleAudience, error)
		FindOneByUserIdArticleId(ctx context.Context, userId uint64, articleId uint64) (*ArticleAudience, error)
		Update(ctx context.Context, data *ArticleAudience) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultArticleAudiencesModel struct {
		conn  sqlx.SqlConn
		table string
	}

	ArticleAudience struct {
		ID        uint64    `db:"id"`
		UserID    uint64    `db:"user_id"`
		ArticleID uint64    `db:"article_id"`
		CreatedAt common.LocalTime `db:"created_at"`
	}
)

func newArticleAudiencesModel(conn sqlx.SqlConn) *defaultArticleAudiencesModel {
	return &defaultArticleAudiencesModel{
		conn:  conn,
		table: "`article_audiences`",
	}
}

func (m *defaultArticleAudiencesModel) Delete(ctx context.Context, id uint64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultArticleAudiencesModel) FindOne(ctx context.Context, id uint64) (*ArticleAudience, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", articleAudiencesRows, m.table)
	var resp ArticleAudience
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultArticleAudiencesModel) FindOneByUserIdArticleId(ctx context.Context, userId uint64, articleId uint64) (*ArticleAudience, error) {
	var resp ArticleAudience
	query := fmt.Sprintf("select %s from %s where `user_id` = ? and `article_id` = ? limit 1", articleAudiencesRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, userId, articleId)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultArticleAudiencesModel) Insert(ctx context.Context, data *ArticleAudience) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?)", m.table, articleAudiencesRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.UserID, data.ArticleID)
	return ret, err
}

func (m *defaultArticleAudiencesModel) Update(ctx context.Context, newData *ArticleAudience) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, articleAudiencesRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.UserID, newData.ArticleID, newData.ID)
	return err
}

func (m *defaultArticleAudiencesModel) tableName() string {
	return m.table
}
