// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.8.5

package modelgen

import (
	"mymall/common"
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	communityArticleCategoryFieldNames          = builder.RawFieldNames(&CommunityArticleCategory{})
	communityArticleCategoryRows                = strings.Join(communityArticleCategoryFieldNames, ",")
	communityArticleCategoryRowsExpectAutoSet   = strings.Join(stringx.Remove(communityArticleCategoryFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	communityArticleCategoryRowsWithPlaceHolder = strings.Join(stringx.Remove(communityArticleCategoryFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	communityArticleCategoryModel interface {
		Insert(ctx context.Context, data *CommunityArticleCategory) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*CommunityArticleCategory, error)
		Update(ctx context.Context, data *CommunityArticleCategory) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultCommunityArticleCategoryModel struct {
		conn  sqlx.SqlConn
		table string
	}

	CommunityArticleCategory struct {
		ID        uint64    `db:"id"`
		ParentID  uint64    `db:"parent_id"`
		Name      string    `db:"name"`
		Sort      int     `db:"sort"`
		Status    int     `db:"status"`
		CreatedAt common.LocalTime `db:"created_at"`
		UpdatedAt common.LocalTime `db:"updated_at"`
	}
)

func newCommunityArticleCategoryModel(conn sqlx.SqlConn) *defaultCommunityArticleCategoryModel {
	return &defaultCommunityArticleCategoryModel{
		conn:  conn,
		table: "`community_article_category`",
	}
}

func (m *defaultCommunityArticleCategoryModel) Delete(ctx context.Context, id uint64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultCommunityArticleCategoryModel) FindOne(ctx context.Context, id uint64) (*CommunityArticleCategory, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", communityArticleCategoryRows, m.table)
	var resp CommunityArticleCategory
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultCommunityArticleCategoryModel) Insert(ctx context.Context, data *CommunityArticleCategory) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?)", m.table, communityArticleCategoryRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.ParentID, data.Name, data.Sort, data.Status)
	return ret, err
}

func (m *defaultCommunityArticleCategoryModel) Update(ctx context.Context, data *CommunityArticleCategory) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, communityArticleCategoryRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.ParentID, data.Name, data.Sort, data.Status, data.ID)
	return err
}

func (m *defaultCommunityArticleCategoryModel) tableName() string {
	return m.table
}
