// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.8.5

package modelgen

import (
	"mymall/common"
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	communityArticleCommentFieldNames          = builder.RawFieldNames(&CommunityArticleComment{})
	communityArticleCommentRows                = strings.Join(communityArticleCommentFieldNames, ",")
	communityArticleCommentRowsExpectAutoSet   = strings.Join(stringx.Remove(communityArticleCommentFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	communityArticleCommentRowsWithPlaceHolder = strings.Join(stringx.Remove(communityArticleCommentFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	communityArticleCommentModel interface {
		Insert(ctx context.Context, data *CommunityArticleComment) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*CommunityArticleComment, error)
		Update(ctx context.Context, data *CommunityArticleComment) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultCommunityArticleCommentModel struct {
		conn  sqlx.SqlConn
		table string
	}

	CommunityArticleComment struct {
		ID        uint64    `db:"id"`
		ArticleID uint64    `db:"article_id"`
		ShopID    uint64    `db:"shop_id"`
		UserID    uint64    `db:"user_id"`
		Content   string    `db:"content"`
		Status    string    `db:"status"`
		CreatedAt common.LocalTime `db:"created_at"`
		UpdatedAt common.LocalTime `db:"updated_at"`
	}
)

func newCommunityArticleCommentModel(conn sqlx.SqlConn) *defaultCommunityArticleCommentModel {
	return &defaultCommunityArticleCommentModel{
		conn:  conn,
		table: "`community_article_comment`",
	}
}

func (m *defaultCommunityArticleCommentModel) Delete(ctx context.Context, id uint64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultCommunityArticleCommentModel) FindOne(ctx context.Context, id uint64) (*CommunityArticleComment, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", communityArticleCommentRows, m.table)
	var resp CommunityArticleComment
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultCommunityArticleCommentModel) Insert(ctx context.Context, data *CommunityArticleComment) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?)", m.table, communityArticleCommentRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.ArticleID, data.ShopID, data.UserID, data.Content, data.Status)
	return ret, err
}

func (m *defaultCommunityArticleCommentModel) Update(ctx context.Context, data *CommunityArticleComment) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, communityArticleCommentRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.ArticleID, data.ShopID, data.UserID, data.Content, data.Status, data.ID)
	return err
}

func (m *defaultCommunityArticleCommentModel) tableName() string {
	return m.table
}
