// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.8.5

package modelgen

import (
	"mymall/common"
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	communityCommentEmojisFieldNames          = builder.RawFieldNames(&CommunityCommentEmoji{})
	communityCommentEmojisRows                = strings.Join(communityCommentEmojisFieldNames, ",")
	communityCommentEmojisRowsExpectAutoSet   = strings.Join(stringx.Remove(communityCommentEmojisFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	communityCommentEmojisRowsWithPlaceHolder = strings.Join(stringx.Remove(communityCommentEmojisFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	communityCommentEmojisModel interface {
		Insert(ctx context.Context, data *CommunityCommentEmoji) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*CommunityCommentEmoji, error)
		Update(ctx context.Context, data *CommunityCommentEmoji) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultCommunityCommentEmojisModel struct {
		conn  sqlx.SqlConn
		table string
	}

	CommunityCommentEmoji struct {
		ID        uint64    `db:"id"`
		Name      string    `db:"name"`
		ImageURL  string    `db:"image_url"`
		Sort      int     `db:"sort"`
		Status    int     `db:"status"` // 1上架 0下架
		CreatedAt common.LocalTime `db:"created_at"`
		UpdatedAt common.LocalTime `db:"updated_at"`
	}
)

func newCommunityCommentEmojisModel(conn sqlx.SqlConn) *defaultCommunityCommentEmojisModel {
	return &defaultCommunityCommentEmojisModel{
		conn:  conn,
		table: "`community_comment_emojis`",
	}
}

func (m *defaultCommunityCommentEmojisModel) Delete(ctx context.Context, id uint64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultCommunityCommentEmojisModel) FindOne(ctx context.Context, id uint64) (*CommunityCommentEmoji, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", communityCommentEmojisRows, m.table)
	var resp CommunityCommentEmoji
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultCommunityCommentEmojisModel) Insert(ctx context.Context, data *CommunityCommentEmoji) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?)", m.table, communityCommentEmojisRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Name, data.ImageURL, data.Sort, data.Status)
	return ret, err
}

func (m *defaultCommunityCommentEmojisModel) Update(ctx context.Context, data *CommunityCommentEmoji) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, communityCommentEmojisRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.Name, data.ImageURL, data.Sort, data.Status, data.ID)
	return err
}

func (m *defaultCommunityCommentEmojisModel) tableName() string {
	return m.table
}
