// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.8.5

package modelgen

import (
	"mymall/common"
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	communityArticleImgFieldNames          = builder.RawFieldNames(&CommunityArticleImg{})
	communityArticleImgRows                = strings.Join(communityArticleImgFieldNames, ",")
	communityArticleImgRowsExpectAutoSet   = strings.Join(stringx.Remove(communityArticleImgFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	communityArticleImgRowsWithPlaceHolder = strings.Join(stringx.Remove(communityArticleImgFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	communityArticleImgModel interface {
		Insert(ctx context.Context, data *CommunityArticleImg) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*CommunityArticleImg, error)
		Update(ctx context.Context, data *CommunityArticleImg) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultCommunityArticleImgModel struct {
		conn  sqlx.SqlConn
		table string
	}

	CommunityArticleImg struct {
		ID        uint64    `db:"id"`
		ArticleID uint64    `db:"article_id"`
		ShopID    uint64    `db:"shop_id"`
		URL       string    `db:"url"`
		Sort      int     `db:"sort"`
		CreatedAt common.LocalTime `db:"created_at"`
	}
)

func newCommunityArticleImgModel(conn sqlx.SqlConn) *defaultCommunityArticleImgModel {
	return &defaultCommunityArticleImgModel{
		conn:  conn,
		table: "`community_article_img`",
	}
}

func (m *defaultCommunityArticleImgModel) Delete(ctx context.Context, id uint64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultCommunityArticleImgModel) FindOne(ctx context.Context, id uint64) (*CommunityArticleImg, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", communityArticleImgRows, m.table)
	var resp CommunityArticleImg
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultCommunityArticleImgModel) Insert(ctx context.Context, data *CommunityArticleImg) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?)", m.table, communityArticleImgRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.ArticleID, data.ShopID, data.URL, data.Sort)
	return ret, err
}

func (m *defaultCommunityArticleImgModel) Update(ctx context.Context, data *CommunityArticleImg) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, communityArticleImgRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.ArticleID, data.ShopID, data.URL, data.Sort, data.ID)
	return err
}

func (m *defaultCommunityArticleImgModel) tableName() string {
	return m.table
}
