// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.8.5

package modelgen

import (
	"mymall/common"
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	communityArticleFieldNames          = builder.RawFieldNames(&CommunityArticle{})
	communityArticleRows                = strings.Join(communityArticleFieldNames, ",")
	communityArticleRowsExpectAutoSet   = strings.Join(stringx.Remove(communityArticleFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	communityArticleRowsWithPlaceHolder = strings.Join(stringx.Remove(communityArticleFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	communityArticleModel interface {
		Insert(ctx context.Context, data *CommunityArticle) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*CommunityArticle, error)
		Update(ctx context.Context, data *CommunityArticle) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultCommunityArticleModel struct {
		conn  sqlx.SqlConn
		table string
	}

	CommunityArticle struct {
		ID                uint64         `db:"id"`
		ShopID            uint64         `db:"shop_id"`
		CategoryID        uint64         `db:"category_id"`
		Title             string         `db:"title"`
		CoverURL          string         `db:"cover_url"`
		Content           string `db:"content"`
		AuditStatus       string         `db:"audit_status"`
		RejectReason      string         `db:"reject_reason"`
		Status            string         `db:"status"`
		SchedulePublishAt common.LocalTime   `db:"schedule_publish_at"`
		IsTop             int          `db:"is_top"`
		ViewCount         uint64         `db:"view_count"`
		LikeCount         uint64         `db:"like_count"`
		PublishedAt       common.LocalTime   `db:"published_at"`
		DeletedAt         common.LocalTime   `db:"deleted_at"`
		CreatedBy         uint64         `db:"created_by"`
		CreatedAt         common.LocalTime      `db:"created_at"`
		UpdatedAt         common.LocalTime      `db:"updated_at"`
	}
)

func newCommunityArticleModel(conn sqlx.SqlConn) *defaultCommunityArticleModel {
	return &defaultCommunityArticleModel{
		conn:  conn,
		table: "`community_article`",
	}
}

func (m *defaultCommunityArticleModel) Delete(ctx context.Context, id uint64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultCommunityArticleModel) FindOne(ctx context.Context, id uint64) (*CommunityArticle, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", communityArticleRows, m.table)
	var resp CommunityArticle
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultCommunityArticleModel) Insert(ctx context.Context, data *CommunityArticle) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, communityArticleRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.ShopID, data.CategoryID, data.Title, data.CoverURL, data.Content, data.AuditStatus, data.RejectReason, data.Status, data.SchedulePublishAt, data.IsTop, data.ViewCount, data.LikeCount, data.PublishedAt, data.DeletedAt, data.CreatedBy)
	return ret, err
}

func (m *defaultCommunityArticleModel) Update(ctx context.Context, data *CommunityArticle) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, communityArticleRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.ShopID, data.CategoryID, data.Title, data.CoverURL, data.Content, data.AuditStatus, data.RejectReason, data.Status, data.SchedulePublishAt, data.IsTop, data.ViewCount, data.LikeCount, data.PublishedAt, data.DeletedAt, data.CreatedBy, data.ID)
	return err
}

func (m *defaultCommunityArticleModel) tableName() string {
	return m.table
}
