// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.8.5

package modelgen

import (
	"mymall/common"
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	homepageBannersFieldNames          = builder.RawFieldNames(&HomepageBanner{})
	homepageBannersRows                = strings.Join(homepageBannersFieldNames, ",")
	homepageBannersRowsExpectAutoSet   = strings.Join(stringx.Remove(homepageBannersFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	homepageBannersRowsWithPlaceHolder = strings.Join(stringx.Remove(homepageBannersFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	homepageBannersModel interface {
		Insert(ctx context.Context, data *HomepageBanner) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*HomepageBanner, error)
		Update(ctx context.Context, data *HomepageBanner) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultHomepageBannersModel struct {
		conn  sqlx.SqlConn
		table string
	}

	HomepageBanner struct {
		ID        uint64       `db:"id"`
		Title     string       `db:"title"`
		ImageURL  string       `db:"image_url"`
		LinkType  string       `db:"link_type"`
		LinkID    uint64       `db:"link_id"`
		Sort      int        `db:"sort"`
		Status    string       `db:"status"`
		StartAt   common.LocalTime `db:"start_at"`
		EndAt     common.LocalTime `db:"end_at"`
		CreatedAt common.LocalTime    `db:"created_at"`
		UpdatedAt common.LocalTime    `db:"updated_at"`
	}
)

func newHomepageBannersModel(conn sqlx.SqlConn) *defaultHomepageBannersModel {
	return &defaultHomepageBannersModel{
		conn:  conn,
		table: "`homepage_banners`",
	}
}

func (m *defaultHomepageBannersModel) Delete(ctx context.Context, id uint64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultHomepageBannersModel) FindOne(ctx context.Context, id uint64) (*HomepageBanner, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", homepageBannersRows, m.table)
	var resp HomepageBanner
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultHomepageBannersModel) Insert(ctx context.Context, data *HomepageBanner) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?)", m.table, homepageBannersRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Title, data.ImageURL, data.LinkType, data.LinkID, data.Sort, data.Status, data.StartAt, data.EndAt)
	return ret, err
}

func (m *defaultHomepageBannersModel) Update(ctx context.Context, data *HomepageBanner) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, homepageBannersRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.Title, data.ImageURL, data.LinkType, data.LinkID, data.Sort, data.Status, data.StartAt, data.EndAt, data.ID)
	return err
}

func (m *defaultHomepageBannersModel) tableName() string {
	return m.table
}
