// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.8.5

package modelgen

import (
	"mymall/common"
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	productTagsFieldNames          = builder.RawFieldNames(&ProductTag{})
	productTagsRows                = strings.Join(productTagsFieldNames, ",")
	productTagsRowsExpectAutoSet   = strings.Join(stringx.Remove(productTagsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	productTagsRowsWithPlaceHolder = strings.Join(stringx.Remove(productTagsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	productTagsModel interface {
		Insert(ctx context.Context, data *ProductTag) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*ProductTag, error)
		FindOneByShopIdName(ctx context.Context, shopId uint64, name string) (*ProductTag, error)
		Update(ctx context.Context, data *ProductTag) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultProductTagsModel struct {
		conn  sqlx.SqlConn
		table string
	}

	ProductTag struct {
		ID        uint64    `db:"id"`
		ShopID    uint64    `db:"shop_id"`
		Name      string    `db:"name"`
		Color     string    `db:"color"`
		Status    int     `db:"status"`
		CreatedAt common.LocalTime `db:"created_at"`
		UpdatedAt common.LocalTime `db:"updated_at"`
	}
)

func newProductTagsModel(conn sqlx.SqlConn) *defaultProductTagsModel {
	return &defaultProductTagsModel{
		conn:  conn,
		table: "`product_tags`",
	}
}

func (m *defaultProductTagsModel) Delete(ctx context.Context, id uint64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultProductTagsModel) FindOne(ctx context.Context, id uint64) (*ProductTag, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", productTagsRows, m.table)
	var resp ProductTag
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultProductTagsModel) FindOneByShopIdName(ctx context.Context, shopId uint64, name string) (*ProductTag, error) {
	var resp ProductTag
	query := fmt.Sprintf("select %s from %s where `shop_id` = ? and `name` = ? limit 1", productTagsRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, shopId, name)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultProductTagsModel) Insert(ctx context.Context, data *ProductTag) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?)", m.table, productTagsRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.ShopID, data.Name, data.Color, data.Status)
	return ret, err
}

func (m *defaultProductTagsModel) Update(ctx context.Context, newData *ProductTag) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, productTagsRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.ShopID, newData.Name, newData.Color, newData.Status, newData.ID)
	return err
}

func (m *defaultProductTagsModel) tableName() string {
	return m.table
}
