// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.8.5

package modelgen

import (
	"mymall/common"
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	productImagesFieldNames          = builder.RawFieldNames(&ProductImage{})
	productImagesRows                = strings.Join(productImagesFieldNames, ",")
	productImagesRowsExpectAutoSet   = strings.Join(stringx.Remove(productImagesFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	productImagesRowsWithPlaceHolder = strings.Join(stringx.Remove(productImagesFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	productImagesModel interface {
		Insert(ctx context.Context, data *ProductImage) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*ProductImage, error)
		Update(ctx context.Context, data *ProductImage) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultProductImagesModel struct {
		conn  sqlx.SqlConn
		table string
	}

	ProductImage struct {
		ID        uint64    `db:"id"`
		ProductID uint64    `db:"product_id"`
		ShopID    uint64    `db:"shop_id"`
		URL       string    `db:"url"`
		Typ       string    `db:"typ"`
		Sort      int     `db:"sort"`
		CreatedAt common.LocalTime `db:"created_at"`
		UpdatedAt common.LocalTime `db:"updated_at"`
	}
)

func newProductImagesModel(conn sqlx.SqlConn) *defaultProductImagesModel {
	return &defaultProductImagesModel{
		conn:  conn,
		table: "`product_images`",
	}
}

func (m *defaultProductImagesModel) Delete(ctx context.Context, id uint64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultProductImagesModel) FindOne(ctx context.Context, id uint64) (*ProductImage, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", productImagesRows, m.table)
	var resp ProductImage
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultProductImagesModel) Insert(ctx context.Context, data *ProductImage) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?)", m.table, productImagesRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.ProductID, data.ShopID, data.URL, data.Typ, data.Sort)
	return ret, err
}

func (m *defaultProductImagesModel) Update(ctx context.Context, data *ProductImage) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, productImagesRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.ProductID, data.ShopID, data.URL, data.Typ, data.Sort, data.ID)
	return err
}

func (m *defaultProductImagesModel) tableName() string {
	return m.table
}
