// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.8.5

package modelgen

import (
	"mymall/common"
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	productSchedulesFieldNames          = builder.RawFieldNames(&ProductSchedule{})
	productSchedulesRows                = strings.Join(productSchedulesFieldNames, ",")
	productSchedulesRowsExpectAutoSet   = strings.Join(stringx.Remove(productSchedulesFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	productSchedulesRowsWithPlaceHolder = strings.Join(stringx.Remove(productSchedulesFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	productSchedulesModel interface {
		Insert(ctx context.Context, data *ProductSchedule) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*ProductSchedule, error)
		Update(ctx context.Context, data *ProductSchedule) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultProductSchedulesModel struct {
		conn  sqlx.SqlConn
		table string
	}

	ProductSchedule struct {
		ID        uint64       `db:"id"`
		ProductID uint64       `db:"product_id"`
		ShopID    uint64       `db:"shop_id"`
		Action    string       `db:"action"`
		RunAt     common.LocalTime    `db:"run_at"`
		Status    string       `db:"status"`
		LockedAt  common.LocalTime `db:"locked_at"`
		CreatedAt common.LocalTime    `db:"created_at"`
		UpdatedAt common.LocalTime    `db:"updated_at"`
	}
)

func newProductSchedulesModel(conn sqlx.SqlConn) *defaultProductSchedulesModel {
	return &defaultProductSchedulesModel{
		conn:  conn,
		table: "`product_schedules`",
	}
}

func (m *defaultProductSchedulesModel) Delete(ctx context.Context, id uint64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultProductSchedulesModel) FindOne(ctx context.Context, id uint64) (*ProductSchedule, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", productSchedulesRows, m.table)
	var resp ProductSchedule
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultProductSchedulesModel) Insert(ctx context.Context, data *ProductSchedule) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?)", m.table, productSchedulesRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.ProductID, data.ShopID, data.Action, data.RunAt, data.Status, data.LockedAt)
	return ret, err
}

func (m *defaultProductSchedulesModel) Update(ctx context.Context, data *ProductSchedule) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, productSchedulesRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.ProductID, data.ShopID, data.Action, data.RunAt, data.Status, data.LockedAt, data.ID)
	return err
}

func (m *defaultProductSchedulesModel) tableName() string {
	return m.table
}
