// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.8.5

package modelgen

import (
	"mymall/common"
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	productsFieldNames          = builder.RawFieldNames(&Product{})
	productsRows                = strings.Join(productsFieldNames, ",")
	productsRowsExpectAutoSet   = strings.Join(stringx.Remove(productsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	productsRowsWithPlaceHolder = strings.Join(stringx.Remove(productsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	productsModel interface {
		Insert(ctx context.Context, data *Product) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*Product, error)
		FindOneByProductNo(ctx context.Context, productNo string) (*Product, error)
		Update(ctx context.Context, data *Product) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultProductsModel struct {
		conn  sqlx.SqlConn
		table string
	}

	Product struct {
		ID               uint64          `db:"id"`
		ShopID           uint64          `db:"shop_id"`           // 所属店铺ID
		ProductNo        string          `db:"product_no"`        // 商品编号
		Name             string          `db:"name"`              // 商品名称
		Subtitle         string  `db:"subtitle"`          // 商品副标题
		Description      string  `db:"description"`       // 商品描述
		MainImage        string  `db:"main_image"`        // 主图
		ImageList        string  `db:"image_list"`        // 商品图片列表
		VideoURL         string  `db:"video_url"`         // 商品视频
		MarketPrice      sql.NullFloat64 `db:"market_price"`      // 市场价
		SalePrice        float64         `db:"sale_price"`        // 销售价
		CostPrice        sql.NullFloat64 `db:"cost_price"`        // 成本价
		Discount         float64         `db:"discount"`          // 折扣(百分比)
		DiscountPrice    sql.NullFloat64 `db:"discount_price"`    // 折后价
		Stock            int           `db:"stock"`             // 库存数量
		StockWarn        int           `db:"stock_warn"`        // 库存预警值
		SoldCount        int           `db:"sold_count"`        // 已售数量
		ViewCount        int           `db:"view_count"`        // 浏览数量
		CollectCount     int           `db:"collect_count"`     // 收藏数量
		PetType          string          `db:"pet_type"`          // 宠物类型
		PetAge           string  `db:"pet_age"`           // 适用年龄
		PetSize          string  `db:"pet_size"`          // 适用体型
		Weight           sql.NullFloat64 `db:"weight"`            // 重量(kg)
		Unit             string  `db:"unit"`              // 单位
		BrandID          sql.NullInt64   `db:"brand_id"`          // 品牌ID
		CategoryID       int           `db:"category_id"`       // 分类ID
		ProductType      string          `db:"product_type"`      // 商品类型
		SpecJSON         string  `db:"spec_json"`         // 规格定义
		Tags             string  `db:"tags"`              // 标签数组
		NutritionInfo    string  `db:"nutrition_info"`    // 营养成分表
		Ingredients      string  `db:"ingredients"`       // 主要成分
		FeedingGuide     string  `db:"feeding_guide"`     // 喂养指南
		ShelfLife        sql.NullInt64   `db:"shelf_life"`        // 保质期(天)
		StorageCondition string  `db:"storage_condition"` // 存储条件
		Status           string          `db:"status"`            // 状态
		IsHot            int           `db:"is_hot"`            // 是否热销
		IsNew            int           `db:"is_new"`            // 是否新品
		IsRecommend      int           `db:"is_recommend"`      // 是否推荐
		IsPrescription   int           `db:"is_prescription"`   // 是否处方粮
		IsImported       int           `db:"is_imported"`       // 是否进口
		IsOrganic        int           `db:"is_organic"`        // 是否有机
		IsGrainFree      int           `db:"is_grain_free"`     // 是否无谷
		PublishTime      common.LocalTime    `db:"publish_time"`      // 上架时间
		ScheduleOnAt     common.LocalTime    `db:"schedule_on_at"`    // 定时上架
		ScheduleOffAt    common.LocalTime    `db:"schedule_off_at"`   // 定时下架
		CopyFromID       sql.NullInt64   `db:"copy_from_id"`      // 复制来源
		CreatedAt        common.LocalTime       `db:"created_at"`
		UpdatedAt        common.LocalTime       `db:"updated_at"`
		DeletedAt        common.LocalTime    `db:"deleted_at"`
	}
)

func newProductsModel(conn sqlx.SqlConn) *defaultProductsModel {
	return &defaultProductsModel{
		conn:  conn,
		table: "`products`",
	}
}

func (m *defaultProductsModel) Delete(ctx context.Context, id uint64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultProductsModel) FindOne(ctx context.Context, id uint64) (*Product, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", productsRows, m.table)
	var resp Product
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultProductsModel) FindOneByProductNo(ctx context.Context, productNo string) (*Product, error) {
	var resp Product
	query := fmt.Sprintf("select %s from %s where `product_no` = ? limit 1", productsRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, productNo)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultProductsModel) Insert(ctx context.Context, data *Product) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, productsRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.ShopID, data.ProductNo, data.Name, data.Subtitle, data.Description, data.MainImage, data.ImageList, data.VideoURL, data.MarketPrice, data.SalePrice, data.CostPrice, data.Discount, data.DiscountPrice, data.Stock, data.StockWarn, data.SoldCount, data.ViewCount, data.CollectCount, data.PetType, data.PetAge, data.PetSize, data.Weight, data.Unit, data.BrandID, data.CategoryID, data.ProductType, data.SpecJSON, data.Tags, data.NutritionInfo, data.Ingredients, data.FeedingGuide, data.ShelfLife, data.StorageCondition, data.Status, data.IsHot, data.IsNew, data.IsRecommend, data.IsPrescription, data.IsImported, data.IsOrganic, data.IsGrainFree, data.PublishTime, data.ScheduleOnAt, data.ScheduleOffAt, data.CopyFromID, data.DeletedAt)
	return ret, err
}

func (m *defaultProductsModel) Update(ctx context.Context, newData *Product) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, productsRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.ShopID, newData.ProductNo, newData.Name, newData.Subtitle, newData.Description, newData.MainImage, newData.ImageList, newData.VideoURL, newData.MarketPrice, newData.SalePrice, newData.CostPrice, newData.Discount, newData.DiscountPrice, newData.Stock, newData.StockWarn, newData.SoldCount, newData.ViewCount, newData.CollectCount, newData.PetType, newData.PetAge, newData.PetSize, newData.Weight, newData.Unit, newData.BrandID, newData.CategoryID, newData.ProductType, newData.SpecJSON, newData.Tags, newData.NutritionInfo, newData.Ingredients, newData.FeedingGuide, newData.ShelfLife, newData.StorageCondition, newData.Status, newData.IsHot, newData.IsNew, newData.IsRecommend, newData.IsPrescription, newData.IsImported, newData.IsOrganic, newData.IsGrainFree, newData.PublishTime, newData.ScheduleOnAt, newData.ScheduleOffAt, newData.CopyFromID, newData.DeletedAt, newData.ID)
	return err
}

func (m *defaultProductsModel) tableName() string {
	return m.table
}
