// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.8.5

package modelgen

import (
	"mymall/common"
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	productCategoriesFieldNames          = builder.RawFieldNames(&ProductCategory{})
	productCategoriesRows                = strings.Join(productCategoriesFieldNames, ",")
	productCategoriesRowsExpectAutoSet   = strings.Join(stringx.Remove(productCategoriesFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	productCategoriesRowsWithPlaceHolder = strings.Join(stringx.Remove(productCategoriesFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	productCategoriesModel interface {
		Insert(ctx context.Context, data *ProductCategory) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*ProductCategory, error)
		Update(ctx context.Context, data *ProductCategory) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultProductCategoriesModel struct {
		conn  sqlx.SqlConn
		table string
	}

	ProductCategory struct {
		ID           uint64         `db:"id"`
		ParentID     int          `db:"parent_id"`     // 父分类ID
		Name         string         `db:"name"`          // 分类名称
		Icon         string `db:"icon"`          // 分类图标
		Image        string `db:"image"`         // 分类图片
		Description  string `db:"description"`   // 分类描述
		SortOrder    int          `db:"sort_order"`    // 排序
		Level        int          `db:"level"`         // 分类层级
		IsShow       int          `db:"is_show"`       // 是否显示
		ProductCount int          `db:"product_count"` // 商品数量
		CreatedAt    common.LocalTime      `db:"created_at"`
		UpdatedAt    common.LocalTime      `db:"updated_at"`
	}
)

func newProductCategoriesModel(conn sqlx.SqlConn) *defaultProductCategoriesModel {
	return &defaultProductCategoriesModel{
		conn:  conn,
		table: "`product_categories`",
	}
}

func (m *defaultProductCategoriesModel) Delete(ctx context.Context, id uint64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultProductCategoriesModel) FindOne(ctx context.Context, id uint64) (*ProductCategory, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", productCategoriesRows, m.table)
	var resp ProductCategory
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultProductCategoriesModel) Insert(ctx context.Context, data *ProductCategory) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, productCategoriesRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.ParentID, data.Name, data.Icon, data.Image, data.Description, data.SortOrder, data.Level, data.IsShow, data.ProductCount)
	return ret, err
}

func (m *defaultProductCategoriesModel) Update(ctx context.Context, data *ProductCategory) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, productCategoriesRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.ParentID, data.Name, data.Icon, data.Image, data.Description, data.SortOrder, data.Level, data.IsShow, data.ProductCount, data.ID)
	return err
}

func (m *defaultProductCategoriesModel) tableName() string {
	return m.table
}
