// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.8.5

package modelgen

import (
	"mymall/common"
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	productFavoritesFieldNames          = builder.RawFieldNames(&ProductFavorite{})
	productFavoritesRows                = strings.Join(productFavoritesFieldNames, ",")
	productFavoritesRowsExpectAutoSet   = strings.Join(stringx.Remove(productFavoritesFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	productFavoritesRowsWithPlaceHolder = strings.Join(stringx.Remove(productFavoritesFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	productFavoritesModel interface {
		Insert(ctx context.Context, data *ProductFavorite) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*ProductFavorite, error)
		FindOneByUserIdProductId(ctx context.Context, userId uint64, productId uint64) (*ProductFavorite, error)
		Update(ctx context.Context, data *ProductFavorite) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultProductFavoritesModel struct {
		conn  sqlx.SqlConn
		table string
	}

	ProductFavorite struct {
		ID        uint64    `db:"id"`
		UserID    uint64    `db:"user_id"`
		ProductID uint64    `db:"product_id"`
		CreatedAt common.LocalTime `db:"created_at"`
	}
)

func newProductFavoritesModel(conn sqlx.SqlConn) *defaultProductFavoritesModel {
	return &defaultProductFavoritesModel{
		conn:  conn,
		table: "`product_favorites`",
	}
}

func (m *defaultProductFavoritesModel) Delete(ctx context.Context, id uint64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultProductFavoritesModel) FindOne(ctx context.Context, id uint64) (*ProductFavorite, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", productFavoritesRows, m.table)
	var resp ProductFavorite
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultProductFavoritesModel) FindOneByUserIdProductId(ctx context.Context, userId uint64, productId uint64) (*ProductFavorite, error) {
	var resp ProductFavorite
	query := fmt.Sprintf("select %s from %s where `user_id` = ? and `product_id` = ? limit 1", productFavoritesRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, userId, productId)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultProductFavoritesModel) Insert(ctx context.Context, data *ProductFavorite) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?)", m.table, productFavoritesRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.UserID, data.ProductID)
	return ret, err
}

func (m *defaultProductFavoritesModel) Update(ctx context.Context, newData *ProductFavorite) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, productFavoritesRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.UserID, newData.ProductID, newData.ID)
	return err
}

func (m *defaultProductFavoritesModel) tableName() string {
	return m.table
}
