// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.8.5

package modelgen

import (
	"mymall/common"
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	productOpLogsFieldNames          = builder.RawFieldNames(&ProductOpLog{})
	productOpLogsRows                = strings.Join(productOpLogsFieldNames, ",")
	productOpLogsRowsExpectAutoSet   = strings.Join(stringx.Remove(productOpLogsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	productOpLogsRowsWithPlaceHolder = strings.Join(stringx.Remove(productOpLogsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	productOpLogsModel interface {
		Insert(ctx context.Context, data *ProductOpLog) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*ProductOpLog, error)
		Update(ctx context.Context, data *ProductOpLog) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultProductOpLogsModel struct {
		conn  sqlx.SqlConn
		table string
	}

	ProductOpLog struct {
		ID         uint64         `db:"id"`
		ShopID     uint64         `db:"shop_id"`
		ProductID  sql.NullInt64  `db:"product_id"`
		OperatorID uint64         `db:"operator_id"`
		Action     string         `db:"action"`
		BeforeJSON string `db:"before_json"`
		AfterJSON  string `db:"after_json"`
		IP         string         `db:"ip"`
		CreatedAt  common.LocalTime      `db:"created_at"`
	}
)

func newProductOpLogsModel(conn sqlx.SqlConn) *defaultProductOpLogsModel {
	return &defaultProductOpLogsModel{
		conn:  conn,
		table: "`product_op_logs`",
	}
}

func (m *defaultProductOpLogsModel) Delete(ctx context.Context, id uint64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultProductOpLogsModel) FindOne(ctx context.Context, id uint64) (*ProductOpLog, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", productOpLogsRows, m.table)
	var resp ProductOpLog
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultProductOpLogsModel) Insert(ctx context.Context, data *ProductOpLog) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?)", m.table, productOpLogsRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.ShopID, data.ProductID, data.OperatorID, data.Action, data.BeforeJSON, data.AfterJSON, data.IP)
	return ret, err
}

func (m *defaultProductOpLogsModel) Update(ctx context.Context, data *ProductOpLog) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, productOpLogsRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.ShopID, data.ProductID, data.OperatorID, data.Action, data.BeforeJSON, data.AfterJSON, data.IP, data.ID)
	return err
}

func (m *defaultProductOpLogsModel) tableName() string {
	return m.table
}
