// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.8.5

package modelgen

import (
	"mymall/common"
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	productSkusFieldNames          = builder.RawFieldNames(&ProductSku{})
	productSkusRows                = strings.Join(productSkusFieldNames, ",")
	productSkusRowsExpectAutoSet   = strings.Join(stringx.Remove(productSkusFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	productSkusRowsWithPlaceHolder = strings.Join(stringx.Remove(productSkusFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	productSkusModel interface {
		Insert(ctx context.Context, data *ProductSku) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*ProductSku, error)
		FindOneByProductIdSpecKey(ctx context.Context, productId uint64, specKey string) (*ProductSku, error)
		FindOneBySkuNo(ctx context.Context, skuNo string) (*ProductSku, error)
		Update(ctx context.Context, data *ProductSku) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultProductSkusModel struct {
		conn  sqlx.SqlConn
		table string
	}

	ProductSku struct {
		ID          uint64          `db:"id"`
		ProductID   uint64          `db:"product_id"`  // 商品ID
		ShopID      uint64          `db:"shop_id"`     // 店铺ID
		SKUNo       string          `db:"sku_no"`      // SKU编码
		SpecValues  string          `db:"spec_values"` // 规格值
		SpecKey     string          `db:"spec_key"`    // 规格唯一键
		SalePrice   float64         `db:"sale_price"`  // 售价
		MarketPrice sql.NullFloat64 `db:"market_price"`
		CostPrice   sql.NullFloat64 `db:"cost_price"`
		Stock       int           `db:"stock"`
		StockWarn   int           `db:"stock_warn"`
		Barcode     string  `db:"barcode"`
		Status      string          `db:"status"`
		SoldCount   int           `db:"sold_count"`
		CreatedAt   common.LocalTime       `db:"created_at"`
		UpdatedAt   common.LocalTime       `db:"updated_at"`
		DeletedAt   common.LocalTime    `db:"deleted_at"`
	}
)

func newProductSkusModel(conn sqlx.SqlConn) *defaultProductSkusModel {
	return &defaultProductSkusModel{
		conn:  conn,
		table: "`product_skus`",
	}
}

func (m *defaultProductSkusModel) Delete(ctx context.Context, id uint64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultProductSkusModel) FindOne(ctx context.Context, id uint64) (*ProductSku, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", productSkusRows, m.table)
	var resp ProductSku
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultProductSkusModel) FindOneByProductIdSpecKey(ctx context.Context, productId uint64, specKey string) (*ProductSku, error) {
	var resp ProductSku
	query := fmt.Sprintf("select %s from %s where `product_id` = ? and `spec_key` = ? limit 1", productSkusRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, productId, specKey)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultProductSkusModel) FindOneBySkuNo(ctx context.Context, skuNo string) (*ProductSku, error) {
	var resp ProductSku
	query := fmt.Sprintf("select %s from %s where `sku_no` = ? limit 1", productSkusRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, skuNo)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultProductSkusModel) Insert(ctx context.Context, data *ProductSku) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, productSkusRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.ProductID, data.ShopID, data.SKUNo, data.SpecValues, data.SpecKey, data.SalePrice, data.MarketPrice, data.CostPrice, data.Stock, data.StockWarn, data.Barcode, data.Status, data.SoldCount, data.DeletedAt)
	return ret, err
}

func (m *defaultProductSkusModel) Update(ctx context.Context, newData *ProductSku) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, productSkusRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.ProductID, newData.ShopID, newData.SKUNo, newData.SpecValues, newData.SpecKey, newData.SalePrice, newData.MarketPrice, newData.CostPrice, newData.Stock, newData.StockWarn, newData.Barcode, newData.Status, newData.SoldCount, newData.DeletedAt, newData.ID)
	return err
}

func (m *defaultProductSkusModel) tableName() string {
	return m.table
}
