// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.8.5

package modelgen

import (
	"mymall/common"
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	productAttrTemplatesFieldNames          = builder.RawFieldNames(&ProductAttrTemplate{})
	productAttrTemplatesRows                = strings.Join(productAttrTemplatesFieldNames, ",")
	productAttrTemplatesRowsExpectAutoSet   = strings.Join(stringx.Remove(productAttrTemplatesFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	productAttrTemplatesRowsWithPlaceHolder = strings.Join(stringx.Remove(productAttrTemplatesFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	productAttrTemplatesModel interface {
		Insert(ctx context.Context, data *ProductAttrTemplate) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*ProductAttrTemplate, error)
		Update(ctx context.Context, data *ProductAttrTemplate) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultProductAttrTemplatesModel struct {
		conn  sqlx.SqlConn
		table string
	}

	ProductAttrTemplate struct {
		ID        uint64    `db:"id"`
		ShopID    uint64    `db:"shop_id"`
		Name      string    `db:"name"`
		AttrsJSON string    `db:"attrs_json"`
		Status    int     `db:"status"`
		CreatedAt common.LocalTime `db:"created_at"`
		UpdatedAt common.LocalTime `db:"updated_at"`
	}
)

func newProductAttrTemplatesModel(conn sqlx.SqlConn) *defaultProductAttrTemplatesModel {
	return &defaultProductAttrTemplatesModel{
		conn:  conn,
		table: "`product_attr_templates`",
	}
}

func (m *defaultProductAttrTemplatesModel) Delete(ctx context.Context, id uint64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultProductAttrTemplatesModel) FindOne(ctx context.Context, id uint64) (*ProductAttrTemplate, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", productAttrTemplatesRows, m.table)
	var resp ProductAttrTemplate
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultProductAttrTemplatesModel) Insert(ctx context.Context, data *ProductAttrTemplate) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?)", m.table, productAttrTemplatesRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.ShopID, data.Name, data.AttrsJSON, data.Status)
	return ret, err
}

func (m *defaultProductAttrTemplatesModel) Update(ctx context.Context, data *ProductAttrTemplate) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, productAttrTemplatesRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.ShopID, data.Name, data.AttrsJSON, data.Status, data.ID)
	return err
}

func (m *defaultProductAttrTemplatesModel) tableName() string {
	return m.table
}
