// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.8.5

package modelgen

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	productAttrsFieldNames          = builder.RawFieldNames(&ProductAttr{})
	productAttrsRows                = strings.Join(productAttrsFieldNames, ",")
	productAttrsRowsExpectAutoSet   = strings.Join(stringx.Remove(productAttrsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	productAttrsRowsWithPlaceHolder = strings.Join(stringx.Remove(productAttrsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	productAttrsModel interface {
		Insert(ctx context.Context, data *ProductAttr) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*ProductAttr, error)
		Update(ctx context.Context, data *ProductAttr) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultProductAttrsModel struct {
		conn  sqlx.SqlConn
		table string
	}

	ProductAttr struct {
		ID         uint64        `db:"id"`
		ProductID  uint64        `db:"product_id"`
		TemplateID sql.NullInt64 `db:"template_id"`
		AttrKey    string        `db:"attr_key"`
		AttrLabel  string        `db:"attr_label"`
		AttrValue  string        `db:"attr_value"`
	}
)

func newProductAttrsModel(conn sqlx.SqlConn) *defaultProductAttrsModel {
	return &defaultProductAttrsModel{
		conn:  conn,
		table: "`product_attrs`",
	}
}

func (m *defaultProductAttrsModel) Delete(ctx context.Context, id uint64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultProductAttrsModel) FindOne(ctx context.Context, id uint64) (*ProductAttr, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", productAttrsRows, m.table)
	var resp ProductAttr
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultProductAttrsModel) Insert(ctx context.Context, data *ProductAttr) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?)", m.table, productAttrsRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.ProductID, data.TemplateID, data.AttrKey, data.AttrLabel, data.AttrValue)
	return ret, err
}

func (m *defaultProductAttrsModel) Update(ctx context.Context, data *ProductAttr) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, productAttrsRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.ProductID, data.TemplateID, data.AttrKey, data.AttrLabel, data.AttrValue, data.ID)
	return err
}

func (m *defaultProductAttrsModel) tableName() string {
	return m.table
}
