// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.8.5

package modelgen

import (
	"mymall/common"
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	productBatchJobsFieldNames          = builder.RawFieldNames(&ProductBatchJob{})
	productBatchJobsRows                = strings.Join(productBatchJobsFieldNames, ",")
	productBatchJobsRowsExpectAutoSet   = strings.Join(stringx.Remove(productBatchJobsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	productBatchJobsRowsWithPlaceHolder = strings.Join(stringx.Remove(productBatchJobsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	productBatchJobsModel interface {
		Insert(ctx context.Context, data *ProductBatchJob) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*ProductBatchJob, error)
		Update(ctx context.Context, data *ProductBatchJob) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultProductBatchJobsModel struct {
		conn  sqlx.SqlConn
		table string
	}

	ProductBatchJob struct {
		ID          uint64    `db:"id"`
		ShopID      uint64    `db:"shop_id"`
		JobType     string    `db:"job_type"`
		PayloadJSON string    `db:"payload_json"`
		Progress    int     `db:"progress"`
		Total       int     `db:"total"`
		Status      string    `db:"status"`
		ResultMsg   string    `db:"result_msg"`
		OperatorID  uint64    `db:"operator_id"`
		CreatedAt   common.LocalTime `db:"created_at"`
		UpdatedAt   common.LocalTime `db:"updated_at"`
	}
)

func newProductBatchJobsModel(conn sqlx.SqlConn) *defaultProductBatchJobsModel {
	return &defaultProductBatchJobsModel{
		conn:  conn,
		table: "`product_batch_jobs`",
	}
}

func (m *defaultProductBatchJobsModel) Delete(ctx context.Context, id uint64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultProductBatchJobsModel) FindOne(ctx context.Context, id uint64) (*ProductBatchJob, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", productBatchJobsRows, m.table)
	var resp ProductBatchJob
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultProductBatchJobsModel) Insert(ctx context.Context, data *ProductBatchJob) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?)", m.table, productBatchJobsRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.ShopID, data.JobType, data.PayloadJSON, data.Progress, data.Total, data.Status, data.ResultMsg, data.OperatorID)
	return ret, err
}

func (m *defaultProductBatchJobsModel) Update(ctx context.Context, data *ProductBatchJob) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, productBatchJobsRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.ShopID, data.JobType, data.PayloadJSON, data.Progress, data.Total, data.Status, data.ResultMsg, data.OperatorID, data.ID)
	return err
}

func (m *defaultProductBatchJobsModel) tableName() string {
	return m.table
}
