// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.8.5

package modelgen

import (
	"mymall/common"
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	shopMenusFieldNames          = builder.RawFieldNames(&ShopMenu{})
	shopMenusRows                = strings.Join(shopMenusFieldNames, ",")
	shopMenusRowsExpectAutoSet   = strings.Join(stringx.Remove(shopMenusFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	shopMenusRowsWithPlaceHolder = strings.Join(stringx.Remove(shopMenusFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	shopMenusModel interface {
		Insert(ctx context.Context, data *ShopMenu) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*ShopMenu, error)
		Update(ctx context.Context, data *ShopMenu) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultShopMenusModel struct {
		conn  sqlx.SqlConn
		table string
	}

	ShopMenu struct {
		ID        uint64    `db:"id"`
		ParentID  uint64    `db:"parent_id"`
		Name      string    `db:"name"`
		Type      string    `db:"type"`
		Path      string    `db:"path"`
		Component string    `db:"component"`
		Icon      string    `db:"icon"`
		Perms     string    `db:"perms"`
		Sort      int     `db:"sort"`
		Visible   int     `db:"visible"`
		Status    int     `db:"status"`
		CreatedAt common.LocalTime `db:"created_at"`
		UpdatedAt common.LocalTime `db:"updated_at"`
	}
)

func newShopMenusModel(conn sqlx.SqlConn) *defaultShopMenusModel {
	return &defaultShopMenusModel{
		conn:  conn,
		table: "`shop_menus`",
	}
}

func (m *defaultShopMenusModel) Delete(ctx context.Context, id uint64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultShopMenusModel) FindOne(ctx context.Context, id uint64) (*ShopMenu, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", shopMenusRows, m.table)
	var resp ShopMenu
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultShopMenusModel) Insert(ctx context.Context, data *ShopMenu) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, shopMenusRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.ParentID, data.Name, data.Type, data.Path, data.Component, data.Icon, data.Perms, data.Sort, data.Visible, data.Status)
	return ret, err
}

func (m *defaultShopMenusModel) Update(ctx context.Context, data *ShopMenu) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, shopMenusRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.ParentID, data.Name, data.Type, data.Path, data.Component, data.Icon, data.Perms, data.Sort, data.Visible, data.Status, data.ID)
	return err
}

func (m *defaultShopMenusModel) tableName() string {
	return m.table
}
