// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.8.5

package modelgen

import (
	"mymall/common"
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	shopRolesFieldNames          = builder.RawFieldNames(&ShopRole{})
	shopRolesRows                = strings.Join(shopRolesFieldNames, ",")
	shopRolesRowsExpectAutoSet   = strings.Join(stringx.Remove(shopRolesFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	shopRolesRowsWithPlaceHolder = strings.Join(stringx.Remove(shopRolesFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	shopRolesModel interface {
		Insert(ctx context.Context, data *ShopRole) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*ShopRole, error)
		FindOneByShopIdCode(ctx context.Context, shopId uint64, code string) (*ShopRole, error)
		Update(ctx context.Context, data *ShopRole) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultShopRolesModel struct {
		conn  sqlx.SqlConn
		table string
	}

	ShopRole struct {
		ID        uint64    `db:"id"`
		ShopID    uint64    `db:"shop_id"`
		Code      string    `db:"code"`
		Name      string    `db:"name"`
		Status    int     `db:"status"`
		Remark    string    `db:"remark"`
		CreatedAt common.LocalTime `db:"created_at"`
		UpdatedAt common.LocalTime `db:"updated_at"`
	}
)

func newShopRolesModel(conn sqlx.SqlConn) *defaultShopRolesModel {
	return &defaultShopRolesModel{
		conn:  conn,
		table: "`shop_roles`",
	}
}

func (m *defaultShopRolesModel) Delete(ctx context.Context, id uint64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultShopRolesModel) FindOne(ctx context.Context, id uint64) (*ShopRole, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", shopRolesRows, m.table)
	var resp ShopRole
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultShopRolesModel) FindOneByShopIdCode(ctx context.Context, shopId uint64, code string) (*ShopRole, error) {
	var resp ShopRole
	query := fmt.Sprintf("select %s from %s where `shop_id` = ? and `code` = ? limit 1", shopRolesRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, shopId, code)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultShopRolesModel) Insert(ctx context.Context, data *ShopRole) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?)", m.table, shopRolesRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.ShopID, data.Code, data.Name, data.Status, data.Remark)
	return ret, err
}

func (m *defaultShopRolesModel) Update(ctx context.Context, newData *ShopRole) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, shopRolesRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.ShopID, newData.Code, newData.Name, newData.Status, newData.Remark, newData.ID)
	return err
}

func (m *defaultShopRolesModel) tableName() string {
	return m.table
}
