// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.8.5

package modelgen

import (
	"mymall/common"
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	shopNotificationsFieldNames          = builder.RawFieldNames(&ShopNotification{})
	shopNotificationsRows                = strings.Join(shopNotificationsFieldNames, ",")
	shopNotificationsRowsExpectAutoSet   = strings.Join(stringx.Remove(shopNotificationsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	shopNotificationsRowsWithPlaceHolder = strings.Join(stringx.Remove(shopNotificationsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	shopNotificationsModel interface {
		Insert(ctx context.Context, data *ShopNotification) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*ShopNotification, error)
		Update(ctx context.Context, data *ShopNotification) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultShopNotificationsModel struct {
		conn  sqlx.SqlConn
		table string
	}

	ShopNotification struct {
		ID        uint64    `db:"id"`
		ShopID    uint64    `db:"shop_id"`
		Type      string    `db:"type"`
		Title     string    `db:"title"`
		Content   string    `db:"content"`
		Link      string    `db:"link"`
		RefType   string    `db:"ref_type"`
		RefID     uint64    `db:"ref_id"`
		IsRead    int     `db:"is_read"`
		CreatedAt common.LocalTime `db:"created_at"`
	}
)

func newShopNotificationsModel(conn sqlx.SqlConn) *defaultShopNotificationsModel {
	return &defaultShopNotificationsModel{
		conn:  conn,
		table: "`shop_notifications`",
	}
}

func (m *defaultShopNotificationsModel) Delete(ctx context.Context, id uint64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultShopNotificationsModel) FindOne(ctx context.Context, id uint64) (*ShopNotification, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", shopNotificationsRows, m.table)
	var resp ShopNotification
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultShopNotificationsModel) Insert(ctx context.Context, data *ShopNotification) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?)", m.table, shopNotificationsRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.ShopID, data.Type, data.Title, data.Content, data.Link, data.RefType, data.RefID, data.IsRead)
	return ret, err
}

func (m *defaultShopNotificationsModel) Update(ctx context.Context, data *ShopNotification) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, shopNotificationsRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.ShopID, data.Type, data.Title, data.Content, data.Link, data.RefType, data.RefID, data.IsRead, data.ID)
	return err
}

func (m *defaultShopNotificationsModel) tableName() string {
	return m.table
}
