// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: user.proto

package userservice

import (
	"context"

	userv1 "mymall/api/gen/user/v1"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	EmptyResponse      = userv1.EmptyResponse
	GetAddressRequest  = userv1.GetAddressRequest
	GetAddressResponse = userv1.GetAddressResponse
	GetConfigRequest   = userv1.GetConfigRequest
	GetConfigResponse  = userv1.GetConfigResponse
	GetUserRequest     = userv1.GetUserRequest
	GetUserResponse    = userv1.GetUserResponse
	NotifyRequest      = userv1.NotifyRequest
	TaskEventRequest   = userv1.TaskEventRequest
	WalletOpRequest    = userv1.WalletOpRequest

	UserService interface {
		GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*GetUserResponse, error)
		GetAddress(ctx context.Context, in *GetAddressRequest, opts ...grpc.CallOption) (*GetAddressResponse, error)
		FreezeWallet(ctx context.Context, in *WalletOpRequest, opts ...grpc.CallOption) (*EmptyResponse, error)
		UnfreezeWallet(ctx context.Context, in *WalletOpRequest, opts ...grpc.CallOption) (*EmptyResponse, error)
		SettleWallet(ctx context.Context, in *WalletOpRequest, opts ...grpc.CallOption) (*EmptyResponse, error)
		Notify(ctx context.Context, in *NotifyRequest, opts ...grpc.CallOption) (*EmptyResponse, error)
		TaskEvent(ctx context.Context, in *TaskEventRequest, opts ...grpc.CallOption) (*EmptyResponse, error)
		GetConfig(ctx context.Context, in *GetConfigRequest, opts ...grpc.CallOption) (*GetConfigResponse, error)
	}

	defaultUserService struct {
		cli zrpc.Client
	}
)

func NewUserService(cli zrpc.Client) UserService {
	return &defaultUserService{
		cli: cli,
	}
}

func (m *defaultUserService) GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*GetUserResponse, error) {
	client := userv1.NewUserServiceClient(m.cli.Conn())
	return client.GetUser(ctx, in, opts...)
}

func (m *defaultUserService) GetAddress(ctx context.Context, in *GetAddressRequest, opts ...grpc.CallOption) (*GetAddressResponse, error) {
	client := userv1.NewUserServiceClient(m.cli.Conn())
	return client.GetAddress(ctx, in, opts...)
}

func (m *defaultUserService) FreezeWallet(ctx context.Context, in *WalletOpRequest, opts ...grpc.CallOption) (*EmptyResponse, error) {
	client := userv1.NewUserServiceClient(m.cli.Conn())
	return client.FreezeWallet(ctx, in, opts...)
}

func (m *defaultUserService) UnfreezeWallet(ctx context.Context, in *WalletOpRequest, opts ...grpc.CallOption) (*EmptyResponse, error) {
	client := userv1.NewUserServiceClient(m.cli.Conn())
	return client.UnfreezeWallet(ctx, in, opts...)
}

func (m *defaultUserService) SettleWallet(ctx context.Context, in *WalletOpRequest, opts ...grpc.CallOption) (*EmptyResponse, error) {
	client := userv1.NewUserServiceClient(m.cli.Conn())
	return client.SettleWallet(ctx, in, opts...)
}

func (m *defaultUserService) Notify(ctx context.Context, in *NotifyRequest, opts ...grpc.CallOption) (*EmptyResponse, error) {
	client := userv1.NewUserServiceClient(m.cli.Conn())
	return client.Notify(ctx, in, opts...)
}

func (m *defaultUserService) TaskEvent(ctx context.Context, in *TaskEventRequest, opts ...grpc.CallOption) (*EmptyResponse, error) {
	client := userv1.NewUserServiceClient(m.cli.Conn())
	return client.TaskEvent(ctx, in, opts...)
}

func (m *defaultUserService) GetConfig(ctx context.Context, in *GetConfigRequest, opts ...grpc.CallOption) (*GetConfigResponse, error) {
	client := userv1.NewUserServiceClient(m.cli.Conn())
	return client.GetConfig(ctx, in, opts...)
}
