// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5

package handler

import (
	"net/http"

	admin "mymall/services/user-service/internal/handler/admin"
	internalapi "mymall/services/user-service/internal/handler/internalapi"
	public "mymall/services/user-service/internal/handler/public"
	user "mymall/services/user-service/internal/handler/user"
	"mymall/services/user-service/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.RequestID, serverCtx.GatewayIdentity, serverCtx.RequirePlatformAdmin},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/admin/admins",
					Handler: admin.ListAdminsHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/v1/admin/admins",
					Handler: admin.CreateAdminHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/api/v1/admin/admins/:id/password",
					Handler: admin.ResetAdminPasswordHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/admin/admins/:id/roles",
					Handler: admin.GetAdminRolesHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/api/v1/admin/admins/:id/roles",
					Handler: admin.AssignAdminRolesHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/admin/auth/me",
					Handler: admin.AuthMeHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/admin/configs",
					Handler: admin.ListConfigsHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/api/v1/admin/configs",
					Handler: admin.SaveConfigsHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/admin/menus",
					Handler: admin.MenuTreeHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/v1/admin/menus",
					Handler: admin.CreateMenuHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/api/v1/admin/menus/:id",
					Handler: admin.UpdateMenuHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/api/v1/admin/menus/:id",
					Handler: admin.DeleteMenuHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/v1/admin/notifications/send",
					Handler: admin.AdminSendNotificationHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/admin/notifications/sends",
					Handler: admin.AdminListNotificationSendsHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/admin/notifications/sends/:id/recipients",
					Handler: admin.AdminListNotificationRecipientsHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/admin/roles",
					Handler: admin.ListRolesHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/v1/admin/roles",
					Handler: admin.CreateRoleHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/api/v1/admin/roles/:id",
					Handler: admin.UpdateRoleHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/api/v1/admin/roles/:id",
					Handler: admin.DeleteRoleHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/admin/roles/:id/menus",
					Handler: admin.GetRoleMenusHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/api/v1/admin/roles/:id/menus",
					Handler: admin.AssignRoleMenusHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/admin/tasks",
					Handler: admin.AdminListTasksHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/api/v1/admin/tasks/:id",
					Handler: admin.AdminUpdateTaskHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/admin/users",
					Handler: admin.ListUsersHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/admin/users/:id",
					Handler: admin.GetUserHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/api/v1/admin/users/:id",
					Handler: admin.UpdateUserHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/admin/users/:id/addresses",
					Handler: admin.AdminListUserAddressesHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/api/v1/admin/users/:id/password",
					Handler: admin.ResetUserPasswordHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/api/v1/admin/users/:id/status",
					Handler: admin.SetUserStatusHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/v1/admin/users/:id/token",
					Handler: admin.GenerateUserTokenHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/admin/users/:id/wallet",
					Handler: admin.AdminGetWalletHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/v1/admin/users/:id/wallet/adjust",
					Handler: admin.AdminAdjustWalletHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/admin/users/:id/wallet/logs",
					Handler: admin.AdminWalletLogsHandler(serverCtx),
				},
			}...,
		),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.RequestID},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/api/v1/internal/notifications",
					Handler: internalapi.InternalCreateNotificationHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/v1/internal/points/deduct",
					Handler: internalapi.InternalDeductPointsHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/v1/internal/points/refund",
					Handler: internalapi.InternalRefundPointsHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/v1/internal/tasks/events",
					Handler: internalapi.InternalEventHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/user/addresses/internal",
					Handler: internalapi.InternalGetHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/v1/user/wallet/freeze",
					Handler: internalapi.InternalFreezeWalletHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/v1/user/wallet/settle",
					Handler: internalapi.InternalSettleWalletHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/v1/user/wallet/unfreeze",
					Handler: internalapi.InternalUnfreezeWalletHandler(serverCtx),
				},
			}...,
		),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.RequestID},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/regions",
					Handler: public.ListRegionsHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/regions/tree",
					Handler: public.RegionTreeHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/v1/user/login",
					Handler: public.LoginHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/v1/user/register",
					Handler: public.RegisterHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/healthz",
					Handler: public.HealthzHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/metrics",
					Handler: public.MetricsHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/readyz",
					Handler: public.ReadyzHandler(serverCtx),
				},
			}...,
		),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.RequestID, serverCtx.UserFlexibleAuth},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/user/addresses",
					Handler: user.UserListAddressesHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/v1/user/addresses",
					Handler: user.UserCreateAddressHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/api/v1/user/addresses/:id",
					Handler: user.UserUpdateAddressHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/api/v1/user/addresses/:id",
					Handler: user.UserDeleteAddressHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/api/v1/user/addresses/:id/default",
					Handler: user.SetDefaultHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/user/notifications",
					Handler: user.ListNotificationsHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/v1/user/notifications/:id/read",
					Handler: user.MarkNotificationReadHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/v1/user/notifications/read-all",
					Handler: user.MarkAllNotificationsReadHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/user/notifications/unread-count",
					Handler: user.UnreadNotificationCountHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/user/points",
					Handler: user.UserPointsHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/user/points/logs",
					Handler: user.UserPointLogsHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/user/profile",
					Handler: user.UserProfileHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/user/tasks",
					Handler: user.UserListTasksHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/v1/user/tasks/:code/claim",
					Handler: user.UserClaimHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/v1/user/tasks/checkin",
					Handler: user.UserCheckinHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/v1/user/tasks/events",
					Handler: user.UserReportEventHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/user/wallet",
					Handler: user.UserGetWalletHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/user/wallet/logs",
					Handler: user.UserWalletLogsHandler(serverCtx),
				},
			}...,
		),
	)
}
