// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5

package handler

import (
	"net/http"

	"mymall/services/user-service/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.RequestID},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/api/v1/internal/notifications",
					Handler: InternalCreateNotificationHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/v1/internal/points/deduct",
					Handler: InternalDeductPointsHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/v1/internal/points/refund",
					Handler: InternalRefundPointsHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/v1/internal/tasks/events",
					Handler: InternalEventHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/regions",
					Handler: ListHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/regions/tree",
					Handler: TreeHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/user/addresses/internal",
					Handler: InternalGetHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/v1/user/login",
					Handler: LoginHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/v1/user/register",
					Handler: RegisterHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/v1/user/wallet/freeze",
					Handler: FreezeHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/v1/user/wallet/settle",
					Handler: SettleHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/v1/user/wallet/unfreeze",
					Handler: UnfreezeHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/healthz",
					Handler: HealthzHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/metrics",
					Handler: MetricsHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/readyz",
					Handler: ReadyzHandler(serverCtx),
				},
			}...,
		),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.RequestID, serverCtx.UserFlexibleAuth},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/user/addresses",
					Handler: List2Handler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/v1/user/addresses",
					Handler: CreateHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/api/v1/user/addresses/:id",
					Handler: UpdateHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/api/v1/user/addresses/:id",
					Handler: DeleteHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/api/v1/user/addresses/:id/default",
					Handler: SetDefaultHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/user/notifications",
					Handler: ListNotificationsHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/v1/user/notifications/:id/read",
					Handler: MarkNotificationReadHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/v1/user/notifications/read-all",
					Handler: MarkAllNotificationsReadHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/user/notifications/unread-count",
					Handler: UnreadNotificationCountHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/user/points",
					Handler: UserPointsHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/user/points/logs",
					Handler: UserPointLogsHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/user/profile",
					Handler: V1UserProfileHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/user/tasks",
					Handler: UserListTasksHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/v1/user/tasks/:code/claim",
					Handler: UserClaimHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/v1/user/tasks/checkin",
					Handler: UserCheckinHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/v1/user/tasks/events",
					Handler: UserReportEventHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/user/wallet",
					Handler: UserGetWalletHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/user/wallet/logs",
					Handler: UserWalletLogsHandler(serverCtx),
				},
			}...,
		),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.RequestID, serverCtx.GatewayIdentity, serverCtx.RequirePlatformAdmin},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/admin/admins",
					Handler: ListAdminsHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/v1/admin/admins",
					Handler: CreateAdminHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/api/v1/admin/admins/:id/password",
					Handler: ResetAdminPasswordHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/admin/admins/:id/roles",
					Handler: GetAdminRolesHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/api/v1/admin/admins/:id/roles",
					Handler: AssignAdminRolesHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/admin/auth/me",
					Handler: AuthMeHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/admin/configs",
					Handler: ListConfigsHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/api/v1/admin/configs",
					Handler: SaveConfigsHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/admin/menus",
					Handler: MenuTreeHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/v1/admin/menus",
					Handler: CreateMenuHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/api/v1/admin/menus/:id",
					Handler: UpdateMenuHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/api/v1/admin/menus/:id",
					Handler: DeleteMenuHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/v1/admin/notifications/send",
					Handler: AdminSendNotificationHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/admin/notifications/sends",
					Handler: AdminListNotificationSendsHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/admin/notifications/sends/:id/recipients",
					Handler: AdminListNotificationRecipientsHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/admin/roles",
					Handler: ListRolesHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/v1/admin/roles",
					Handler: CreateRoleHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/api/v1/admin/roles/:id",
					Handler: UpdateRoleHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/api/v1/admin/roles/:id",
					Handler: DeleteRoleHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/admin/roles/:id/menus",
					Handler: GetRoleMenusHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/api/v1/admin/roles/:id/menus",
					Handler: AssignRoleMenusHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/admin/tasks",
					Handler: AdminList2Handler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/api/v1/admin/tasks/:id",
					Handler: AdminUpdateHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/admin/users",
					Handler: ListUsersHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/admin/users/:id",
					Handler: GetUserHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/api/v1/admin/users/:id",
					Handler: UpdateUserHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/admin/users/:id/addresses",
					Handler: AdminListHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/api/v1/admin/users/:id/password",
					Handler: ResetUserPasswordHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/api/v1/admin/users/:id/status",
					Handler: SetUserStatusHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/v1/admin/users/:id/token",
					Handler: GenerateUserTokenHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/admin/users/:id/wallet",
					Handler: AdminGetWalletHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/v1/admin/users/:id/wallet/adjust",
					Handler: AdminAdjustWalletHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/admin/users/:id/wallet/logs",
					Handler: AdminWalletLogsHandler(serverCtx),
				},
			}...,
		),
	)
}
