// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package handler

import (
	"net/http"

	adminauth "mymall/services/user-service/internal/handler/admin/auth"
	adminconfig "mymall/services/user-service/internal/handler/admin/config"
	adminmenu "mymall/services/user-service/internal/handler/admin/menu"
	adminnotification "mymall/services/user-service/internal/handler/admin/notification"
	adminpoints_mall "mymall/services/user-service/internal/handler/admin/points_mall"
	adminrole "mymall/services/user-service/internal/handler/admin/role"
	adminstaff "mymall/services/user-service/internal/handler/admin/staff"
	admintask "mymall/services/user-service/internal/handler/admin/task"
	adminuser "mymall/services/user-service/internal/handler/admin/user"
	internalapiaddress "mymall/services/user-service/internal/handler/internalapi/address"
	internalapinotification "mymall/services/user-service/internal/handler/internalapi/notification"
	internalapipoints "mymall/services/user-service/internal/handler/internalapi/points"
	internalapitask "mymall/services/user-service/internal/handler/internalapi/task"
	internalapiwallet "mymall/services/user-service/internal/handler/internalapi/wallet"
	publicauth "mymall/services/user-service/internal/handler/public/auth"
	publichealth "mymall/services/user-service/internal/handler/public/health"
	publicpoints_mall "mymall/services/user-service/internal/handler/public/points_mall"
	publicregion "mymall/services/user-service/internal/handler/public/region"
	useraddress "mymall/services/user-service/internal/handler/user/address"
	usercps "mymall/services/user-service/internal/handler/user/cps"
	usernotification "mymall/services/user-service/internal/handler/user/notification"
	userpoints "mymall/services/user-service/internal/handler/user/points"
	userpoints_mall "mymall/services/user-service/internal/handler/user/points_mall"
	userprofile "mymall/services/user-service/internal/handler/user/profile"
	usertask "mymall/services/user-service/internal/handler/user/task"
	userwallet "mymall/services/user-service/internal/handler/user/wallet"
	"mymall/services/user-service/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.RequestID, serverCtx.GatewayIdentity, serverCtx.RequirePlatformAdmin},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/admin/auth/me",
					Handler: adminauth.AuthMeHandler(serverCtx),
				},
			}...,
		),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.RequestID, serverCtx.GatewayIdentity, serverCtx.RequirePlatformAdmin},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/admin/configs",
					Handler: adminconfig.ListConfigsHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/api/v1/admin/configs",
					Handler: adminconfig.SaveConfigsHandler(serverCtx),
				},
			}...,
		),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.RequestID, serverCtx.GatewayIdentity, serverCtx.RequirePlatformAdmin},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/admin/menus",
					Handler: adminmenu.MenuTreeHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/v1/admin/menus",
					Handler: adminmenu.CreateMenuHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/api/v1/admin/menus/:id",
					Handler: adminmenu.UpdateMenuHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/api/v1/admin/menus/:id",
					Handler: adminmenu.DeleteMenuHandler(serverCtx),
				},
			}...,
		),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.RequestID, serverCtx.GatewayIdentity, serverCtx.RequirePlatformAdmin},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/api/v1/admin/notifications/send",
					Handler: adminnotification.AdminSendNotificationHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/admin/notifications/sends",
					Handler: adminnotification.AdminListNotificationSendsHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/admin/notifications/sends/:id/recipients",
					Handler: adminnotification.AdminListNotificationRecipientsHandler(serverCtx),
				},
			}...,
		),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.RequestID, serverCtx.GatewayIdentity, serverCtx.RequirePlatformAdmin},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/admin/points-orders",
					Handler: adminpoints_mall.ListPointsOrdersHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/admin/points-orders/:id",
					Handler: adminpoints_mall.DetailPointsOrderHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/v1/admin/points-orders/:id/cancel",
					Handler: adminpoints_mall.CancelPointsOrderHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/v1/admin/points-orders/:id/complete",
					Handler: adminpoints_mall.CompletePointsOrderHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/api/v1/admin/points-orders/:id/remark",
					Handler: adminpoints_mall.RemarkPointsOrderHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/v1/admin/points-orders/:id/ship",
					Handler: adminpoints_mall.ShipPointsOrderHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/admin/points-products",
					Handler: adminpoints_mall.ListPointsProductsHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/v1/admin/points-products",
					Handler: adminpoints_mall.CreatePointsProductHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/admin/points-products/:id",
					Handler: adminpoints_mall.DetailPointsProductHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/api/v1/admin/points-products/:id",
					Handler: adminpoints_mall.UpdatePointsProductHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/api/v1/admin/points-products/:id",
					Handler: adminpoints_mall.DeletePointsProductHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/api/v1/admin/points-products/:id/status",
					Handler: adminpoints_mall.SetPointsProductStatusHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/v1/admin/points-products/upload",
					Handler: adminpoints_mall.UploadPointsProductHandler(serverCtx),
				},
			}...,
		),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.RequestID, serverCtx.GatewayIdentity, serverCtx.RequirePlatformAdmin},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/admin/roles",
					Handler: adminrole.ListRolesHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/v1/admin/roles",
					Handler: adminrole.CreateRoleHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/api/v1/admin/roles/:id",
					Handler: adminrole.UpdateRoleHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/api/v1/admin/roles/:id",
					Handler: adminrole.DeleteRoleHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/admin/roles/:id/menus",
					Handler: adminrole.GetRoleMenusHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/api/v1/admin/roles/:id/menus",
					Handler: adminrole.AssignRoleMenusHandler(serverCtx),
				},
			}...,
		),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.RequestID, serverCtx.GatewayIdentity, serverCtx.RequirePlatformAdmin},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/admin/admins",
					Handler: adminstaff.ListAdminsHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/v1/admin/admins",
					Handler: adminstaff.CreateAdminHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/api/v1/admin/admins/:id/password",
					Handler: adminstaff.ResetAdminPasswordHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/admin/admins/:id/roles",
					Handler: adminstaff.GetAdminRolesHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/api/v1/admin/admins/:id/roles",
					Handler: adminstaff.AssignAdminRolesHandler(serverCtx),
				},
			}...,
		),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.RequestID, serverCtx.GatewayIdentity, serverCtx.RequirePlatformAdmin},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/admin/tasks",
					Handler: admintask.AdminListTasksHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/api/v1/admin/tasks/:id",
					Handler: admintask.AdminUpdateTaskHandler(serverCtx),
				},
			}...,
		),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.RequestID, serverCtx.GatewayIdentity, serverCtx.RequirePlatformAdmin},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/admin/users",
					Handler: adminuser.ListUsersHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/admin/users/:id",
					Handler: adminuser.GetUserHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/api/v1/admin/users/:id",
					Handler: adminuser.UpdateUserHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/admin/users/:id/addresses",
					Handler: adminuser.AdminListUserAddressesHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/api/v1/admin/users/:id/password",
					Handler: adminuser.ResetUserPasswordHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/api/v1/admin/users/:id/status",
					Handler: adminuser.SetUserStatusHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/v1/admin/users/:id/token",
					Handler: adminuser.GenerateUserTokenHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/admin/users/:id/wallet",
					Handler: adminuser.AdminGetWalletHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/v1/admin/users/:id/wallet/adjust",
					Handler: adminuser.AdminAdjustWalletHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/admin/users/:id/wallet/logs",
					Handler: adminuser.AdminWalletLogsHandler(serverCtx),
				},
			}...,
		),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.RequestID},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/user/addresses/internal",
					Handler: internalapiaddress.InternalGetHandler(serverCtx),
				},
			}...,
		),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.RequestID},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/api/v1/internal/notifications",
					Handler: internalapinotification.InternalCreateNotificationHandler(serverCtx),
				},
			}...,
		),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.RequestID},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/api/v1/internal/points/deduct",
					Handler: internalapipoints.InternalDeductPointsHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/v1/internal/points/refund",
					Handler: internalapipoints.InternalRefundPointsHandler(serverCtx),
				},
			}...,
		),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.RequestID},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/api/v1/internal/tasks/events",
					Handler: internalapitask.InternalEventHandler(serverCtx),
				},
			}...,
		),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.RequestID},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/api/v1/user/wallet/freeze",
					Handler: internalapiwallet.InternalFreezeWalletHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/v1/user/wallet/settle",
					Handler: internalapiwallet.InternalSettleWalletHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/v1/user/wallet/unfreeze",
					Handler: internalapiwallet.InternalUnfreezeWalletHandler(serverCtx),
				},
			}...,
		),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.RequestID},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/api/v1/user/login",
					Handler: publicauth.LoginHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/v1/user/register",
					Handler: publicauth.RegisterHandler(serverCtx),
				},
			}...,
		),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.RequestID},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/healthz",
					Handler: publichealth.HealthzHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/metrics",
					Handler: publichealth.MetricsHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/readyz",
					Handler: publichealth.ReadyzHandler(serverCtx),
				},
			}...,
		),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.RequestID},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/uploads/points-mall/:file",
					Handler: publicpoints_mall.ServePointsMallUploadHandler(serverCtx),
				},
			}...,
		),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.RequestID},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/regions",
					Handler: publicregion.ListRegionsHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/regions/tree",
					Handler: publicregion.RegionTreeHandler(serverCtx),
				},
			}...,
		),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.RequestID, serverCtx.UserFlexibleAuth},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/user/addresses",
					Handler: useraddress.UserListAddressesHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/v1/user/addresses",
					Handler: useraddress.UserCreateAddressHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/api/v1/user/addresses/:id",
					Handler: useraddress.UserUpdateAddressHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/api/v1/user/addresses/:id",
					Handler: useraddress.UserDeleteAddressHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/api/v1/user/addresses/:id/default",
					Handler: useraddress.SetDefaultHandler(serverCtx),
				},
			}...,
		),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.RequestID, serverCtx.UserFlexibleAuth},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/user/notifications",
					Handler: usernotification.ListNotificationsHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/v1/user/notifications/:id/read",
					Handler: usernotification.MarkNotificationReadHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/v1/user/notifications/read-all",
					Handler: usernotification.MarkAllNotificationsReadHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/user/notifications/unread-count",
					Handler: usernotification.UnreadNotificationCountHandler(serverCtx),
				},
			}...,
		),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.RequestID, serverCtx.UserFlexibleAuth},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/user/points",
					Handler: userpoints.UserPointsHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/user/points/logs",
					Handler: userpoints.UserPointLogsHandler(serverCtx),
				},
			}...,
		),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.RequestID, serverCtx.GatewayIdentity},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/api/v1/user/points-mall/exchange",
					Handler: userpoints_mall.ExchangeHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/user/points-mall/orders",
					Handler: userpoints_mall.ListUserPointsOrdersHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/user/points-mall/orders/:id",
					Handler: userpoints_mall.DetailUserPointsOrderHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/user/points-mall/product",
					Handler: userpoints_mall.ListProductsHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/user/points-mall/product/:id",
					Handler: userpoints_mall.DetailProductHandler(serverCtx),
				},
			}...,
		),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.RequestID},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/user/cps/acts",
					Handler: usercps.ListActsHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/user/cps/goods",
					Handler: usercps.ListGoodsHandler(serverCtx),
				},
			}...,
		),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.RequestID, serverCtx.GatewayIdentity},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/api/v1/user/cps/convert",
					Handler: usercps.ConvertHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/v1/user/cps/goods/convert",
					Handler: usercps.ConvertGoodsHandler(serverCtx),
				},
			}...,
		),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.RequestID, serverCtx.UserFlexibleAuth},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/user/profile",
					Handler: userprofile.UserProfileHandler(serverCtx),
				},
			}...,
		),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.RequestID, serverCtx.UserFlexibleAuth},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/user/tasks",
					Handler: usertask.UserListTasksHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/v1/user/tasks/:code/claim",
					Handler: usertask.UserClaimHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/v1/user/tasks/checkin",
					Handler: usertask.UserCheckinHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/v1/user/tasks/events",
					Handler: usertask.UserReportEventHandler(serverCtx),
				},
			}...,
		),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.RequestID, serverCtx.UserFlexibleAuth},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/user/wallet",
					Handler: userwallet.UserGetWalletHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/user/wallet/logs",
					Handler: userwallet.UserWalletLogsHandler(serverCtx),
				},
			}...,
		),
	)
}
